(function(g){var window=this;'use strict';var QP=function(z){z.publish("cardstatechange",z.AU()&&z.Di()?1:0)},q_=function(z,K){var f=g.K1(K),M=f?K:arguments;
for(f=f?0:1;f<M.length;f++){if(z==null)return;z=z[M[f]]}return z},RY9=function(z){var K=g.J$(z);
z=g.dW(z);return new g.Ls(K.x,K.y,z.width,z.height)},SH5=function(z,K,f){var M=M===void 0?{}:M;
var p;return p=g.qm(z,K,function(){g.m6(p);f.apply(z,arguments)},M)},VP=function(z){z=g.M5(z);
delete m5[z];g.U9(m5)&&lw&&lw.stop()},Ld_=function(){lw||(lw=new g.Kl(function(){uY_()},20));
var z=lw;z.isActive()||z.start()},uY_=function(){var z=g.N5();
g.jS(m5,function(K){EN_(K,z)});
g.U9(m5)||Ld_()},nT=function(z,K,f,M){g.hU.call(this);
if(!Array.isArray(z)||!Array.isArray(K))throw Error("Start and end parameters must be arrays");if(z.length!=K.length)throw Error("Start and end points must be the same length");this.Y=z;this.G=K;this.duration=f;this.C=M;this.coords=[];this.progress=this.W=0;this.J=null},EN_=function(z,K){K<z.startTime&&(z.endTime=K+z.endTime-z.startTime,z.startTime=K);
z.progress=(K-z.startTime)/(z.endTime-z.startTime);z.progress>1&&(z.progress=1);z.W=1E3/(K-z.J);z.J=K;Pg_(z,z.progress);z.progress==1?(z.S=0,VP(z),z.onFinish(),z.ob()):z.isPlaying()&&z.pw()},Pg_=function(z,K){typeof z.C==="function"&&(K=z.C(K));
z.coords=Array(z.Y.length);for(var f=0;f<z.Y.length;f++)z.coords[f]=(z.G[f]-z.Y[f])*K+z.Y[f]},HCf=function(z,K){g.$Z.call(this,z);
this.coords=K.coords;this.x=K.coords[0];this.y=K.coords[1];this.z=K.coords[2];this.duration=K.duration;this.progress=K.progress;this.fps=K.W;this.state=K.S},Wn=function(z,K,f,M,p){nT.call(this,K,f,M,p);
this.element=z},Qjo=function(z,K,f,M,p){if(K.length!=2||f.length!=2)throw Error("Start and end points must be 2D");
Wn.call(this,z,K,f,M,p)},qH4=function(z){return Math.pow(z,3)},mWQ=function(z){return 3*z*z-2*z*z*z},ljT=function(z){g.J.call(this);
this.Y=z||window;this.S=[]},JD=function(z){return z.baseUrl||null},gC=function(z,K){return g.ds(g.UZ(z,K),function(f){return!!f})},VGT=function(z,K,f){function M(M8){var $S=M8.hovercardButton;
if(!$S)return null;$S=$S.subscribeButtonRenderer;if(!$S)return null;var td=t($S.unsubscribedButtonText),r=t($S.subscribedButtonText);if($S.subscribed){var yI=t($S.subscriberCountWithUnsubscribeText);var H5=t($S.subscriberCountText)}else yI=t($S.subscriberCountText),H5=t($S.subscriberCountWithSubscribeText);var ra=null;if(M8.signinEndpoint){ra=q_(M8,"signinEndpoint","webNavigationEndpointData","url");if(!ra){var Ho,I8;ra=(I8=g.A((Ho=$S.signInEndpoint)==null?void 0:Ho.commandMetadata,g.SZ))==null?void 0:
I8.url}if(!ra)return null}return td&&(r||ra)?{subscribed:$S.subscribed,subscribeText:td,subscribeCount:yI,unsubscribeText:r,unsubscribeCount:H5,enabled:$S.enabled,signinUrl:ra,classic:M8.useClassicSubscribeButton}:null}
function p(M8){if(M8){var $S=[],td=M8.videoId;td&&$S.push("v="+td);(td=M8.playlistId)&&$S.push("list="+td);(M8=M8.startTimeSeconds)&&$S.push("t="+M8);return"/watch?"+$S.join("&")}}
function t(M8){if(!M8)return null;var $S=M8.simpleText;return $S?$S:M8.runs?g.UZ(M8.runs,function(td){return td.text}).join(""):null}
K=K.endscreenElementRenderer;if(!K)return null;var B=K.style,v=K.endpoint||{},I=null,G=null,b=!1,e=null,w=null,D=null,y=null,R=!1,S=null,E=null,L=null,q=null,V=null,c=null;if(B==="VIDEO")g.A(v,g.Fc)?I=g.A(v,g.Fc).url:(c=g.A(v,g.f5),I=p(c)),G=!1,e=z,K.thumbnailOverlays?(b=K.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,w=t(b.text),b=b.style==="LIVE"):w=t(K.videoDuration);else if(B==="PLAYLIST")g.A(v,g.Fc)?I=g.A(v,g.Fc).url:(c=g.A(v,g.f5),I=p(c)),G=!1,e=z,D=t(K.playlistLength);else if(B===
"CHANNEL"){if(R=q_(v,"browseEndpoint","browseId"))y=R,I="/channel/"+y;G=!1;e="new";(R=!!K.isSubscribe)?S=M(K):E=t(K.subscribersText)}else B==="WEBSITE"?((L=q_(v,"urlEndpoint","url"))&&(I=L),G=!0,e="new",L=K.icon.thumbnails[0].url):B==="CREATOR_MERCHANDISE"&&(K.productPrice&&(q=t(K.productPrice)),K.additionalFeesText&&(V=t(K.additionalFeesText)),(G=q_(v,"urlEndpoint","url"))&&(I=G),G=!0,e="new");z=q_(K,"title","accessibility","accessibilityData","label");var O=K.endpoint?K.endpoint.clickTrackingParams:
null,x="";if(K.metadata){var T=t(K.metadata);T&&(x=T)}return{id:"element-"+f,type:B,title:t(K.title),metadata:x,callToAction:t(K.callToAction),Ow:K.image,iconUrl:L,left:Number(K.left),width:Number(K.width),top:Number(K.top),aspectRatio:Number(K.aspectRatio),startMs:Math.floor(Number(K.startMs)),endMs:Math.floor(Number(K.endMs)),videoDuration:w,J7:b,playlistLength:D,channelId:y,subscribeButton:S,subscribersText:E,isSubscribe:R,targetUrl:I||null,Xy:G,sessionData:O?{itct:O}:null,PWq:e,vU:z?z:null,isPlaceholder:K.isPlaceholder,
impressionUrls:gC(K.impressionUrls||[],JD),dY:gC(K.hovercardShowUrls||[],JD),clickUrls:gC(v.loggingUrls||[],JD),visualElement:g.qe(K.trackingParams),productPrice:q,additionalFeesText:V,watchEndpoint:c||null}},nNf=function(z,K){var f={startMs:Math.floor(Number(z.startMs)),
impressionUrls:gC(z.impressionUrls||[],JD),elements:gC(z.elements||[],function(M,p){return VGT(K,M,p)})};
z.trackingParams&&(f.visualElement=g.qe(z.trackingParams));return f},Wd2=function(z){g.R5.call(this,z);
this.J=this.endscreen=null;this.Y={};this.W={};this.C=this.T=null;this.D=[];this.S=null;this.Y1=!0;this.G=0;z=z.Z();this.N=g.Aw(z)||g.Yv(z);this.events=new g.xI(this);g.d(this,this.events);this.events.X(this.player,g.wE("creatorendscreen"),this.onCueRangeEnter);this.events.X(this.player,g.DU("creatorendscreen"),this.onCueRangeExit);this.events.X(this.player,"resize",this.NB);this.events.X(window,"focus",this.FPx);this.load();var K=g.zi("STYLE");(g.x7("HEAD")[0]||document.body).appendChild(K);this.addOnDisposeCallback(function(){g.ps(K)});
K.sheet&&(K.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),K.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},J4Z=function(z){return z.player.getVideoData().f3?"current":z.N?"new":"current"},iw=function(z){return z.player.Z().playerStyle==="creator-endscreen-editor"},gNZ=function(z){var K=z.player.getVideoData(),f=K.videoId;
z.J&&z.J.abort();f={method:"POST",onFinish:function(p){var t=z.J=null;p.status===200&&(p=p.responseText,p.substring(0,3)===")]}"&&(p=p.substring(3),t=JSON.parse(p),t=nNf(t,J4Z(z))));dC(z,t)},
urlParams:{v:f},withCredentials:!0};z.N&&(f.urlParams.ptype="embedded");var M=K.cJ;M&&(f.postParams={ad_tracking:M});if(K=g.H9v(K))if(K=g.rr(K),K=g.xo(K))z.J=g.V4(K,f)},dC=function(z,K,f){f=f===void 0?!0:f;
z.player.GE("creatorendscreen");z.T&&(z.T.dispose(),z.T=null,z.C.dispose(),z.C=null);for(var M=g.a(Object.values(z.Y)),p=M.next();!p.done;p=M.next())p.value.dispose();z.Y={};z.W={};z.D.length>0&&(z.D.forEach(function(v){v.dispose()}),z.D.length=0);
z.S&&(g.Dz(z.S,"ytp-ce-element-show"),z.S.setAttribute("aria-hidden","true"));z.G=0;if((z.endscreen=K)&&K.elements){f&&iCZ(z);f=[];M=new g.bS(K.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});f.push(M);z.player.Z().Y||(z.T=new g.F({j:"div",K:"ytp-ce-shadow"}),g.dq(z.player,z.T.element,4),z.C=new g.I3(z.T,200));for(M=0;M<K.elements.length;++M){p=K.elements[M];var t=dW7(z,p);if(t){z.Y[p.id]=t;z.W[p.id]=p;g.dq(z.player,t.element,4);var B=new g.bS(p.startMs,p.endMs,{id:"ytp-ce-element-"+
p.id,namespace:"creatorendscreen"});f.push(B);c4S(z,t,p)}else g.Al(new g.UT("buildEndscreenElement null",p))}z.player.St(f);z.NB()}},iCZ=function(z){var K=g.lc(),f=g.Vz();
f&&K&&z.endscreen.visualElement&&g.Mu(g.zU)(void 0,f,K,z.endscreen.visualElement)},dW7=function(z,K){var f=null;
switch(K.type){case "VIDEO":z={j:"div",Wx:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":K.vU||"","aria-hidden":"true"},L:[{j:"div",K:"ytp-ce-element-shadow"},{j:"div",K:"ytp-ce-covering-image",V:cn(K)},{j:"div",K:"ytp-ce-covering-shadow-top"},{j:"a",K:"ytp-ce-covering-overlay",V:{href:sO(z,K.targetUrl),tabindex:"-1"},L:[{j:"div",Wx:["ytp-ce-video-title","ytp-webkit-ellipsis"],V:{dir:g.Ll(K.title||"")},qc:K.title},{j:"div",K:K.J7?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
qc:K.videoDuration||void 0}]}]};f=new g.F(z);break;case "PLAYLIST":z={j:"div",Wx:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":K.vU||"","aria-hidden":"true"},L:[{j:"div",K:"ytp-ce-element-shadow"},{j:"div",K:"ytp-ce-covering-image",V:cn(K)},{j:"div",K:"ytp-ce-covering-shadow-top"},{j:"a",K:"ytp-ce-covering-overlay",V:{href:sO(z,K.targetUrl),tabindex:"-1"},L:[{j:"div",Wx:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],V:{dir:g.Ll(K.title||"")},qc:K.title},{j:"div",K:"ytp-ce-playlist-count",
L:[{j:"div",K:"ytp-ce-playlist-icon"},{j:"div",K:"ytp-ce-playlist-count-text",qc:K.playlistLength||void 0}]}]}]};f=new g.F(z);break;case "CHANNEL":f={j:"div",Wx:["ytp-ce-element","ytp-ce-channel",K.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":K.vU||"","aria-hidden":"true"},L:[{j:"div",K:"ytp-ce-element-shadow"},{j:"div",K:"ytp-ce-expanding-overlay",L:[{j:"div",K:"ytp-ce-expanding-overlay-hider"},{j:"div",K:"ytp-ce-expanding-overlay-background"},{j:"div",K:"ytp-ce-expanding-overlay-content",
L:[{j:"div",K:"ytp-ce-expanding-overlay-body",L:[{j:"div",K:"ytp-ce-expanding-overlay-body-padding",L:[{j:"a",Wx:["ytp-ce-channel-title","ytp-ce-link"],V:{href:sO(z,K.targetUrl),target:"_blank",tabindex:"-1",dir:g.Ll(K.title||"")},qc:K.title},K.subscribeButton?{j:"div",K:"ytp-ce-subscribe-container",L:[{j:"div",K:"ytp-ce-channel-subscribe"}]}:"",K.subscribersText?{j:"div",K:"ytp-ce-channel-subscribers-text",qc:K.subscribersText}:"",K.metadata?{j:"div",Wx:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],qc:K.metadata}:""]}]}]}]},{j:"div",K:"ytp-ce-expanding-image",V:cn(K)}]};f=new g.F(f);var M=g.Os(document,"div","ytp-ce-channel-subscribe",f.element)[0];if(K.subscribeButton&&K.channelId){g.ey(M,"ytp-ce-subscribe-button");if(z.player.Z().Y){var p=null;var t=K.sessionData.itct}else p="endscreen",t=null;p=new g.Ky(K.subscribeButton.subscribeText,K.subscribeButton.subscribeCount,K.subscribeButton.unsubscribeText,K.subscribeButton.unsubscribeCount,!!K.subscribeButton.enabled,!!K.subscribeButton.classic,
K.channelId,!!K.subscribeButton.subscribed,p,t,z.player,!1);M.appendChild(p.element);z.D.push(p)}break;case "WEBSITE":z={j:"div",Wx:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":K.vU||"","aria-hidden":"true"},L:[{j:"div",K:"ytp-ce-element-shadow"},{j:"div",K:"ytp-ce-expanding-overlay",L:[{j:"div",K:"ytp-ce-expanding-overlay-hider"},{j:"div",K:"ytp-ce-expanding-overlay-background"},{j:"div",K:"ytp-ce-expanding-overlay-content",L:[{j:"div",K:"ytp-ce-expanding-overlay-body",L:[{j:"div",
K:"ytp-ce-expanding-overlay-body-padding",L:[{j:"div",K:"ytp-ce-website-title",V:{dir:g.Ll(K.title||"")},qc:K.title},{j:"div",K:"ytp-ce-website-metadata",qc:K.metadata},{j:"a",Wx:["ytp-ce-website-goto","ytp-ce-link"],V:{href:sO(z,K.targetUrl),target:"_blank",tabindex:"-1"},qc:K.callToAction}]}]}]}]},{j:"div",K:"ytp-ce-expanding-image",V:cn(K)},{j:"div",K:"ytp-ce-expanding-icon",V:sjp(K.iconUrl)}]};f=new g.F(z);break;case "CREATOR_MERCHANDISE":f="",K.productPrice&&(f={j:"div",K:"ytp-ce-merchandise-price-container",
L:[{j:"div",K:"ytp-ce-merchandise-price",qc:K.productPrice}]},K.additionalFeesText&&f.L.push({j:"div",K:"ytp-ce-merchandise-additional-fees",qc:K.additionalFeesText})),z={j:"div",Wx:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":K.vU||"","aria-hidden":"true"},L:[{j:"div",K:"ytp-ce-element-shadow"},{j:"div",K:"ytp-ce-expanding-overlay",L:[{j:"div",K:"ytp-ce-expanding-overlay-hider"},{j:"div",K:"ytp-ce-expanding-overlay-background"},{j:"div",K:"ytp-ce-expanding-overlay-content",
L:[{j:"div",K:"ytp-ce-expanding-overlay-body",L:[{j:"div",K:"ytp-ce-expanding-overlay-body-padding",L:[{j:"div",K:"ytp-ce-merchandise-title",V:{dir:g.Ll(K.title||"")},qc:K.title},f,{j:"div",K:"ytp-ce-merchandise-metadata",qc:K.metadata},{j:"a",Wx:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:sO(z,K.targetUrl),target:"_blank",tabindex:"-1"},qc:K.callToAction}]}]}]}]},{j:"div",K:"ytp-ce-expanding-image",V:cn(K)},{j:"div",K:"ytp-ce-merchandise-invideo-cta-container",L:[{j:"div",K:"ytp-ce-merchandise-invideo-cta",
qc:K.callToAction||void 0}]}]},f=new g.F(z)}K.isPlaceholder&&g.ey(f.element,"ytp-ce-placeholder");return f},cn=function(z){if(z.Ow)var K=z.Ow.thumbnails;
return sjp(K?K[K.length-1].url:null)},sjp=function(z){return z?{style:"background-image: url("+z+")"}:{}},c4S=function(z,K,f){function M(I){I&&(K.listen("blur",function(){I.style.display!="none"&&z.Y1&&I.focus()}),K.X(I,"focus",t),K.X(I,"blur",B))}
function p(I){z.G+=I;z.G>0?(g.ey(K.element,"ytp-ce-force-expand"),AD(z,f.id,!0)):(g.Dz(K.element,"ytp-ce-force-expand"),g.Dz(K.element,"ytp-ce-element-hover"),AD(z,f.id,!1))}
function t(){p(1)}
function B(){p(-1)}
K.listen("mouseenter",function(){A4_(z,K,f)});
K.listen("mouseleave",function(){jj_(z,K,f)});
z.player.Z().Y||K.listen("click",function(){g.ey(K.element,"ytp-ce-element-hover")});
K.listen("click",function(I){YH5(z,f,I)});
K.listen("keypress",function(I){YH5(z,f,I)});
K.listen("focus",function(){A4_(z,K,f)});
K.listen("blur",function(){jj_(z,K,f)});
K.listen("touchstart",function(){A4_(z,K,f)});
var v=g.rT("ytp-ce-expanding-overlay-hider",K.element);v&&K.X(v,"touchstart",function(I){I.stopPropagation();g.Dz(K.element,"ytp-ce-element-hover");g.Dz(K.element,"ytp-ce-force-expand")});
K.listen("keydown",function(I){z.Y1=I.keyCode===9&&!I.shiftKey});
M(g.rT("ytp-sb-subscribe",K.element));M(g.rT("ytp-sb-unsubscribe",K.element));K.listen("focus",t);K.listen("blur",B)},YH5=function(z,K,f){if(K.targetUrl&&(!f||f.type!=="keypress"||f.keyCode===13)){for(var M=f.target;M&&!g.bx(M,"ytp-ce-element");){g.bx(M,"subscribe-label")&&Xi2(z,K);
if(g.bx(M,"ytp-ce-channel-subscribe"))return;M=M.parentElement||null}if(!M||g.bx(M,"ytp-ce-element-hover")){f.preventDefault();f.stopPropagation();if(M=z.Y[K.id])jj_(z,M,K),M.element.blur();if(f.ctrlKey||f.metaKey||K.PWq==="new")Xi2(z,K),z.player.sendVideoStatsEngageEvent(17,void 0),z.player.pauseVideo(),f=g.rr(sO(z,K.targetUrl)),f=g.xo(f),g.U$(f,void 0,K.sessionData);else{var p=g.$t(z.player.Z())||z.player.getVideoData().f3,t=function(){var B=sO(z,K.targetUrl),v=K.sessionData,I=K.watchEndpoint,G=
g.Iw(B);p&&G&&(G.v||G.list)?z.player.by(G.v,v,G.list,!1,void 0,I||void 0):g.Ts(B,v)};
Xi2(z,K,function(){z.player.sendVideoStatsEngageEvent(17,t)})}}}},sO=function(z,K){z=z.player.Z();
if(K){if(K.startsWith("//"))return z.protocol+":"+K;if(K.startsWith("/"))return g.vG(z)+K}else return"";return K},A4_=function(z,K,f){g.bx(K.element,"ytp-ce-element-hover")||(f.type==="VIDEO"||f.type==="PLAYLIST"?g.ey(K.element,"ytp-ce-element-hover"):z.player.Z().Y?(new g.Kl(function(){g.ey(K.element,"ytp-ce-element-hover")},200)).start():g.ey(K.element,"ytp-ce-element-hover"),jV(z,f.dY),AD(z,f.id,!0))},jj_=function(z,K,f){g.Dz(K.element,"ytp-ce-element-hover");
g.Dz(K.element,"ytp-ce-force-expand");AD(z,f.id,!1)},AD=function(z,K,f){z.T&&(f?z.C.show():z.C.hide());
for(var M=g.a(Object.keys(z.Y)),p=M.next();!p.done;p=M.next())p=p.value,p!==K&&g.k4(z.Y[p].element,"ytp-ce-element-shadow-show",f)},jV=function(z,K,f){function M(){t||(p++,p===K.length&&(B.stop(),f&&f()))}
if(!K||K.length===0||iw(z))f&&f();else{K=xW5(z,K);var p=0,t=!1,B=new g.Kl(function(){t=!0;f&&f()},1E3,z);
B.start();for(z=0;z<K.length;z++)g.F$(K[z],M)}},Xi2=function(z,K,f){jV(z,K.clickUrls,f);
(z=g.Vz())&&K.Xy&&g.bn(z,K.visualElement)},xW5=function(z,K){var f=z.player.getVideoData().clientPlaybackNonce;
z=z.player.getCurrentTime().toFixed(2);f={CPN:f,AD_CPN:f,MT:z};z=[];for(var M=0;M<K.length;M++)z.push(Fdo(K[M],f));return z},Fdo=function(z,K){return z.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(f){var M=unescape(f);
M=M.substring(1,M.length-1);return K[M]?escape(K[M]):f})},OC7=function(z){return typeof z==="string"?z:""},YA=function(z,K,f){for(var M in K)if(K[M]===z)return z;
return f},r4f=function(z,K,f,M){this.value=z;
this.target=K;this.showLinkIcon=f;this.S=M},XK=function(z){return z.value?z.value:null},xA=function(z){if(!z)return null;
var K=g.rr(OC7(z.value));K=g.xo(K);if(!K)return null;var f=YA(z.target,ZC9,"current");if(f==null)z=null;else{var M=z.show_link_icon;z=new r4f(K,f,M==="true"||M==="false"?M==="true":!0,z.pause_on_navigation!=null?z.pause_on_navigation:!0)}return z},oN5=function(z,K,f){this.type=z;
this.trigger=K;this.url=f},UWT=function(z){if(!z)return null;
var K=YA(z.type,Cg1),f=YA(z.trigger,Tk9);z=z.url;z=Array.isArray(z)&&z.length?z[0]:z;z=xA(z?z:null);return K?new oN5(K,f,z):null},zrT=function(z,K,f,M,p){this.id=z;
this.type=K;this.style=f;this.data=p;this.action=M||[]},KuQ=function(z,K){return g.yQ(z.action,K)},$Q_=function(z,K){this.context=z;
this.S=K},feH=function(z){return z.customMessage?FK("div","iv-card-message",z.customMessage):""},OO=function(z,K){z="background-image: url("+z+");";
var f=[];K&&f.push(K);return{j:"div",K:"iv-card-image",V:{style:z},L:f}},M2p=function(z){if(!z.metaInfo||z.metaInfo.length===0)return"";
var K=[];z=g.a(z.metaInfo);for(var f=z.next();!f.done;f=z.next())K.push(FK("li","",f.value));return{j:"ul",K:"iv-card-meta-info",L:K}},FK=function(z,K,f){K?typeof K==="string"?K={"class":K}:Array.isArray(K)&&(K={"class":K.join(" ")}):K={};
K.dir=g.Ll(f);return{j:z,V:K,qc:f}},p7f=function(z){if(!z.customMessage)return"";
var K=["iv-card-action","iv-card-primary-link"],f={};z.uZ&&(K.push("iv-card-action-icon"),f.style="background-image: url("+z.uZ+");");f.dir=g.Ll(z.customMessage);var M=[{j:"span",qc:z.customMessage}];z.showLinkIcon&&(M.push("\u00a0"),M.push({j:"span",K:"iv-card-link-icon"}));return{j:"div",Wx:K,V:f,L:M}},rC=function(z,K,f,M){if(M){K=g.a(K);
for(var p=K.next();!p.done;p=K.next())z.S(p.value,M,f.id,f.sessionData,f.Yv.click,5)}},t2T=function(z,K){this.merchant=z;
this.price=K},BjS=function(z){var K;
(K=z)&&!(K=z.length>1?z.charAt(0)==="/"&&z.charAt(1)!=="/":z==="/")&&(K=z.replace(/^(https?:)?\/\//,"").split("/",1),K=!K||K.length<1||!K[0]?[]:K[0].toLowerCase().split(".").reverse(),K=K[0]==="com"&&K[1]==="youtube"||K[0]==="be"&&K[1]==="youtu");return K?z.indexOf("/redirect?")===-1:!1},Nj1=function(z,K){return K?K:BjS(z)?"current":"new"},ZC=function(z,K){g.J.call(this);
var f=this;this.element=z;this.context=K;this.oa=!1;this.QE=new Map;this.b_=new Map;this.context.U.addEventListener(g.wE("annotations_module"),function(M){(M=f.QE.get(M))&&M.apply(f)});
this.context.U.addEventListener(g.DU("annotations_module"),function(M){(M=f.b_.get(M))&&M.apply(f)})},oX=function(z,K,f,M,p,t,B){z.context.S.listen(K,"click",function(v){z.dJ(f,M,p,t||[],B||0,v)});
z.context.S.listen(K,"touchstart",function(){z.oa=!1});
z.context.S.listen(K,"touchmove",function(){z.oa=!0})},vg9=function(z){var K;
return((K=g.A(z,g.Fc))==null?0:K.url)?g.A(z,g.Fc).url:(z=g.A(z,g.f5))&&z.videoId?(K="/watch?v="+z.videoId,z.playlistId&&(K+="&list="+z.playlistId),z.index&&(K+="&index="+z.index),z.startTimeSeconds&&(K+="&t="+z.startTimeSeconds),K):null},CT=function(z,K,f){return{cZ:(z.impressionLoggingUrlsV2s||[]).map(function(M){return M.baseUrl||""}),
click:(f.loggingUrls||[]).map(function(M){return M.baseUrl||""}),
close:(K.dismissLoggingUrlsV2s||[]).map(function(M){return M.baseUrl||""}),
UK:(K.impressionLoggingUrlsV2s||[]).map(function(M){return M.baseUrl||""}),
DJ:(K.clickLoggingUrlsV2s||[]).map(function(M){return M.baseUrl||""})}},Ie9=function(z,K,f){ZC.call(this,K,f);
var M=this;this.U=z;this.eventId=null;this.nI=this.vx=this.W1=this.T=this.isInitialized=!1;this.cards=[];this.SE=this.D=this.Bx=this.C=this.Xc=this.S=null;this.Y1=[];this.l_=this.G=this.wh=this.eV=null;this.W=0;this.Hx=new g.Kl(function(){},f.SV.Rf?4E3:3E3);
g.d(this,this.Hx);this.rE=new g.Kl(function(){});
g.d(this,this.rE);this.nH=new $Q_(f,function(p,t,B,v,I,G){oX(M,p,t,B,v,I,G)});
this.N=new g.F({j:"div",K:"iv-drawer",V:{id:"iv-drawer"},L:[{j:"div",K:"iv-drawer-header",V:{"aria-role":"heading"},L:[{j:"span",K:"iv-drawer-header-text"},{j:"button",Wx:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"Masquer les fiches",tabindex:"0"}}]},{j:"div",K:"iv-drawer-content"}]});g.d(this,this.N);this.J=this.N.element;this.VE=new g.I3(this.N,330);g.d(this,this.VE);this.TP=g.rT("iv-drawer-header-text",this.J);this.Y=g.rT("iv-drawer-content",this.J);this.addCueRange(0,f.videoData.lengthSeconds*
1E3,"",function(){M.W1&&Ty(M,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(M.W1=M.T)&&UO(M)});
this.Px=new g.xI(this);g.d(this,this.Px);this.U.addEventListener("videodatachange",this.Up.bind(this))},Gg7=function(z,K){K=K.data;
K.autoOpenMs&&z.addCueRange(K.autoOpenMs,0x8000000000000,"",function(){Ty(z,"YOUTUBE_DRAWER_AUTO_OPEN")});
K.autoCloseMs&&z.addCueRange(K.autoCloseMs,0x8000000000000,"",function(){UO(z)});
var f=K.headerText;g.B6(z.TP,f);z.D&&z.D.setAttribute("title",f);K.eventId&&(z.eventId=K.eventId);z.eV=g.qe(K.trackingParams);z.G=g.qe(K.closeTrackingParams);z.wh=g.qe(K.iconTrackingParams)},bPp=function(z,K){var f=K.cardId?K.cardId:"cr:"+z.W,M=z.U.Z().experiments.sf("enable_error_corrections_infocard_web_client");
if(!K.content&&K.teaser.simpleCardTeaserRenderer&&M){var p=K.teaser.simpleCardTeaserRenderer,t=K.icon?K.icon.infoCardIconRenderer:null;if(p.channelAvatar&&p.channelAvatar.thumbnails&&p.channelAvatar.thumbnails.length>0)var B=zK(p.channelAvatar.thumbnails,22,22).url;K={id:f,timestamp:z.W,type:"simple",teaserText:g.Lc(p.message),teaserDurationMs:Number(K.cueRanges[0].teaserDurationMs),startMs:Number(K.cueRanges[0].startCardActiveMs),autoOpen:!!K.autoOpen,sessionData:{},sponsored:!1,Yv:{},Zi:null,Oo:p.trackingParams?
g.qe(p.trackingParams):null,wh:t&&t.trackingParams?g.qe(t.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,uZ:null,title:"",customMessage:"",url:null,onClickCommand:p.onTapCommand||null,Cx:B};Kk(z,K)}else{var v;if((v=K.content)==null?0:v.simpleCardContentRenderer){if(!K.cueRanges.length)return;B=(p=K.content)==null?void 0:p.simpleCardContentRenderer;p=K.teaser.simpleCardTeaserRenderer;t=K.icon?K.icon.infoCardIconRenderer:null;K={id:f,timestamp:z.W,type:"simple",teaserText:g.Lc(p.message),
teaserDurationMs:Number(K.cueRanges[0].teaserDurationMs),startMs:Number(K.cueRanges[0].startCardActiveMs),autoOpen:!!K.autoOpen,sessionData:$1(z,f,K,B),sponsored:!1,Yv:CT(B,p,B.command),Zi:B.trackingParams?g.qe(B.trackingParams):null,Oo:p.trackingParams?g.qe(p.trackingParams):null,wh:t&&t.trackingParams?g.qe(t.trackingParams):null,imageUrl:zK(B.image.thumbnails,290,290).url,displayDomain:B.displayDomain?g.Lc(B.displayDomain):null,showLinkIcon:!!B.showLinkIcon,uZ:null,title:B.title?g.Lc(B.title):"",
customMessage:B.callToAction?g.Lc(B.callToAction):"",url:g.A(B.command,g.Fc).url?xA({pause_on_navigation:!z.context.videoData.isLivePlayback,target:"new",value:g.A(B.command,g.Fc).url}):null,onClickCommand:null};Kk(z,K)}else{var I;if((I=K.content)==null?0:I.collaboratorInfoCardContentRenderer){if(!K.cueRanges.length)return;B=(t=K.content)==null?void 0:t.collaboratorInfoCardContentRenderer;p=K.teaser.simpleCardTeaserRenderer;t=K.icon?K.icon.infoCardIconRenderer:null;K={id:f,timestamp:z.W,type:"collaborator",
teaserText:g.Lc(p.message),teaserDurationMs:Number(K.cueRanges[0].teaserDurationMs),startMs:Number(K.cueRanges[0].startCardActiveMs),autoOpen:!!K.autoOpen,sessionData:$1(z,f,K,B),sponsored:!1,Yv:CT(B,p,B.endpoint),Zi:B.trackingParams?g.qe(B.trackingParams):null,Oo:p.trackingParams?g.qe(p.trackingParams):null,wh:t&&t.trackingParams?g.qe(t.trackingParams):null,channelId:g.A(B.endpoint,g.mU).browseId,customMessage:B.customText?g.Lc(B.customText):null,profileImageUrl:zK(B.channelAvatar.thumbnails,290,
290).url,title:B.channelName?g.Lc(B.channelName):"",metaInfo:[B.subscriberCountText?g.Lc(B.subscriberCountText):""],url:xA({pause_on_navigation:!z.context.videoData.isLivePlayback,target:"new",value:g.A(B.endpoint,g.mU).canonicalBaseUrl?g.A(B.endpoint,g.mU).canonicalBaseUrl:"/channel/"+g.A(B.endpoint,g.mU).browseId}),onClickCommand:null};Kk(z,K)}else{var G;if((G=K.content)==null?0:G.playlistInfoCardContentRenderer){if(!K.cueRanges.length)return;var b;B=(b=K.content)==null?void 0:b.playlistInfoCardContentRenderer;
p=K.teaser.simpleCardTeaserRenderer;t=K.icon?K.icon.infoCardIconRenderer:null;K={id:f,timestamp:z.W,type:"playlist",teaserText:g.Lc(p.message),teaserDurationMs:Number(K.cueRanges[0].teaserDurationMs),startMs:Number(K.cueRanges[0].startCardActiveMs),autoOpen:!!K.autoOpen,sessionData:$1(z,f,K,B),sponsored:!1,Yv:CT(B,p,B.action),Zi:B.trackingParams?g.qe(B.trackingParams):null,Oo:p.trackingParams?g.qe(p.trackingParams):null,wh:t&&t.trackingParams?g.qe(t.trackingParams):null,G3:zK(B.playlistThumbnail.thumbnails,
258,290).url,customMessage:B.customMessage?g.Lc(B.customMessage):null,playlistVideoCount:g.Lc(B.playlistVideoCount),title:B.playlistTitle?g.Lc(B.playlistTitle):"",metaInfo:[B.channelName?g.Lc(B.channelName):"",B.videoCountText?g.Lc(B.videoCountText):""],url:xA({pause_on_navigation:!z.context.videoData.isLivePlayback,target:"new",value:vg9(B.action)}),onClickCommand:null};Kk(z,K)}else{var e;if((e=K.content)==null?0:e.videoInfoCardContentRenderer){if(!K.cueRanges.length)return;var w;B=(w=K.content)==
null?void 0:w.videoInfoCardContentRenderer;p=K.teaser.simpleCardTeaserRenderer;t=K.icon?K.icon.infoCardIconRenderer:null;K={id:f,timestamp:z.W,type:"video",teaserText:g.Lc(p.message),teaserDurationMs:Number(K.cueRanges[0].teaserDurationMs),startMs:Number(K.cueRanges[0].startCardActiveMs),autoOpen:!!K.autoOpen,sessionData:$1(z,f,K,B),sponsored:!1,Yv:CT(B,p,B.action),Zi:B.trackingParams?g.qe(B.trackingParams):null,Oo:p.trackingParams?g.qe(p.trackingParams):null,wh:t&&t.trackingParams?g.qe(t.trackingParams):
null,G3:zK(B.videoThumbnail.thumbnails,258,290).url,videoDuration:B.lengthString?g.Lc(B.lengthString):null,customMessage:B.customMessage?g.Lc(B.customMessage):null,title:B.videoTitle?g.Lc(B.videoTitle):"",metaInfo:[B.channelName?g.Lc(B.channelName):"",B.viewCountText?g.Lc(B.viewCountText):""],isLiveNow:!!B.badge,url:xA({pause_on_navigation:!z.context.videoData.isLivePlayback,target:"new",value:vg9(B.action)}),onClickCommand:null};Kk(z,K)}}}}}z.W++},zK=function(z,K,f){for(var M=-1,p=-1,t=0;t<z.length;t++){if(z[t].height===
K||z[t].width===f)return z[t];
((z[t].height||0)<K||(z[t].width||0)<f)&&(M<0||(z[M].height||0)<(z[t].height||0)||(z[M].width||0)<(z[t].width||0))?M=t:((z[t].height||0)>=K||(z[t].width||0)>=f)&&(p<0||(z[p].height||0)>(z[t].height||0)||(z[p].width||0)>(z[t].width||0))&&(p=t)}return z[p>=0?p:M]},$1=function(z,K,f,M){return{feature:f.feature?f.feature:"cards",
src_vid:z.context.videoData.videoId,annotation_id:K,ei:z.context.videoData.eventId||"",itct:M.trackingParams||""}},w7Z=function(z,K){if(K=er4(z,K))K===z.S&&(z.S=null),z.U.removeCueRange(K.Df.id),g.ps(K.Gj),g.R8(z.cards,K),z.o0(),fk(z)},Ty=function(z,K,f){if(!z.T){z.VE.show();
z.Xc=new g.Kl(function(){g.ey(z.context.U.getRootNode(),g.$6.IV_DRAWER_OPEN)},0);
z.Xc.start();z.Px.X(z.Y,"mousewheel",function(B){z.Hx.start();B.preventDefault();B=B||window.event;var v=0;B.type=="MozMousePixelScroll"?v=0==(B.axis==B.HORIZONTAL_AXIS)?B.detail:0:window.opera?v=B.detail:v=B.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?B.wheelDeltaY/-30:B.wheelDeltaY/-1.2:B.wheelDelta/-1.6:B.wheelDeltaY/-3;if(B=v)z.Y.scrollTop+=B});
z.T=!0;var M=g.Vz();M&&z.eV&&z.G&&g.IT(M,[z.eV,z.G]);K={TRIGGER_TYPE:K};for(var p=g.a(z.cards),t=p.next();!t.done;t=p.next())t=t.value,t.jW||(t.jW=!0,DQ7(z.context.logger,t.Df.Yv.cZ,K)),M&&g.IT(M,[t.Df.Zi]);QP(z.U);f&&(z.C=new g.Kl(function(){z.Bx=z.D;z.SE.focus()},330),z.C.start())}},UO=function(z){z.T&&(z.VE.hide(),g.g0(z.Px),g.Dz(z.context.U.getRootNode(),g.$6.IV_DRAWER_OPEN),z.T=!1,QP(z.U),z.C&&z.C.stop(),z.C=new g.Kl(function(){z.Bx&&(z.Bx.focus(),z.Bx=null)},330),z.C.start())},yG8=function(z){g.wy(z.H1(),
[g.$6.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.dq(z.U,z.J,5);z.ON();z.D=g.rT("ytp-cards-button",z.U.getRootNode());z.SE=g.rT("iv-drawer-close-button",z.J);z.isInitialized=!0},kgH=function(z){z.Y1.push(g.IP("iv-teaser-shown",z.qY,z));
z.Y1.push(g.IP("iv-teaser-hidden",z.YfL,z));z.Y1.push(g.IP("iv-teaser-clicked",z.Ti,z));z.nI=!0},hrf=function(z,K){var f;
return K.onClickCommand&&((f=g.A(K.onClickCommand,g.oo_))==null?void 0:f.targetId)==="engagement-panel-error-corrections"?(z.l_=K,!0):!1},aeT=function(z,K){z.l_=K;
var f=z.U.getVideoData();if(!f)return!1;f=g.na(f);if(f==null?0:f.markersMap)for(var M,p=0;((M=f)==null?void 0:M.markersMap.length)>p;p++){var t=void 0,B=(t=f)==null?void 0:t.markersMap[p];if(B.key==="ERROR_CORRECTION_MARKERS"&&(t=void 0,(B=(t=B.value)==null?void 0:t.markers)&&B.length>0))return M=void 0,K.startMs=((M=g.A(B[0],g.iT8))==null?void 0:M.timeRangeStartMillis)||0,z.l_=null,!0}return!1},Kk=function(z,K){if(!hrf(z,K)||aeT(z,K)){var f=Rr2(z,K);
if(f){var M={Df:K,Gj:f.element,jW:!1};if(K.onClickCommand)z.U.B("web_infocards_teaser_show_logging_fix")&&(z.nI||kgH(z),w7Z(z,K.id),f=z.findLastIndex(M),g.q5(z.cards,f,0,M));else{z.isInitialized||yG8(z);w7Z(z,K.id);var p=z.findLastIndex(M);g.q5(z.cards,p,0,M);f.hL(z.Y,p);z.o0()}K.autoOpen?z.addCueRange(K.startMs,0x8000000000000,K.id,function(){z.T||(z.S=M,fk(z),Sc1(z,M),Ty(z,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(f=z.context.U.getCurrentTime()*1E3,f<5E3&&f>K.startMs&&upf(z,M),z.addCueRange(K.startMs,
K.startMs+1,K.id,function(){upf(z,M)}),fk(z))}}},Rr2=function(z,K){switch(K.type){case "simple":z=z.nH;
var f=K.displayDomain?{j:"div",K:"iv-card-image-text",qc:K.displayDomain}:void 0;var M=p7f(K);f={j:"div",Wx:["iv-card"],L:[{j:"a",K:"iv-click-target",V:{href:K.url?XK(K.url)||"":""},L:[OO(K.imageUrl,f),{j:"div",K:"iv-card-content",L:[FK("h2",void 0,K.title),M]}]}]};f=new g.F(f);rC(z,g.F3("iv-click-target",f.element),K,K.url);K=f;break;case "collaborator":z=z.nH;f={j:"div",Wx:["iv-card","iv-card-channel"],L:[{j:"a",Wx:["iv-click-target"],V:{href:XK(K.url)||"","data-ytid":K.channelId},L:[OO(K.profileImageUrl),
{j:"div",K:"iv-card-content",L:[feH(K),{j:"h2",K:"iv-card-primary-link",qc:K.title},M2p(K)]}]}]};f=new g.F(f);rC(z,g.F3("iv-click-target",f.element),K,K.url);K=f;break;case "playlist":z=z.nH;f={j:"div",Wx:["iv-card","iv-card-playlist"],L:[{j:"a",K:"iv-click-target",V:{href:XK(K.url)||""},L:[OO(K.G3,{j:"div",K:"iv-card-image-overlay",L:[{j:"span",K:"iv-card-playlist-video-count",qc:K.playlistVideoCount}]}),{j:"div",K:"iv-card-content",L:[feH(K),FK("h2","iv-card-primary-link",K.title),M2p(K)]}]}]};
f=new g.F(f);rC(z,g.F3("iv-click-target",f.element),K,K.url);K=f;break;case "productListing":z=z.nH;var p=K.offers.length!=0;f=["iv-card"];M="";var t=p7f(K);p&&(f.push("iv-card-product-listing"),M="iv-card-primary-link",t=K.offers[0],p=[],t.price&&p.push({j:"div",K:"iv-card-offer-price",qc:t.price}),t.merchant&&p.push({j:"div",K:"iv-card-offer-merchant",qc:t.merchant}),t={j:"div",L:p});p=K.url?XK(K.url)||"":"";f={j:"div",Wx:f,V:{tabindex:"0"},L:[{j:"a",Wx:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
K.imageUrl+");",href:p,"aria-hidden":"true",tabindex:"-1"}},{j:"div",K:"iv-card-content",L:[K.sponsored?{j:"div",K:"iv-card-sponsored",L:["Lien commercial",{j:"div",K:"iv-ad-info-container",L:[{j:"div",K:"iv-ad-info",qc:"{{adInfo}}"},{j:"div",K:"iv-ad-info-icon-container",L:[{j:"div",K:"iv-ad-info-icon"},{j:"div",K:"iv-ad-info-callout"}]}]}]}:"",{j:"a",K:"iv-click-target",V:{href:p},L:[FK("h2",M,K.title),t]}]}]};f=new g.F(f);M=g.zi("span");g.B6(M,"Vous voyez ce produit, car nous pensons qu'il est pertinent pour la vid\u00e9o. Il se peut que le marchand r\u00e9mun\u00e8re Google.");
f.s0(M,"adInfo");rC(z,g.F3("iv-click-target",f.element),K,K.url);K=f;break;case "video":z=z.nH;M=K.videoDuration?{j:"span",K:"iv-card-video-duration",qc:K.videoDuration}:void 0;t=K.isLiveNow?{j:"span",Wx:["yt-badge","yt-badge-live"],qc:"EN DIRECT MAINTENANT"}:null;p={j:"div",Wx:["iv-card","iv-card-video"],L:[{j:"a",K:"iv-click-target",V:{href:((f=K.url)==null?void 0:XK(f))||""},L:[OO(K.G3,M),{j:"div",K:"iv-card-content",L:[feH(K),FK("h2","iv-card-primary-link",K.title),M2p(K),t]}]}]};f=new g.F(p);
rC(z,g.F3("iv-click-target",f.element),K,K.url);K=f;break;default:return null}return K},Lu4=function(z){if(z.S)return z.S.Df.type==="productListing";
if(z.U.B("enable_wn_infocards")){var K;return!((K=z.cards)==null||!K.length)&&g.zd(z.cards,function(f){return f.Df.type==="productListing"})}return g.zd(z.cards,function(f){return f.Df.type==="productListing"})},fk=function(z){g.k4(z.U.getRootNode(),"ytp-cards-shopping-active",Lu4(z))},upf=function(z,K){if(!g.bx(z.U.getRootNode(),"ytp-cards-teaser-shown")){if(z.S!==K){var f=g.Vz(),M=z.S?z.S.Df.wh:z.wh;
f&&M&&g.GU(f,[M]);z.S=K;fk(z)}(f=z.isInitialized&&z.H1().style.display=="none")||(f=z.context.U.getPlayerState(),M=f===0&&z.context.U.getCurrentTime()===0,f=!(f===1||f===3||M));if(!f&&K.Df.teaserDurationMs){var p;f={teaserText:K.Df.teaserText,durationMs:K.Df.teaserDurationMs,onClickCommand:K.Df.onClickCommand,Cx:(p=K.Df.Cx)!=null?p:null};z.U.Ga(!0,f)}z.rE.isActive()||((!z.T||!z.Hx.isActive()&&z.vx)&&Sc1(z,K),z.rE.start(910+K.Df.teaserDurationMs))}},Sc1=function(z,K){z.N.l8?(K=new nT([0,
z.Y.scrollTop],[0,K.Gj.offsetTop],600,mWQ),z.context.T.listen(K,"animate",function(f){z.Y.scrollTop=f.y}),z.context.T.listen(K,"finish",function(f){z.Y.scrollTop=f.y}),K.play()):(z.N.s3(!0),z.Y.scrollTop=K.Gj.offsetTop,z.N.s3(!1))},MO=function(z){return z.S&&z.S.Df?z.S.Df:z.cards[0]&&z.cards[0].Df?z.cards[0].Df:null},er4=function(z,K){return g.yQ(z.cards,function(f){return f.Df.id===K})},pk=function(z,K,f){ZC.call(this,z,K);
this.annotation=f;this.isActive=!1},EgH=function(z){var K=z.annotation.data;
"start_ms"in K&&"end_ms"in K&&z.addCueRange(Number(K.start_ms),Number(K.end_ms),z.annotation.id,function(){z.show()},function(){z.hide()})},t9=function(z,K,f){pk.call(this,z,K,f);
this.Y=null;this.G=!1;this.T=null;this.J=!1;this.S=this.W=this.C=null},PFT=function(z,K){var f=f===void 0?0:f;
var M=RY9(K).width;g.ns(K,M);f=new Qjo(K,[M,K.offsetTop],[M-M-f,K.offsetTop],200,qH4);g.d(z,f);z.context.T.listen(f,"begin",function(){g.c6(K,!0)});
f.play()},qcS=function(z,K){if(K.channel_name){var f=z.createElement({j:"div",
Wx:["iv-branding-context-name"],qc:K.channel_name}),M=z.createElement({j:"div",Wx:["iv-branding-context-subscribe"]}),p=K.standalone_subscribe_button_data;p&&(z.S=new g.Ky(p.subscribeText,p.subscribeCount,p.unsubscribeText,p.unsubscribeCount,!!p.enabled,!!p.classic,K.channel_id,!!p.subscribed,p.feature,K.session_data.itct,z.context.U,!1),z.S.hL(M));var t=z.createElement({j:"div",Wx:["iv-branding-context-subscribe-caret"]}),B=z.createElement({j:"div",Wx:["branding-context-container-inner"]});B.appendChild(t);
B.appendChild(f);B.appendChild(M);g.c6(B,!1);var v=z.createElement({j:"div",Wx:["branding-context-container-outer"]});v.appendChild(B);g.H6(v,"right",K.image_width+"px");g.$0(z.H1(),v);z.T=new g.Kl(function(){HPH(z,B,v)},500);
g.d(z,z.T);z.context.S.listen(z.H1(),"mouseover",function(){QrT(z,B,v,t,K.image_height)});
z.context.S.listen(z.H1(),"mouseout",function(){z.T.start()})}},QrT=function(z,K,f,M,p){z.T.stop();
if(!z.J){var t=g.dW(K);z.S||(K.style.width=g.Ve(t.width,!0),f.style.width=g.Ve(t.width,!0));g.H6(M,"top",t.height-Math.max(Math.min(t.height,p)/2+10,20)+"px");g.H6(M,"right","1px");z.J=!0;g.c6(K,!0);z.C=new g.Kl(function(){g.ey(this.H1(),"iv-branding-active")},0,z);
z.C.start()}},HPH=function(z,K,f){g.Dz(z.H1(),"iv-branding-active");
z.W=new g.Kl(function(){g.c6(K,!1);z.S||(f.style.width=g.Ve(0,!0))},250);
z.W.start();z.J=!1},mQp=function(z,K,f,M,p,t,B){this.S=z;
this.T=K;this.SV=f;this.videoData=M;this.logger=p;this.U=t;this.Y=B},lep=function(z,K,f){pk.call(this,z,K,f);
var M=this;this.D=this.isCollapsed=this.N=!1;this.W=5E3;this.Y=this.T=this.S=this.J=null;this.G=this.createElement({j:"div",Wx:["iv-promo-contents"]});this.C=new g.Kl(function(){M.S.setAttribute("aria-hidden","true");g.c6(M.T,!1);g.c6(M.Y,!0)},700,this);
g.d(this,this.C)},ngT=function(z){var K=z.annotation.data;
if(z.annotation.style==="cta")var f=6;else if(z.annotation.style==="video"||z.annotation.style==="playlist")f=7;z.W=K.collapsedelay_ms||z.W;var M=["iv-promo","iv-promo-inactive"];z.H1().setAttribute("aria-hidden","true");z.H1().setAttribute("aria-label","Promotion");z.H1().tabIndex=0;var p=z.annotation.Ic(),t=K.image_url;if(t){var B=z.createElement({j:"div",Wx:["iv-promo-img","iv-click-target"]});t=z.createElement({j:"img",V:{src:t,"aria-hidden":"true"}});B.appendChild(t);K.video_duration&&!K.is_live?
(t=z.createElement({j:"span",K:"iv-promo-video-duration",qc:K.video_duration}),B.appendChild(t)):K.playlist_length&&(t=z.createElement({j:"span",K:"iv-promo-playlist-length",qc:K.playlist_length.toString()}),B.appendChild(t));p&&oX(z,B,p,z.annotation.id,K.session_data,void 0,f)}p?(t=z.createElement({j:"a",K:"iv-promo-txt"}),g.CL(t,XK(p)),z.S=t):z.S=z.createElement({j:"div",K:"iv-promo-txt"});switch(z.annotation.style){case "cta":case "website":var v=z.createElement({j:"p",L:[{j:"strong",qc:K.text_line_1}]});
var I=z.createElement({j:"p",L:[{j:"span",K:"iv-promo-link",qc:K.text_line_2}]});if(t=K.text_line_3){M.push("iv-promo-website-card-cta-redesign");var G=z.createElement({j:"button",Wx:["iv-promo-round-expand-icon","ytp-button"]});t=z.createElement({j:"button",Wx:["iv-button","iv-promo-button"],L:[{j:"span",K:"iv-button-content",qc:t}]});var b=z.createElement({j:"div",K:"iv-promo-button-container"});b.appendChild(t);p&&oX(z,z.H1(),p,z.annotation.id,K.session_data,void 0,f)}g.ey(z.S,"iv-click-target");
p&&oX(z,z.S,p,z.annotation.id,K.session_data,void 0,f);break;case "playlist":case "video":v=z.createElement({j:"p",L:[{j:"span",qc:K.text_line_1}]}),I=z.createElement({j:"p",L:[{j:"strong",qc:K.text_line_2}]}),K.is_live&&(v=I,I=z.createElement({j:"span",Wx:["yt-badge","iv-promo-badge-live"],qc:"EN DIRECT MAINTENANT"})),g.ey(z.S,"iv-click-target"),p&&oX(z,z.S,p,z.annotation.id,K.session_data,void 0,f),M.push("iv-promo-video")}v&&z.S.appendChild(v);I&&z.S.appendChild(I);z.G.appendChild(z.S);b&&z.G.appendChild(b);
f=z.createElement({j:"div",K:"iv-promo-actions"});z.Y=z.createElement({j:"button",Wx:["iv-promo-expand","ytp-button"]});z.Y.title="Agrandir";z.context.S.listen(z.Y,"click",function(e){V2_(z,5E3,e)});
f.appendChild(z.Y);g.c6(z.Y,!1);z.context.S.listen(z.H1(),"mouseover",z.Vo,z);z.context.S.listen(z.H1(),"mouseout",z.Qo,z);z.context.S.listen(z.H1(),"touchend",function(e){V2_(z,5E3,e)});
z.T=z.createElement({j:"button",Wx:["iv-promo-close","ytp-button"]});z.T.title="Fermer";z.context.S.listen(z.T,"click",z.annotation.style==="cta"&&K.text_line_3?z.gM:z.uL,z);f.appendChild(z.T);g.wy(z.H1(),M);B&&(g.$0(z.H1(),B),G&&B.appendChild(G));g.$0(z.H1(),z.G);g.$0(z.H1(),f)},V2_=function(z,K,f){f.stopPropagation();
Wuo(z);JG_(z,K);z.S.focus()},gg4=function(z){z.isCollapsed||z.D||z.J||(g.ey(z.H1(),"iv-promo-collapsed"),z.isCollapsed=!0,z.C.start())},Wuo=function(z){z.C.stop();
z.isCollapsed&&(g.yf(z.H1(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),z.isCollapsed=!1,z.S&&z.S.removeAttribute("aria-hidden"),g.c6(z.Y,!1),g.c6(z.T,!0))},JG_=function(z,K){z.J||(z.J=g.Xu(function(){iPp(this);
gg4(this)},K,z))},iPp=function(z){z.J&&(g.ZT.clearTimeout(z.J),z.J=null)},dQo=function(z){this.U=z},DQ7=function(z,K,f){K&&(f?Bh(z,K.map(function(M){return g.Jy(M,f)})):Bh(z,K))},Bh=function(z,K,f,M){var p=1,t=void 0,B=-1;
if(f){var v=!1;t=function(){p--;p||v||(clearTimeout(B),v=!0,f())};
B=setTimeout(function(){v=!0;f()},1E3)}K=g.a(K||[]);
for(var I=K.next();!I.done;I=K.next())I=I.value,p++,g.F$(I,t);M&&(p++,M!==0&&z.U.sendVideoStatsEngageEvent(M,t))},cG7=function(z){g.R5.call(this,z);
var K=this;this.Y1=this.D=!1;this.loadNumber=0;this.W={};this.logger=new dQo(this.player);this.J=new g.xI(this);this.C=this.G=null;this.events=new g.xI(this);this.T8=this.N=this.S=null;this.l_=[];g.d(this,this.J);this.J.X(this.player,"onVideoAreaChange",function(){K.publish("onVideoAreaChange")});
this.J.X(this.player,"onHideControls",function(){K.publish("onHideControls")});
this.J.X(this.player,"onShowControls",function(){K.publish("onShowControls")});
this.J.X(this.player,"resize",function(M){K.publish("resize",M)});
this.J.X(this.player,"presentingplayerstatechange",function(M){K.publish("presentingplayerstatechange",M)});
this.subscribe("presentingplayerstatechange",this.JX,this);this.subscribe("resize",this.YV,this);this.player.Z().vx.subscribe("vast_info_card_add",this.iN,this);g.d(this,this.events);this.nH=this.createElement({j:"div",K:"video-custom-annotations"});this.Y=new g.F({j:"div",Wx:["ytp-player-content","ytp-iv-player-content"]});g.d(this,this.Y);g.dq(this.player,this.Y.element,4);this.Y.hide();this.T=new g.F({j:"div",Wx:["ytp-iv-video-content"]});g.d(this,this.T);z=this.createElement({j:"div",K:"video-annotations"});
z.appendChild(this.nH);this.T.element.appendChild(z);this.F7()&&this.load();var f=this.createElement({j:"style"});(g.x7("HEAD")[0]||document.body).appendChild(f);this.addOnDisposeCallback(function(){g.ps(f)});
if(z=f.sheet)z.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),z.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),z.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),z.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),z.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),z.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),z.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),z.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),z.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),z.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},srf=function(z){z=z.createElement({j:"div",
Wx:["annotation","annotation-type-custom"]});g.c6(z,!1);return z},AGT=function(z,K){K=!K.isCued()&&!g.Z(K,1024);
z.Y.s3(K);z.T.s3(K)},jrf=function(z,K,f){z.D=!0;
z.C=g.V4(K,f)},Yc4=function(z,K){for(var f={},M=g.a(K.attributes),p=M.next();!p.done;p=M.next())p=p.value,f[p.name]=p.nodeValue;
for(M=0;M<K.childNodes.length;M++)if(p=K.childNodes[M],g.$f(p)&&p.nodeType==1){if(f[p.tagName])var t=f[p.tagName];else if(p.tagName==="data"){p.childNodes.length>0&&(t=p.childNodes[0].nodeValue,f[p.tagName]=typeof t==="string"?t.trim():t);continue}else t=[],f[p.tagName]=t;p&&p.tagName==="TEXT"?p.childNodes.length===1&&p.childNodes[0].nodeType===3?t.push(p.childNodes[0].nodeValue):t.push(""):p&&t.push(Yc4(z,p))}return f},OPf=function(z){var K=z.player.getVideoData();
if(K.Px){var f=z.player.Z().vx.get(K.videoId);if(f){var M={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(p,t,B){p=z.loadNumber;t=K.videoId;z.loaded&&z.loadNumber===p&&z.player.getVideoData().videoId===t&&(B=g.Rw(B)&&B.responseXML?B.responseXML:null)&&X7p(z,B)}};
g.BJ()&&(M.onFinish=xQ9(z,M.onFinish));M.postParams={ic_only:"1"};Fu7(M,f);z.D=!0;g.V4(K.Px,M)}}},Fu7=function(z,K){z.method="POST";
z.postParams=z.postParams||{};K.Tp&&(z.postParams.ic_coll=K.Tp);K.PS&&(z.postParams.ic_xml=K.PS);K.gQ&&(z.postParams.ic_track=K.gQ)},rGf=function(z){var K=new g.F({j:"div"});
g.c6(K.element,!1);var f=new Ie9(z.player,K.element,NO(z));g.d(f,K);K.hL(z.Y.element);f.E5();return f},ogf=function(z,K){var f,M;
if(K=(f=K.getWatchNextResponse())==null?void 0:(M=f.cards)==null?void 0:M.cardCollectionRenderer)z.Y1=!0,ZPQ(z,K),K.headerText&&z.T8&&(f=g.Lc(K.headerText),z.T8.setAttribute("title",f))},NO=function(z){if(!z.N){var K=new ljT(z);
g.d(z,K);var f=new g.u2(z);g.d(z,f);z.N=new mQp(K,f,z.player.Z(),z.player.getVideoData(),z.logger,z.player,z.Jo)}return z.N},X7p=function(z,K){var f=!1,M=K.getElementsByTagName("annotations");
if(M&&!(M.length<1)&&(M=M[0].getAttribute("itct"))){var p=g.Vz();if(p){var t=g.lc();t&&g.Mu(g.Um)(void 0,p,t,[g.qe(M)])}}K=K.getElementsByTagName("annotation");for(M=0;M<K.length;M++){t=Yc4(z,K[M]);p=null;try{if(t){var B=t.id,v=/.+/;var I=typeof B==="string"&&v!=null&&B!=null&&B.match(v)?B:"";var G=YA(t.type,CFo),b=YA(t.style,Tj8),e=OC7(t.data),w=e.length!==0?JSON.parse(e):{};var D=t.action;t=UWT;if(D==null)var y=null;else if(g.K1(D)){v=[];for(var R=g.a(D),S=R.next();!S.done;S=R.next()){var E=t(S.value);
E&&v.push(E)}y=v}else{var L=t(D);y=L?[L]:[]}p=I&&G?new zrT(I,G,b,y,w):null}else p=null}catch(T){}if(p)if(p.type==="branding"||p.type==="promotion"){t=z;v=p;var q=srf(t),V=null;switch(v.type){case "branding":if(t.player.Z().SU)break;t.Y.element.appendChild(q);V=new t9(q,NO(t),v);break;case "promotion":g.dq(t.player,q,4),V=new lep(q,NO(t),v)}V&&V.E5();if(t=V)g.d(z,t),z.W[p.id]=t}else if(p.type==="card"||p.type==="drawer"){z.S||(z.S=rGf(z),g.d(z,z.S));if(p.type==="card"){q=z.S;var c=(f=p)&&f.data&&f.data.card_type;
p=f.data;if(c)switch(t=p.tracking||{},t={cZ:t.impression,click:t.click,close:t.close,UK:t.teaser_impression,DJ:t.teaser_click},v=p.tracking_params||{},V=null,c){case "collaborator":f={id:f.id,timestamp:p.timestamp||0,type:p.card_type,teaserText:p.teaser_text,teaserDurationMs:p.teaser_duration_ms,startMs:p.start_ms,autoOpen:p.auto_open||!1,sessionData:p.session_data||{},sponsored:p.sponsored||!1,Yv:t,Zi:v.card?g.qe(v.card):null,Oo:v.teaser?g.qe(v.teaser):null,wh:v.icon?g.qe(v.icon):null,channelId:p.channel_id,
customMessage:p.custom_message?p.custom_message:null,profileImageUrl:p.image_url,title:p.title,metaInfo:p.meta_info,url:xA({pause_on_navigation:p.pause_on_navigation,target:p.target||"new",value:p.url}),onClickCommand:null};Kk(q,f);break;case "playlist":f={id:f.id,timestamp:p.timestamp||0,type:p.card_type,teaserText:p.teaser_text,teaserDurationMs:p.teaser_duration_ms,startMs:p.start_ms,autoOpen:p.auto_open||!1,sessionData:p.session_data||{},sponsored:p.sponsored||!1,Yv:t,Zi:v.card?g.qe(v.card):null,
Oo:v.teaser?g.qe(v.teaser):null,wh:v.icon?g.qe(v.icon):null,G3:p.image_url,playlistVideoCount:p.playlist_video_count,customMessage:p.custom_message?p.custom_message:null,title:p.title,metaInfo:p.meta_info,url:xA({pause_on_navigation:p.pause_on_navigation,target:p.target||"new",value:p.url}),onClickCommand:null};Kk(q,f);break;case "productListing":p.signin_url&&(V=xA({target:"current",value:p.signin_url}));c=[];for(var O=p.offers||[],x=0;x<O.length;x++)c.push(new t2T(g.hR(O[x].merchant),g.hR(O[x].price)));
f={id:f.id,timestamp:p.timestamp||0,type:p.card_type,teaserText:p.teaser_text,teaserDurationMs:p.teaser_duration_ms,startMs:p.start_ms,autoOpen:p.auto_open||!1,sessionData:p.session_data||{},sponsored:p.sponsored||!1,Yv:t,Zi:v.card?g.qe(v.card):null,Oo:v.teaser?g.qe(v.teaser):null,wh:v.icon?g.qe(v.icon):null,imageUrl:p.image_url,displayDomain:p.display_domain?p.display_domain:null,showLinkIcon:!!p.show_link_icon,uZ:p.button_icon_url?p.button_icon_url:null,title:p.title,customMessage:p.custom_message?
p.custom_message:null,url:xA({pause_on_navigation:p.pause_on_navigation,target:p.target||"new",value:p.url}),EaH:V,JVf:p.signin_title?p.signin_title:void 0,qcV:p.signin_message?p.signin_message:void 0,offers:c,onClickCommand:null};Kk(q,f);break;case "simple":f={id:f.id,timestamp:p.timestamp||0,type:p.card_type,teaserText:p.teaser_text,teaserDurationMs:p.teaser_duration_ms,startMs:p.start_ms,autoOpen:p.auto_open||!1,sessionData:p.session_data||{},sponsored:p.sponsored||!1,Yv:t,Zi:v.card?g.qe(v.card):
null,Oo:v.teaser?g.qe(v.teaser):null,wh:v.icon?g.qe(v.icon):null,imageUrl:p.image_url,displayDomain:p.display_domain?p.display_domain:null,showLinkIcon:!!p.show_link_icon,uZ:p.button_icon_url?p.button_icon_url:null,title:p.title,customMessage:p.custom_message?p.custom_message:null,url:xA({pause_on_navigation:p.pause_on_navigation,target:p.target||"new",value:p.url}),onClickCommand:null};Kk(q,f);break;case "video":f={id:f.id,timestamp:p.timestamp||0,type:p.card_type,teaserText:p.teaser_text,teaserDurationMs:p.teaser_duration_ms,
startMs:p.start_ms,autoOpen:p.auto_open||!1,sessionData:p.session_data||{},sponsored:p.sponsored||!1,Yv:t,Zi:v.card?g.qe(v.card):null,Oo:v.teaser?g.qe(v.teaser):null,wh:v.icon?g.qe(v.icon):null,G3:p.image_url,videoDuration:p.video_duration||null,customMessage:p.custom_message?p.custom_message:null,title:p.title,metaInfo:p.meta_info,isLiveNow:!!p.is_live_now,url:xA({pause_on_navigation:p.pause_on_navigation,target:p.target||"new",value:p.url}),onClickCommand:null},Kk(q,f)}}else Gg7(z.S,p);f=!0}}f&&
(QP(z.player),z.YV())},ZPQ=function(z,K){var f=!1;
z.S||(z.S=rGf(z),g.d(z,z.S));for(var M=g.a(K.cards||[]),p=M.next();!p.done;p=M.next())p=p.value,p.cardRenderer&&(bPp(z.S,p.cardRenderer),f=!0);if(f){var t;(t=z.player.getVideoData())!=null&&g.iv(t)||(f=z.S,M=K.headerText?g.Lc(K.headerText):"",g.B6(f.TP,M),f.D&&f.D.setAttribute("title",M),f.context.videoData.eventId&&(f.eventId=f.context.videoData.eventId),f.eV=K.trackingParams?g.qe(K.trackingParams):null,f.G=K.closeButton.infoCardIconRenderer.trackingParams?g.qe(K.closeButton.infoCardIconRenderer.trackingParams):
null,f.wh=K.icon.infoCardIconRenderer.trackingParams?g.qe(K.icon.infoCardIconRenderer.trackingParams):null,z.YV());QP(z.player)}},UQ5=function(z,K,f,M,p){if(!z.player.Z().SU){var t=[];
K.navigationEndpoint&&g.A(K.navigationEndpoint,g.mU)&&g.A(K.navigationEndpoint,g.mU).browseId&&t.push(new oN5("openUrl","click",new r4f("/channel/"+g.A(K.navigationEndpoint,g.mU).browseId,"new",!0,!0)));var B=K.watermark.thumbnails[0];M={channel_name:K.channelName,end_ms:K.endTimeMs,image_height:B.height,image_type:1,image_url:B.url,image_width:B.width,is_mobile:!1,session_data:{annotation_id:f,ei:p,feature:"iv",itct:K.trackingParams,src_vid:M},start_ms:K.startTimeMs};if(K.subscribeButton&&g.A(K.subscribeButton,
g.lv)){M.channel_id=g.A(K.subscribeButton,g.lv).channelId;var v;K=g.A(K.subscribeButton,g.lv);B=p=null;K.subscribed?(K.subscriberCountWithUnsubscribeText&&(p=g.Lc(K.subscriberCountWithUnsubscribeText)),K.subscriberCountText&&(B=g.Lc(K.subscriberCountText))):(K.subscriberCountText&&(p=g.Lc(K.subscriberCountText)),K.subscriberCountWithSubscribeText&&(B=g.Lc(K.subscriberCountWithSubscribeText)));var I,G=((I=g.A((v=K.signInEndpoint)==null?void 0:v.commandMetadata,g.SZ))==null?void 0:I.url)||"";v={subscribeText:g.Lc(K.unsubscribedButtonText),
subscribeCount:p||"",unsubscribeText:g.Lc(K.subscribedButtonText),unsubscribeCount:B||"",enabled:K.enabled||!1,classic:!1,subscribed:K.subscribed||!1,feature:"iv",signInUrl:G};M.standalone_subscribe_button_data=v}t=new zrT(f,"branding","branding",t,M);v=srf(z);z.Y.element.appendChild(v);t=new t9(v,NO(z),t);t.E5();g.d(t,t);z.W[f]=t}},xQ9=function(z,K){return function(){var f=g.i8.apply(0,arguments);
z.CH()||z.l_.push(g.rh.DD(function(){K.apply(null,g.P(f))}))}},zu_=function(z){return z==="annotation-editor"||z==="live-dashboard"};
g.m8.prototype.Ga=g.pW(45,function(z,K){var f=g.Ji(this.pI());f&&f.Ga(z,K)});
var m5={},lw=null;g.GH(nT,g.hU);g.k=nT.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(z){if(z||this.S==0)this.progress=0,this.coords=this.Y;else if(this.isPlaying())return!1;VP(this);this.startTime=z=g.N5();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.J=this.startTime;this.progress||this.Od();this.UP("play");this.isPaused()&&this.UP("resume");this.S=1;var K=g.M5(this);K in m5||(m5[K]=this);Ld_();EN_(this,z);return!0};
g.k.stop=function(z){VP(this);this.S=0;z&&(this.progress=1);Pg_(this,this.progress);this.onStop();this.ob()};
g.k.pause=function(){this.isPlaying()&&(VP(this),this.S=-1,this.UP("pause"))};
g.k.JL=function(){this.S==0||this.stop(!1);this.UP("destroy");nT.Y9.JL.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.pw=function(){this.UP("animate")};
g.k.UP=function(z){this.dispatchEvent(new HCf(z,this))};
g.GH(HCf,g.$Z);g.GH(Wn,nT);Wn.prototype.T=function(){};
Wn.prototype.pw=function(){this.T();Wn.Y9.pw.call(this)};
Wn.prototype.ob=function(){this.T();Wn.Y9.ob.call(this)};
Wn.prototype.Od=function(){this.T();Wn.Y9.Od.call(this)};
g.GH(Qjo,Wn);Qjo.prototype.T=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.h(ljT,g.J);g.k=ljT.prototype;g.k.listen=function(z,K,f,M){f=(0,g.p1)(f,M||this.Y);z=g.qm(z,K,f);this.S.push(z);return z};
g.k.Gf=function(z,K,f,M){f=(0,g.p1)(f,M||this.Y);z=SH5(z,K,f);this.S.push(z);return z};
g.k.W8=function(z){g.m6(z);g.R8(this.S,z)};
g.k.removeAll=function(){g.m6(this.S);this.S.length=0};
g.k.JL=function(){this.removeAll();g.J.prototype.JL.call(this)};g.h(Wd2,g.R5);g.k=Wd2.prototype;g.k.load=function(){g.R5.prototype.load.call(this);if(!iw(this)){var z=g.QdS(this.player.getVideoData());z?(z=nNf(z,J4Z(this)),dC(this,z,!1)):gNZ(this)}};
g.k.unload=function(){dC(this,null);this.J&&(this.J.abort(),this.J=null);g.R5.prototype.unload.call(this)};
g.k.Lo=function(z,K){return iw(this)?z==="loadCustomEndscreenRenderer"?(z=nNf(K,"new"),dC(this,z),!0):null:null};
g.k.getOptions=function(){return iw(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.NB=function(){if(this.endscreen&&this.endscreen.elements){var z=this.player.getVideoContentRect();if(z&&z.width!==0&&z.height!==0){var K=this.player.getPlayerSize();if(K&&K.width!==0&&K.height!==0){var f=z.width/z.height;var M=0;for(var p=-1,t=0;t<Kt_.length;t++){var B=Math.abs(K.width-Kt_[t]);if(p===-1||M>=B)p=t,M=B}M=$MH[p];this.T&&g.H6(this.T.element,"outline-width",Math.max(K.width,K.height)+"px");for(K=0;K<this.endscreen.elements.length;++K)if(t=this.endscreen.elements[K].id,p=this.Y[t],
B=this.W[t],p&&B){var v=B.width*f/B.aspectRatio,I=Math.round(B.width*z.width);t=Math.round(v*z.height);var G=z.left+Math.round(B.left*z.width),b=z.top+Math.round(B.top*z.height);g.ip(p.element,I,t);g.ns(p.element,G,b);g.yf(p.element,fi_);I>256||t>256?g.ey(p.element,"ytp-ce-large-round"):I>96||t>96?g.ey(p.element,"ytp-ce-medium-round"):g.ey(p.element,"ytp-ce-small-round");g.yf(p.element,M55);I=B.left+B.width/2;B=B.top+v/2;g.ey(p.element,I<=.5&&B<=.5?"ytp-ce-top-left-quad":I>.5&&B<=.5?"ytp-ce-top-right-quad":
I<=.5&&B>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.yf(p.element,$MH);g.ey(p.element,M);(p=g.Os(document,"div","ytp-ce-expanding-overlay-body",p.element)[0])&&g.H6(p,"height",t+"px")}}}}};
g.k.onCueRangeEnter=function(z){if(this.endscreen)if(z.getId()==="ytp-ce-in-endscreen")jV(this,this.endscreen.impressionUrls),(z=g.Vz())&&this.endscreen.visualElement&&g.vW(z,this.endscreen.visualElement),this.S&&(g.ey(this.S,"ytp-ce-element-show"),this.S.removeAttribute("aria-hidden"),this.player.AU()?g.ey(this.S,"ytp-ce-hide-button-lower"):g.Dz(this.S,"ytp-ce-hide-button-lower"));else{z=z.getId().substring(15);var K=this.Y[z],f=this.W[z];g.ey(K.element,"ytp-ce-element-show");K.element.removeAttribute("aria-hidden");
K=this.player.getRootNode();g.ey(K,"ytp-ce-shown");jV(this,f.impressionUrls);(K=g.Vz())&&g.vW(K,f.visualElement);this.player.Z().D&&this.player.LH("endscreenelementshown",z)}};
g.k.onCueRangeExit=function(z){if(z.getId()==="ytp-ce-in-endscreen")this.S&&(g.Dz(this.S,"ytp-ce-element-show"),this.S.setAttribute("aria-hidden","true"));else{z=z.getId().substring(15);var K=this.Y[z];g.Dz(K.element,"ytp-ce-element-show");K.element.setAttribute("aria-hidden","true");K=this.player.getRootNode();g.Dz(K,"ytp-ce-shown");this.player.Z().D&&this.player.LH("endscreenelementhidden",z)}};
g.k.FPx=function(z){var K=this;z.target===window&&(new g.Kl(function(){for(var f=g.a(Object.values(K.Y)),M=f.next();!M.done;M=f.next())g.yf(M.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.s3=function(z){for(var K=g.a(Object.values(this.Y)),f=K.next();!f.done;f=K.next())f=f.value,z?f.element.setAttribute("hidden",""):f.element.removeAttribute("hidden")};
g.k.RTc=function(z){this.S&&this.player.getRootNode().removeChild(this.S);z&&(g.ey(z,"ytp-ce-hide-button-container"),this.S=z,g.dq(this.player,this.S,4))};
var Kt_=[346,426,470,506,570,640,853,1280,1920],$MH="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),M55=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],fi_=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var ZC9={aDV:"current",iJa:"new"};var Cg1={CLOSE:"close",ZJc:"openUrl",SUBSCRIBE:"subscribe"},Tk9={u2x:"click",CLOSE:"close",S8c:"hidden",Ix1:"rollOut",Cyx:"rollOver",ZYa:"shown"};zrT.prototype.Ic=function(){var z=KuQ(this,function(K){return K.type==="openUrl"&&K.url!=null});
return z?z.url:null};
var Tj8={boc:"anchored",VK:"branding",CHANNEL:"channel",yoH:"cta",lMV:"highlightText",b7c:"label",PLAYLIST:"playlist",POPUP:"popup",Lzc:"speech",SUBSCRIBE:"subscribe",lzh:"title",VIDEO:"video",Mma:"website"},CFo={VK:"branding",vx_:"card",pWd:"drawer",Y81:"highlight",Em_:"marker",T_a:"promotion",TEXT:"text",cd_:"widget"};g.h(ZC,g.J);g.k=ZC.prototype;g.k.addCueRange=function(z,K,f,M,p){z=new g.bS(z,K,{id:f,namespace:"annotations_module"});M&&this.QE.set(z,M);p&&this.b_.set(z,p);this.context.U.St([z],1)};
g.k.E5=function(){this.context.Y.subscribe("resize",this.o0,this)};
g.k.H1=function(){return this.element};
g.k.dJ=function(z,K,f,M,p,t){if(this.oa)return!1;t&&(t.stopPropagation(),t.preventDefault());this.navigate(z,f,M,p);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.ps(this.H1())};
g.k.o0=function(){};
g.k.navigate=function(z,K,f,M){var p=this,t=XK(z);if(t){var B=Nj1(t,z.target),v=function(){z.S&&p.context.U.pauseVideo();var I=p.context.videoData.f3||!1,G=g.Iw(t||"");I&&G&&(G.v||G.list)?p.context.U.by(G.v,K,G.list,!1):g.U$(t||"",B==="current"?"_top":void 0,K)};
B==="new"&&(v(),v=null);Bh(this.context.logger,f,v,M);BjS(t)||(f=g.Vz(),M=K.itct,f&&M&&g.bn(f,g.qe(M)))}};
g.k.JL=function(){this.QE.clear();this.b_.clear();g.J.prototype.JL.call(this)};
g.k.createElement=function(z){z=new g.F(z);g.d(this,z);return z.element};g.h(Ie9,ZC);g.k=Ie9.prototype;g.k.Up=function(){this.l_&&Kk(this,this.l_)};
g.k.isAvailable=function(){var z;if(z=!!this.cards.length)(z=this.U.getRootNode())?(z=g.dW(z),z=173<z.width&&173<z.height):z=!1;return z};
g.k.o0=function(){var z=this.isAvailable();g.c6(this.H1(),z);g.k4(this.context.U.getRootNode(),g.$6.IV_DRAWER_ENABLED,z);QP(this.U)};
g.k.destroy=function(){this.U.Ga(!1);try{this.U.getRootNode().removeChild(this.J)}catch(z){}g.GW(this.Y1);g.g0(this.Px);this.Xc&&this.Xc.dispose();this.C&&this.C.dispose();ZC.prototype.destroy.call(this)};
g.k.ON=function(){var z=this;this.context.S.listen(g.rT("iv-drawer-close-button",this.J),"click",this.Dm,this);this.context.S.listen(this.Y,"touchend",function(){z.Hx.start()});
this.context.S.listen(this.Y,"scroll",this.Jv,this);this.context.Y.subscribe("onHideControls",function(){z.vx=!0});
this.context.Y.subscribe("onShowControls",function(){z.vx=!1});
this.context.Y.subscribe("onVideoAreaChange",function(){z.vx=g.bx(z.U.getRootNode(),"ytp-autohide")});
this.Y1.push(g.IP("iv-button-shown",this.ALa,this));this.Y1.push(g.IP("iv-button-hidden",this.SfE,this));kgH(this)};
g.k.findLastIndex=function(z){if(this.cards.length===0)return 0;var K=g.kf(this.cards,function(f){return z.Df.startMs>f.Df.startMs||z.Df.startMs===f.Df.startMs&&z.Df.timestamp>=f.Df.timestamp?!0:!1});
return K===-1?0:K+1};
g.k.Dm=function(){if(this.T){Bh(this.context.logger,MO(this).Yv.close);var z=g.Vz();z&&this.G&&g.bn(z,this.G);UO(this)}};
g.k.Jv=function(){g.k4(this.J,"iv-drawer-scrolled",this.Y.scrollTop>0)};
g.k.ALa=function(){var z=g.Vz(),K=MO(this);K=K?K.wh:this.wh;z&&K&&g.IT(z,[K])};
g.k.SfE=function(){var z=g.Vz(),K=MO(this);K=K?K.wh:this.wh;z&&K&&g.GU(z,[K])};
g.k.qY=function(){var z=MO(this);Bh(this.context.logger,z.Yv.UK);var K=g.Vz();if(K&&z)if(this.U.B("web_infocards_teaser_show_logging_fix")){var f=[];z.Oo&&f.push(z.Oo);z.wh&&f.push(z.wh);f.length>0&&g.IT(K,f)}else g.IT(K,[z.Oo,z.wh])};
g.k.YfL=function(){var z=g.Vz(),K=MO(this);z&&K&&g.GU(z,[K.Oo])};
g.k.Ti=function(z){var K=MO(this),f=g.Vz();this.S?z?(z=this.context.logger,Bh(z,K.Yv.DJ),z.U.sendVideoStatsEngageEvent(4,void 0),f&&K.Oo&&g.bn(f,K.Oo)):(z=this.context.logger,Bh(z,K.Yv.DJ),z.U.sendVideoStatsEngageEvent(4,void 0),f&&K.wh&&g.bn(f,K.wh)):(z=this.context.logger,Bh(z,K.Yv.DJ),z.U.sendVideoStatsEngageEvent(4,void 0),f&&this.wh&&g.bn(f,this.wh))};g.h(pk,ZC);pk.prototype.E5=function(){ZC.prototype.E5.call(this);EgH(this)};
pk.prototype.show=function(){ZC.prototype.show.call(this);var z=g.Vz(),K=this.annotation.data;z&&K&&(K=K.session_data)&&g.IT(z,[g.qe(K.itct)])};
pk.prototype.hide=function(){ZC.prototype.hide.call(this);var z=g.Vz(),K=this.annotation.data;z&&K&&(K=K.session_data)&&g.GU(z,[g.qe(K.itct)])};g.h(t9,pk);
t9.prototype.show=function(){if(!this.isActive){pk.prototype.show.call(this);if(!this.G){g.ey(this.H1(),"iv-branding");var z=this.annotation.data;this.Y=this.createElement({j:"img",Wx:["branding-img","iv-click-target"],V:{"aria-label":"Filigrane de cha\u00eene",src:z.image_url,width:z.image_width,height:z.image_height}});g.c6(this.Y,!1);var K=this.createElement({j:"button",Wx:["branding-img-container","ytp-button"]});K.appendChild(this.Y);this.H1().appendChild(K);var f=this.annotation.Ic();f&&oX(this,
K,f,this.annotation.id,z.session_data);this.context.U.B("disable_branding_context")||qcS(this,z);this.G=!0}g.c6(this.H1(),!0);this.isActive=!0;if(this.Y){try{PFT(this,this.Y)}catch(M){}g.ey(this.context.U.getRootNode(),"ytp-branding-shown");this.context.U.getRootNode().style.setProperty("--branding-image-width",this.Y.getAttribute("width")+"px")}}};
t9.prototype.hide=function(){this.isActive&&(pk.prototype.hide.call(this),g.c6(this.H1(),!1),this.isActive=!1,g.Dz(this.context.U.getRootNode(),"ytp-branding-shown"))};
t9.prototype.destroy=function(){this.S&&(this.S.dispose(),this.S=null);g.Dz(this.context.U.getRootNode(),"ytp-branding-shown");pk.prototype.destroy.call(this)};g.h(lep,pk);g.k=lep.prototype;g.k.show=function(){this.isActive||(pk.prototype.show.call(this),this.N||(ngT(this),this.N=!0),g.c6(this.H1(),!0),g.Xu(function(){g.Dz(this.H1(),"iv-promo-inactive")},100,this),this.H1().removeAttribute("aria-hidden"),this.isActive=!0,iPp(this),Wuo(this),JG_(this,this.W))};
g.k.hide=function(){this.isActive&&(g.ey(this.H1(),"iv-promo-inactive"),this.isActive=!1,this.H1().setAttribute("aria-hidden","true"))};
g.k.dJ=function(z,K,f,M,p,t){return this.isCollapsed?!1:pk.prototype.dJ.call(this,z,K,f,M,p,t)};
g.k.Vo=function(z){this.D=!0;V2_(this,500,z)};
g.k.Qo=function(){this.D=!1;gg4(this)};
g.k.uL=function(z){z.stopPropagation();this.hide()};
g.k.gM=function(z){z.stopPropagation();iPp(this);this.isCollapsed=!0;g.ey(this.H1(),"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();pk.prototype.destroy.call(this)};g.h(cG7,g.R5);g.k=cG7.prototype;g.k.Lo=function(z,K){if(!zu_(this.player.Z().playerStyle))return null;switch(z){case "loadCustomAnnotationsXml":return(z=g.C7(K))&&X7p(this,z),!0;case "removeCustomAnnotationById":return K&&this.S&&(w7Z(this.S,K),QP(this.player)),!0}return null};
g.k.getOptions=function(){return zu_(this.player.Z().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.F7=function(){var z=this.player.Z(),K=this.player.getVideoData(),f=z.annotationsLoadPolicy||K.annotationsLoadPolicy;return g.zG(K)||this.player.isMutedByEmbedsMutedAutoplay()?!1:f===1&&!K.cT||z.vx.get(K.videoId)||g.dH(K)||g.cw(K)?!0:!1};
g.k.YV=function(){if(this.T){var z=this.player.wE().getVideoContentRect(!0);g.ip(this.T.element,z.width,z.height);g.ns(this.T.element,z.left,z.top)}if(this.S){var K=this.player.hD();z=this.S;K=K.width;g.k4(z.J,"iv-drawer-small",K<=426);g.k4(z.J,"iv-drawer-big",K>=1280)}};
g.k.JX=function(z){AGT(this,z.state);g.Z(z.state,2)&&(this.AU()&&this.Di()&&this.player.getPresentingPlayerType()!==2&&this.Ps(!1),this.Ga(!1))};
g.k.load=function(){function z(B){var v=K.loadNumber;K.C=null;K.loaded&&K.loadNumber===v&&K.player.getVideoData().videoId===M&&(B=g.Rw(B)&&B.responseXML?B.responseXML:null)&&(X7p(K,B),g.ey(K.player.getRootNode(),"iv-module-loaded"))}
var K=this;g.R5.prototype.load.call(this);AGT(this,this.player.getPlayerStateObject());this.loadNumber++;var f=this.player.getVideoData(),M=f.videoId;g.BJ()&&(z=xQ9(this,z));var p={format:"XML",onFinish:z,onError:function(){K.C=null},
urlParams:{}};f.isPharma&&(p.urlParams.pharma="1");p.method="POST";p.withCredentials=!0;var t=this.player.Z().vx.get(M);t&&Fu7(p,t);t=t&&(t.PS||t.Tp);if(!f.lY||t)f.Px?jrf(this,f.Px,p):(this.G=function(){if(!K.D)K.onVideoDataChange(p);var B=K.player.getVideoData();(B==null?0:g.iv(B))&&!K.Y1&&ogf(K,B)},this.player.addEventListener("videodatachange",this.G));
g.dq(this.player,this.T.element,4);this.YV();(t=g.dH(f))&&ZPQ(this,t);(t=g.cw(f))&&t.featuredChannel&&UQ5(this,t.featuredChannel,t.annotationId||"branding",f.videoId||null,f.eventId||null);this.T8=g.rT("ytp-cards-button",this.player.getRootNode());g.iv(f)&&ogf(this,f)};
g.k.onVideoDataChange=function(z){var K=this.player.getVideoData();K.Px&&jrf(this,K.Px,z)};
g.k.unload=function(){this.player.GE("annotations_module");for(var z=g.a(Object.keys(this.W)),K=z.next();!K.done;K=z.next())this.W[K.value].destroy();this.N=null;this.S&&(this.S.destroy(),this.S=null,QP(this.player));this.D=!1;this.C&&(this.C.abort(),this.C=null);this.Y1=!1;this.W={};this.Y.hide();g.R5.prototype.unload.call(this);this.T.detach();this.G&&(this.player.removeEventListener("videodatachange",this.G),this.G=null)};
g.k.iN=function(z){z===this.player.getVideoData().videoId&&(this.loaded?OPf(this):this.load())};
g.k.AU=function(){var z;return((z=this.S)==null?void 0:z.isAvailable())||this.Y1};
g.k.Di=function(){return!!this.S&&this.S.T};
g.k.Ps=function(z,K,f){K=K===void 0?!1:K;this.AU();this.S&&(z?f?Ty(this.S,f,K):Ty(this.S,"YOUTUBE_DRAWER_AUTO_OPEN",K):UO(this.S))};
g.k.Ga=function(z,K){this.player.publish(z?"cardsteasershow":"cardsteaserhide",K)};
g.k.JL=function(){this.player.Z().vx.unsubscribe("vast_info_card_add",this.iN,this);g.Dz(this.player.getRootNode(),g.$6.IV_DRAWER_OPEN);for(var z=this.l_,K=g.rh,f=0,M=z.length;f<M;f++)K.Yg(z[f]);this.l_.length=0;g.R5.prototype.JL.call(this)};
g.k.createElement=function(z){z=new g.F(z);g.d(this,z);return z.element};g.a5("annotations_module",cG7);g.a5("creatorendscreen",Wd2);})(_yt_player);
