(function(g){var window=this;'use strict';var B5p=function(z,K,f){g.n(function(M){z.S=g.V4(K,f);g.Rv(M)})},vh=function(z){z.isActive()||z.start()},N58=function(z,K){return K?z.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},vD4=function(z){return g.$t(z)||z.B("web_enable_caption_language_preference_stickiness")},IiH=function(z,K){var f=new g.aB;
f.languageCode=z.languageCode;f.languageName=z.languageName;f.name=z.name;f.displayName=z.displayName;f.kind=z.kind;f.isDefault=!1;f.S=z.S;f.isTranslateable=z.isTranslateable;f.vssId=z.vssId;f.url=z.url;f.translationLanguage=K;z.xtags&&(f.xtags=z.xtags);z.captionId&&(f.captionId=z.captionId);return f},GAp=function(z,K){var f,M,p;
return g.n(function(t){if(t.Y==1)return f=z+"|"+K,g.l(t,g.fR(),2);if(t.Y!=3){M=t.S;if(!M)throw g.Ql("gct");return g.l(t,g.dA(M),3)}p=t.S;return t.return(p.get("captions",f))})},bFQ=function(z,K,f){GAp(z,K).then(function(M){M&&f(M.trackData,new g.aB(M.metadata))})},DMZ=function(z){if(!euf.test(z))throw Error("'"+z+"' is not a valid hex color");
z.length==4&&(z=z.replace(wX7,"#$1$1$2$2$3$3"));z=z.toLowerCase();z=parseInt(z.slice(1),16);return[z>>16,z>>8&255,z&255]},yCT=function(){var z=void 0;
z=z===void 0?{}:z;var K="suggest_correction"in g.AR7?g.AR7.suggest_correction:"Edit caption";K=K||"";var f={},M;for(M in z){f={xf:f.xf};f.xf=M;var p=function(t){return function(){return String(z[t.xf])}}(f);
K=K.replace(new RegExp("\\$\\{"+f.xf+"\\}","gi"),p);K=K.replace(new RegExp("\\$"+f.xf,"gi"),p)}return K},kAZ=function(){return g.AV("yt-player-caption-display-settings")},IH=function(){this.segments=[]},hu9=function(z,K){var f=g.l_(z.segments,K);
f>=0||f<0&&(-f-1)%2===1||(f=-f-1,f>0&&K-z.segments[f-1]===1&&f<z.segments.length&&z.segments[f]-K===1?(g.a8(z.segments,f),g.a8(z.segments,f-1)):f>0&&K-z.segments[f-1]===1?z.segments[f-1]=K:f<z.segments.length&&z.segments[f]-K===1?z.segments[f]=K:(g.q5(z.segments,f,0,K),g.q5(z.segments,f+1,0,K)))},ai7=function(z,K,f,M,p,t){g.J.call(this);
this.policy=z;this.player=K;this.Y1=f;this.D=M;this.C=p;this.N=t;this.J=new IH;this.W=-1;this.T=this.Y=this.S=null;this.l_=0;this.G=new g.Kl(this.EB,1E3,this);this.events=new g.xI(this);g.d(this,this.G);g.d(this,this.events);this.events.X(K,"SEEK_COMPLETE",this.Ki);this.Ki();this.EB()},Ru1=function(z){return z.S&&z.S.W?z.S.W+z.player.MB()<z.player.getCurrentTime():!1},SU8=function(z,K){if(z.policy.A0&&z.player.XP()){var f=g.Tk(K,z.policy,{});
f.set("pot",z.player.XP());f=f.Ic()}else f=g.Tk(K,z.policy,{}).Ic();var M={format:"RAW",withCredentials:!0};if(z.policy.Bx){M.method="POST";var p=K.J;p&&Object.keys(p).length>0?M.postBody=g.tM(p,g.IR):M.postBody=(0,g.aS)([120,0])}z.C&&(M.responseType="arraybuffer");var t=++z.l_,B=(0,g.X)();z.T=g.gV(f,M,3,100).then(function(v){if(z.policy.Ni&&t%100===1){var I=(0,g.X)();z.player.Th("caprsp",{rn:t,ms:I-B,kb:(v.xhr.responseText.length/1024).toFixed()})}a:{v=v.xhr;z.CH();if(z.Y){var G=!(z.C?v.response:
v.responseText)||v.status>=400;if(I=g.BfS(v)){v=g.Tk(z.Y,z.policy,{});z.Y.hU(v,I);SU8(z,z.Y);break a}if(G)z.player.Th("capfail",{status:v.status});else{var b;g.iq("fcb_r",(0,g.X)(),((b=z.player.getVideoData())==null?void 0:b.N)||"");b=z.Y.tL[0].Ia;z.D!=null&&z.W!==b&&(I=z.Y.tL[0],z.C?z.D(v.response,(I.startTime+z.player.MB())*1E3):z.D(v.responseText,(I.startTime+z.player.MB())*1E3),z.W=b)}}z.Y=null;z.T=null}}).Qf(function(v){z.Y=null;
z.T=null;var I;z.player.Th("capfail",{rn:t,status:(I=v.xhr)==null?void 0:I.status})});
z.Y=K;hu9(z.J,z.Y.tL[0].Ia)},GK=function(z,K){g.u$.call(this,K);
this.S=z;this.U=K;this.T=null;this.W=!1;this.logger=new g.Np("caps");this.G=g.M6q(this.U,this.S)},Lt9=function(z,K){var f=[],M;
for(M in z.S.S)if(z.S.S.hasOwnProperty(M)){var p=z.S.S[M];if(g.Ew(p,K||null)){var t=p.info.id,B=t,v="."+t,I="",G="";if(p=p.info.captionTrack)t=p.languageCode,B=p.displayName,v=p.vssId,I=p.kind,G=p.id;else{p=t;var b=g.Nkp.get(p);b==null&&(b=uCp[p]||uCp[p.replace(/-/g,"_")],g.Nkp.set(p,b));p=b;B=p||B}f.push(new g.aB({id:M,languageCode:t,languageName:B,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:v,kind:I,captionId:G}))}}return f},EDQ=function(z,K){return K!=null&&K in z.S.S?z.S.S[K]:null},
PMQ=function(z,K,f){var M=[],p;
for(p in z.S.S)if(z.S.S.hasOwnProperty(p)){var t=z.S.S[p];if(g.Ew(t,f||null)){var B=t.info.captionTrack;B&&B.languageCode===K&&M.push(t)}}return M.length?M[0]:null},bt=function(z,K,f,M,p,t,B,v,I,G){var b=G.isInline()&&!0,e={};
Object.assign(e,K);Object.assign(e,z.params);Object.assign(e,f);var w={};Object.assign(w,K.l3);z.params.l3&&Object.assign(w,z.params.l3);Object.assign(w,f.l3);b&&(e.windowOpacity=.6,w.backgroundOpacity=0);e.l3=w;var D=e.F2===1,y=[{j:"span",K:"captions-text",V:{style:"word-wrap: normal; display: block;"}}],R,S,E;(v=v.sf("caption_edit_on_hover")&&((R=G.getVideoData().getPlayerResponse())==null?void 0:(S=R.captions)==null?void 0:(E=S.playerCaptionsTracklistRenderer)==null?void 0:E.openTranscriptCommand))&&
y.unshift({j:"button",K:"caption-edit",V:{tabindex:"0","aria-label":yCT()},L:[{j:"svg",V:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},L:[{j:"path",V:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.F.call(this,{j:"div",K:"caption-window",V:{id:"caption-window-"+z.id,dir:D?"rtl":"ltr",tabindex:"0",lang:e.lang},L:y});var L=
this;this.G=[];this.eV=!1;this.Y=z;this.vx=this.Bx=null;this.E0=t;this.ra=B;this.D=null;this.maxWidth=t*.96;this.maxHeight=B*.96;this.S=e;this.O3=f;this.l_=K;this.J=this.dE("captions-text");this.W1=this.J.style.getPropertyValue("box-decoration-break")!==""||this.J.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Xc=HFo(M,p,t,B);this.Z2=I;v&&(this.W=this.dE("caption-edit"),this.X(this.W,"click",function(){L.Z2()}));
this.type=0;this.QE=this.Xc*QnT(w);this.SE=b;z=new g.sR(this.element,!0);g.d(this,z);z.subscribe("dragstart",this.nt,this);z.subscribe("dragmove",this.zi,this);z.subscribe("dragend",this.EY,this);this.VE=this.b_=this.oa=this.rE=0;z="";this.S.windowOpacity&&(z=DMZ(this.S.windowColor),z="rgba("+z[0]+","+z[1]+","+z[2]+","+this.S.windowOpacity+")");K={"background-color":z,display:this.S.isVisible===!1?"none":"","text-align":qU_[this.S.textAlign]};this.W1&&(K["border-radius"]=z?this.QE/8+"px":"");(this.T=
this.Y.params.F2===2||this.Y.params.F2===3)&&mM2(this,this.element);g.H6(this.element,K);if(b){var q;(q=this.element.parentElement)==null||q.style.setProperty("--caption-window-color",z)}switch(this.S.J0){case 0:case 1:case 2:g.ey(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.ey(this.element,"ytp-caption-window-bottom")}},mM2=function(z,K){var f="vertical-rl";
z.S.mH===1&&(f="vertical-lr");g.Sy&&(f=f==="vertical-lr"?"tb-lr":"tb-rl");g.H6(K,"-o-writing-mode",f);g.H6(K,"-webkit-writing-mode",f);g.H6(K,"writing-mode",f);g.H6(K,"text-orientation","upright");g.ey(K,"ytp-vertical-caption");z.Y.params.F2===3&&(g.H6(K,"text-orientation",""),g.H6(K,"transform","rotate(180deg)"))},QnT=function(z){var K=1+.25*(z.fontSizeIncrement||0);
if(z.offset===0||z.offset===2)K*=.8;return K},lio=function(z,K){var f={},M=K.background?K.background:z.S.l3.background;
if(K.backgroundOpacity!=null||K.background){var p=K.backgroundOpacity!=null?K.backgroundOpacity:z.S.l3.backgroundOpacity;M=DMZ(M);f.background="rgba("+M[0]+","+M[1]+","+M[2]+","+p+")";z.W1&&(f["box-decoration-break"]="clone",f["border-radius"]=z.QE/8+"px")}if(K.fontSizeIncrement!=null||K.offset!=null)f["font-size"]=z.Xc*QnT(K)+"px";M=1;p=K.color||z.S.l3.color;if(K.color||K.textOpacity!=null)p=DMZ(p),M=K.textOpacity==null?z.S.l3.textOpacity:K.textOpacity,p="rgba("+p[0]+","+p[1]+","+p[2]+","+M+")",
f.color=p,f.fill=p;var t=K.charEdgeStyle;t===0&&(t=void 0);if(t){p="rgba(34, 34, 34, "+M+")";var B="rgba(204, 204, 204, "+M+")";K.KV&&(B=p=K.KV);var v=z.Xc/16/2,I=Math.max(v,1),G=Math.max(2*v,1),b=Math.max(3*v,1),e=Math.max(5*v,1);M=[];switch(t){case 4:for(;b<=e;b+=v)M.push(G+"px "+G+"px "+b+"px "+p);break;case 1:G=window.devicePixelRatio>=2?.5:1;for(t=I;t<=b;t+=G)M.push(t+"px "+t+"px "+p);break;case 2:M.push(I+"px "+I+"px "+B);M.push("-"+I+"px -"+I+"px "+p);break;case 3:for(b=0;b<5;b++)M.push("0 0 "+
G+"px "+p)}f["text-shadow"]=M.join(", ")}p="";switch(K.fontFamily){case 1:p='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:p='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:p='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:p='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:p='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:p=g.CJ()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:p='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}p&&(f["font-family"]=p);p=K.offset;p==null&&(p=z.S.l3.offset);switch(p){case 0:f["vertical-align"]="sub";break;case 2:f["vertical-align"]="super"}K.fontFamily===7&&(f["font-variant"]="small-caps");K.bold&&(f["font-weight"]="bold");K.italic&&(f["font-style"]="italic");K.underline&&(f["text-decoration"]=
"underline");K.nP&&(f.visibility="hidden");K.hc===1&&z.T&&(f["text-combine-upright"]="all",f["text-orientation"]="mixed",p=g.pa||g.PJ,z.Y.params.F2===3?f.transform=p?"rotate(90deg)":"rotate(180deg)":p&&(f.transform="rotate(-90deg)"));if(K.textEmphasis===1||K.textEmphasis===2||K.textEmphasis===3||K.textEmphasis===4||K.textEmphasis===5)if(g.pa)f["font-weight"]="bold";else switch(f["text-emphasis-style"]="filled circle",f["text-emphasis-color"]="currentcolor",f["webkit-text-emphasis"]="filled circle",
K.textEmphasis){case 4:case 3:f["text-emphasis-position"]="under left";f["webkit-text-emphasis-position"]="under left";break;case 5:case 2:f["text-emphasis-position"]="over right",f["webkit-text-emphasis-position"]="over right"}return f},et=function(z){z=z.split("px");
return z.length>0?(z=Number(z[0]))?z:0:0},V5T=function(z){z.D=g.zi("SPAN");
g.H6(z.D,{display:"block"});g.ey(z.D,"caption-visual-line");z.J.appendChild(z.D)},nDQ=function(z,K){var f=g.zi("SPAN");
g.H6(f,{display:"inline-block","white-space":"pre-wrap"});g.H6(f,lio(z,K));f.classList.add("ytp-caption-segment");z.D.appendChild(f);f.previousElementSibling&&(g.H6(f.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.H6(f,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return f},WtZ=function(z,K,f){z.eV=z.eV||!!f;
var M={};Object.assign(M,z.S.l3);Object.assign(M,f||K.S);Object.assign(M,z.O3.l3);(f=!z.D)&&V5T(z);for(var p=z.Bx&&z.vx&&g.KL(M,z.vx)?z.Bx:nDQ(z,M),t=typeof K.text==="string",B=t?K.text.split("\n"):[K.text],v=0;v<B.length;v++){var I=v>0||!K.append,G=B[v];I&&!f?(V5T(z),p=nDQ(z,M)):I&&f&&(f=!1);G&&(p.appendChild(t?g.Ks(G):G),t||G.tagName!=="RUBY"||G.childElementCount!==4||g.pa||!g.q0(G.children[2],"text-emphasis")||(I=z.T?"padding-right":"padding-top",g.q0(G.children[2],"text-emphasis-position")&&(I=
z.T?"padding-left":"padding-bottom"),g.oz?g.H6(p,I,"1em"):g.H6(p,I,"0.5em")))}z.vx=M;z.Bx=p;z.G.push(K)},HFo=function(z,K,f,M){var p=K/360*16;
K>=z&&(z=640,M>f*1.3&&(z=480),p=f/z*16);return p},gD_=function(){this.T=this.time=this.mode=this.Y=0;
this.J=new JCT(this);this.C=new JCT(this);this.S=[];this.clear()},dM1=function(z,K,f){if(z===255&&K===255||!z&&!K)return{DW:z,
RD:K,result:0};z=iFS[z];K=iFS[K];if(z&128){var M;if(M=!(K&128))M=K,M=f.bl()&&f.RD===M;if(M)return{DW:z,RD:K,result:1}}else if(K&128&&1<=z&&z<=31)return{DW:z,RD:K,result:2};return{DW:z,RD:K,result:3}},sn8=function(z,K,f,M){K===255&&f===255||!K&&!f?(++z.T===45&&z.reset(),z.J.Y.clear(),z.C.Y.clear()):(z.T=0,cCp(z.J,K,f,M))},ACS=function(z,K){z.S.sort(function(p,t){var B=p.time-t.time;
return B===0?p.order-t.order:B});
for(var f=g.a(z.S),M=f.next();!M.done;M=f.next())M=M.value,z.time=M.time,M.type===0?sn8(z,M.Y_,M.lw,K):M.type===1&&z.Y&496&&cCp(z.C,M.Y_,M.lw,K);z.S.length=0},w$=function(){this.type=0},Dr=function(){this.state=this.RD=this.DW=0},jnZ=function(){this.timestamp=this.S=0},yZ=function(z){this.C=z;
this.T=[];this.S=this.Y=this.row=0;this.style=new w$;for(z=this.J=0;z<=15;z++){this.T[z]=[];for(var K=0;K<=32;K++)this.T[z][K]=new jnZ}},k1=function(z,K){if(z.style.type===3){for(var f=0,M=0,p=z.C.time+0,t="",B="",v=p,I=1;I<=15;++I){for(var G=!1,b=M?M:1;b<=32;++b){var e=z.T[I][b];
if(e.S!==0){f===0&&(f=I,M=b);G=String.fromCharCode(e.S);var w=e.timestamp;w<p&&(p=w);e.timestamp=v;B&&(t+=B,B="");t+=G;G=!0}if((e.S===0||b===32)&&G){B="\n";break}else if(M&&!G)break}if(f&&!G)break}t&&K.J(f,M,p,v,t)}else for(M=f=0,t=p=z.C.time+0,B=1;B<=15;++B)for(v="",I=1;I<=32;++I)if(b=z.T[B][I],e=b.S,e!==0&&(f===0&&(f=B,M=I),G=String.fromCharCode(e),w=b.timestamp,w<=p&&(p=w),v+=G,b.reset()),I===32||e===0)v&&K.J(f,M,p,t,v),p=t,v="",M=f=0},OF8=function(z,K){switch(z){case 0:return YUQ[(K&127)-32];
case 1:return XXT[K&15];case 2:return xMS[K&31];case 3:return FtT[K&31]}return 0},h9=function(z){return z.T[z.row][z.Y]},aH=function(z,K,f){K>=2&&z.Y>1&&(--z.Y,h9(z).S=0);
var M=h9(z);M.timestamp=z.C.time+0;M.S=OF8(K,f);z.Y<32&&z.Y++},rCp=function(z,K,f,M){for(var p=0;p<M;p++)for(var t=0;t<=32;t++){var B=z.T[K+p][t],v=z.T[f+p][t];
B.S=v.S;B.timestamp=v.timestamp}},RH=function(z,K,f){for(var M=0;M<f;M++)for(var p=0;p<=32;p++)z.T[K+M][p].reset()},ZF1=function(z){z.row=z.S>0?z.S:1;
z.Y=1;RH(z,0,15)},oDH=function(z){this.T=z;
this.C=0;this.style=new w$;this.W=new yZ(this.T);this.G=new yZ(this.T);this.text=new yZ(this.T);this.Y=this.W;this.J=this.G;this.S=this.Y},CM_=function(z,K,f){var M=z.Y,p=!1;
switch(z.style.get()){case 4:case 1:case 2:z.style.get()===4&&M.S>0||(k1(M,f),ZF1(z.Y),ZF1(z.J),M.row=15,M.S=K,p=!0)}z.style.set(3);z.S=M;z.S.style=z.style;z.T.mode=1<<M.J;p?M.Y=1:M.S!==K&&(M.S>K?(k1(M,f),RH(M,M.row-M.S,K)):M.row<K&&(K=M.S),M.S=K)},T5Q=function(z){z.style.set(1);
z.S=z.J;z.S.S=0;z.S.style=z.style;z.T.mode=1<<z.S.J},UM9=function(z){z.style.set(4);
z.S=z.text;z.S.style=z.style;z.T.mode=1<<z.S.J},JCT=function(z){this.S=z;
this.C=0;this.T=new oDH(this.S);this.W=new oDH(this.S);this.Y=new Dr;this.J=this.T},cCp=function(z,K,f,M){z.Y.update();
K=dM1(K,f,z.Y);switch(K.result){case 0:return;case 1:case 2:return}var p=K.DW;f=K.RD;if(32<=p||!p)z.S.mode&z.S.Y&&(K=p,K&128&&(K=127),f&128&&(f=127),z=z.J.S,K&96&&aH(z,0,K),f&96&&aH(z,0,f),K!==0&&f!==0&&z.style.type===3&&k1(z,M));else if(p&16)a:if(!z.Y.matches(p,f)&&(K=z.Y,K.DW=p,K.RD=f,K.state=2,K=p&8?z.W:z.T,z.J=K,z.S.mode=1<<(z.C<<2)+(K.C<<1)+(K.style.type===4?1:0),(z.S.mode|1<<(z.C<<2)+(K.C<<1)+(K.style.type!==4?1:0))&z.S.Y))if(f&64){M=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(p&7)<<1|f>>5&1];
z=f&16?((f&14)>>1)*4:0;f=K.S;switch(K.style.get()){case 4:M=f.row;break;case 3:if(M!==f.row){if(M<f.S&&(M=f.S,M===f.row))break;var t=1+f.row-f.S,B=1+M-f.S;rCp(f,B,t,f.S);K=t;p=f.S;B<t?(t=B+p-t,t>0&&(K+=t,p-=t)):(t=t+p-B,t>0&&(p-=t));RH(f,K,p)}}f.row=M;f.Y=z+1}else switch(p&7){case 1:switch(f&112){case 32:aH(K.S,0,32);break a;case 48:f===57?(M=K.S,h9(M).S=0,M.Y<32&&M.Y++):aH(K.S,1,f&15)}break;case 2:f&32&&aH(K.S,2,f&31);break;case 3:f&32&&aH(K.S,3,f&31);break;case 4:case 5:if(32<=f&&f<=47)switch(f){case 32:T5Q(K);
break;case 33:M=K.S;M.Y>1&&(--M.Y,h9(M).S=0);break;case 36:M=K.S;K=h9(M);for(z=0;z<=15;z++)for(f=0;f<=32;f++)if(M.T[z][f]===K){for(;f<=32;f++)M.T[z][f].reset();break}break;case 37:CM_(K,2,M);break;case 38:CM_(K,3,M);break;case 39:CM_(K,4,M);break;case 40:aH(K.S,0,32);break;case 41:K.style.set(2);K.S=K.Y;K.S.S=0;K.S.style=K.style;K.T.mode=1<<K.S.J;break;case 42:M=K.text;M.S=15;M.style.set(4);ZF1(M);UM9(K);break;case 43:UM9(K);break;case 44:z=K.Y;switch(K.style.get()){case 1:case 2:case 3:k1(z,M)}RH(z,
0,15);break;case 45:b:{z=K.S;switch(K.style.get()){default:case 2:case 1:break b;case 4:if(z.row<15){++z.row;z.Y=1;break b}break;case 3:}z.S<2&&(z.S=2,z.row<z.S&&(z.row=z.S));K=z.row-z.S+1;k1(z,M);rCp(z,K,K+1,z.S-1);RH(z,z.row,1)}break;case 46:RH(K.J,0,15);break;case 47:k1(K.Y,M),K.J.updateTime(K.T.time+0),M=K.J,K.J=K.Y,K.Y=M,T5Q(K)}break;case 7:switch(f){case 33:case 34:case 35:M=K.S,(M.Y+=f&3)>32&&(M.Y=32)}}},zXT=function(){},St=function(z,K,f,M,p,t,B){t=t===void 0?!1:t;
B=B===void 0?null:B;g.bS.call(this,z,z+K,{priority:f,namespace:"captions"});this.windowId=M;this.text=p;this.append=t;this.S=B},$r7=function(z,K,f,M,p,t,B){var v=t[0],I=B[v.getAttribute("p")];
if(I.pz===1){var G=t[1],b=t[2];t=t[3];v.getAttribute("t");G.getAttribute("t");b.getAttribute("t");t.getAttribute("t");v.getAttribute("p");G.getAttribute("p");t.getAttribute("p");B=B[b.getAttribute("p")];v=Km4(v.textContent,G.textContent,b.textContent,t.textContent,B);return new St(z,K,p,f,v,M,I)}switch(I.pz){case 9:case 10:I.textEmphasis=1;break;case 11:I.textEmphasis=2;break;case 12:I.textEmphasis=3;break;case 13:I.textEmphasis=4;break;case 14:I.textEmphasis=5}return new St(z,K,p,f,v.textContent||
"",M,I)},Km4=function(z,K,f,M,p){var t=g.CJ(),B=t?g.zi("DIV"):g.zi("RUBY"),v=g.zi("SPAN");
v.textContent=z;B.appendChild(v);z=t?g.zi("DIV"):g.zi("RP");z.textContent=K;B.appendChild(z);K=t?g.zi("DIV"):g.zi("RT");K.textContent=f;B.appendChild(K);f=p.pz;if(f===10||f===11||f===12||f===13||f===14)if(g.H6(K,"text-emphasis-style","filled circle"),g.H6(K,"text-emphasis-color","currentcolor"),g.H6(K,"webkit-text-emphasis","filled circle"),p.pz===11||p.pz===13)g.H6(K,"webkit-text-emphasis-position","under left"),g.H6(K,"text-emphasis-position","under left");f=!0;if(p.pz===4||p.pz===7||p.pz===12||
p.pz===14)g.H6(B,"ruby-position","over"),g.H6(B,"-webkit-ruby-position","before");else if(p.pz===5||p.pz===6||p.pz===11||p.pz===13)g.H6(B,"ruby-position","under"),g.H6(B,"-webkit-ruby-position","after"),f=!1;p=t?g.zi("DIV"):g.zi("RP");p.textContent=M;B.appendChild(p);t&&(M=f,g.H6(B,{display:"inline-block",position:"relative"}),t=B.firstElementChild.nextElementSibling,g.H6(t,"display","none"),t=t.nextElementSibling,g.H6(t,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.H6(B.lastElementChild,"display","none"),M?(g.H6(B,"padding-top","0.6em"),g.H6(t,"top","0")):(g.H6(B,"padding-bottom","0.6em"),g.H6(t,"bottom","0")));return B},ut=function(){g.J.apply(this,arguments)},Lk=function(z,K,f,M,p){g.bS.call(this,z,z+K,{priority:f,
namespace:"captions"});this.id=M;this.params=p;this.S=[]},fD9=function(z){var K="_"+EC++;
return new Lk(0,0x8000000000000,0,K,z)},Ph=function(z){ut.call(this);
this.J=z;this.pens={};this.D={};this.N={};this.C="_"+EC++;this.G={};this.Y=this.S=null;this.W=!0},Hh=function(z,K){z=z.getAttribute(K);
if(z!=null)return Number(z)},QZ=function(z,K){z=z.getAttribute(K);
if(z!=null)return z==="1"},qO=function(z,K){z=Hh(z,K);
return z!==void 0?z:null},lt=function(z,K){z=z.getAttribute(K);
if(z!=null)return mB.test(z),z},MU5=function(z,K){var f={},M=K.getAttribute("ws");
Object.assign(f,M?z.N[M]:z.J);z=qO(K,"mh");z!=null&&(f.Ke=z);z=qO(K,"ju");z!=null&&(f.textAlign=z);z=qO(K,"pd");z!=null&&(f.F2=z);z=qO(K,"sd");z!=null&&(f.mH=z);z=lt(K,"wfc");z!=null&&(f.windowColor=z);K=Hh(K,"wfo");K!==void 0&&(f.windowOpacity=K/255);return f},pv5=function(z,K){var f={},M=K.getAttribute("wp");
M&&Object.assign(f,z.D[M]);z=qO(K,"ap");z!=null&&(f.J0=z);z=Hh(K,"cc");z!=null&&(f.aD=z);z=Hh(K,"ah");z!=null&&(f.IL=z);z=Hh(K,"rc");z!=null&&(f.xQ=z);K=Hh(K,"av");K!=null&&(f.hd=K);return f},tUT=function(z,K,f,M){var p={};
Object.assign(p,pv5(z,K));Object.assign(p,MU5(z,K));M?g.KL(p,z.J)?(M=z.C,p=z.J):M="_"+EC++:M=K.getAttribute("id")||"_"+EC++;z=Hh(K,"t")+f;K=Hh(K,"d")||0x8000000000000;if(p.F2===2||p.F2===3)f=p.xQ,p.xQ=p.aD,p.aD=f;return new Lk(z,K,0,M,p)},VZ=function(z){ut.call(this);
this.W=z;this.S=new Map;this.J=new Map;this.C=new Map;this.Y=new Map},nk=function(z){z=g.qt(Math.round(z),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-z.length)+z},B4S=function(z,K,f,M,p){M===0&&(M=0x8000000000000);
var t={};K.wpWinPosId&&Object.assign(t,z.J.get(K.wpWinPosId));K.wsWinStyleId&&Object.assign(t,z.C.get(K.wsWinStyleId));z=K.rcRowCount;z!==void 0&&(t.xQ=z);K=K.ccColCount;K!==void 0&&(t.aD=K);if(t.F2===2||t.F2===3)K=t.xQ,t.xQ=t.aD,t.aD=K;return new Lk(f,M,0,p,t)},Wh=function(z,K,f){g.u$.call(this,z);
this.videoData=K;this.audioTrack=f;this.C=K.q_},J9=function(z,K,f,M,p,t,B,v,I,G){bt.call(this,z,K,f,M,p,t,B,v,I,G);
this.type=1},g$=function(z,K,f){this.trackData=z;
this.W=f;this.version=this.C=this.T=this.byteOffset=0;this.Y=[];this.S=new DataView(this.trackData)},it=function(z){var K=z.byteOffset;
z.byteOffset+=1;return z.S.getUint8(K)},d$=function(z){var K=z.byteOffset;
z.byteOffset+=4;return z.S.getUint32(K)},ch=function(z,K){ut.call(this);
this.Y=z;this.J=K;this.track=this.J.languageName==="CC3"?4:0;this.S=new gD_;this.S.Y=1<<this.track},vpQ=function(z){if(typeof z==="string")return!1;
z=new g$(z,8,0);return N4T(z)},N4T=function(z){if(!(z.byteOffset<z.S.byteLength)||d$(z)!==1380139777)return!1;
z.version=it(z);if(z.version>1)return!1;it(z);it(z);it(z);return!0},sC=function(z,K,f,M,p,t,B,v,I,G){bt.call(this,z,K,f,M,p,t,B,v,I,G);
var b=this;this.type=2;this.nH=[];this.Y1=this.N=this.Px=0;this.Hx=NaN;this.TP=0;this.Ft=null;this.nI=new g.Kl(this.mS,433,this);this.W&&(G.createClientVe(this.W,this,167342),this.X(this.W,"click",function(){G.logClick(b.W)}),z=new g.sR(this.element,!0),g.d(this,z),z.subscribe("hoverstart",function(){G.logVisibility(b.W,!0)},this));
g.ey(this.element,"ytp-caption-window-rollup");g.d(this,this.nI);g.H6(this.element,"overflow","hidden")},IDT=function(z,K){if(!K)return"";
z.T&&z.Y.params.mH!==1&&(K*=-1);return"translate"+(z.T?"X":"Y")+"("+K+"px)"},GzT=function(z){z.nH=Array.from(z.element.getElementsByClassName("caption-visual-line"));
for(var K=z.Y.params.xQ,f=0,M=0,p=z.nH.length-1;f<K&&p>-1;){var t=z.nH[p];M+=z.T?t.offsetWidth:t.offsetHeight;f++;p--}z.N=M;K=Math;f=K.max;isNaN(z.Hx)&&((M=z.S.aD)?(p=g.zi("SPAN"),g.B6(p,"\u2013".repeat(M)),g.H6(p,lio(z,z.S.l3)),z.J.appendChild(p),z.Hx=p.offsetWidth,z.J.removeChild(p)):z.Hx=0);M=z.J;z.Y1=f.call(K,z.Hx,z.TP,(z.T?M.offsetHeight:M.offsetWidth)+1)},beZ=function(z,K){GzT(z);
var f=z.nH.reduce(function(t,B){return(z.T?B.offsetWidth:B.offsetHeight)+t},0);
f=z.N-f;if(f!==z.Px){var M=f>0&&z.Px===0,p=f<z.Px;K||isNaN(f)||M||!p||(g.ey(z.element,"ytp-rollup-mode"),z.X(z.element,"transitionend",z.mS));g.H6(z.J,"transform",IDT(z,f));z.Px=f}GzT(z)},eXo=function(z,K,f,M){var p=this;
this.U=z;this.T=K;this.logger=f;this.CI=M;this.z5=[];this.BE=[];this.S=null;this.dO={z$e:function(){return p.S},
MV:function(){return p.z5}};
z=g.uY(this.U.Z().experiments,"html5_override_micro_discontinuities_threshold_ms");this.Y=z>0?z:10},yo1=function(z,K){z.S=function(f,M){if(f.info.C){var p=f;
if(z.BE.length>0){for(p=z.BE.shift();z.BE.length>0;)p=g.bj(p,z.BE.shift());p=g.bj(p,f)}if(p){f=p;try{var t=g.en(f)*1E3}catch(G){t=f.info.startTime*1E3}try{var B=g.ChT(f)*1E3}catch(G){B=f.info.duration*1E3}if(t<0||B<0)t<0&&(t=f.info.startTime*1E3),B<0&&(B=f.info.duration*1E3);f.info.startTime=t/1E3;f.info.J=t/1E3;f.info.duration=B/1E3;f.info.G=B/1E3;t=z.gr(p);B=t.Ia;t={formatId:t.formatId,startTimeMs:t.startTimeMs,durationMs:t.durationMs,g2:B,TH:B};B=wvT(z.z5,t.startTimeMs);var v=(f=B>=0?z.z5[B]:null)?
f.startTimeMs+f.durationMs:0,I=t.startTimeMs+t.durationMs;!f||t.startTimeMs-v>z.Y?z.z5.splice(B+1,0,t):(f.durationMs=Math.max(v,I)-f.startTimeMs,f.TH=Math.max(f.TH,t.TH));M(z.z5);M=g.GO(p);Dro(z.T,M.buffer.slice(M.byteOffset,M.byteLength+M.byteOffset),K,p.info.J)}else z.logger.S(350058965,"Empty slice")}else z.BE.push(f)};
z.U.addEventListener("sabrCaptionsDataLoaded",z.S)},wvT=function(z,K){z=g.l_(z,{startTimeMs:K},function(f,M){return f.startTimeMs-M.startTimeMs});
return z>=0?z:-z-2},kz2=function(z,K){g.u$.call(this,K);
this.S=z;this.U=K;this.logger=new g.Np("caps");this.T=this.W=null;this.G=new eXo(this.U,this,this.logger,this.S.CI)},Dro=function(z,K,f,M){z.logger.debug(function(){return"SABR captions data received for "+M});
z.W?z.T==null?z.logger.S(350058965,"Null loaded track meta data at captions data received"):f.jX(K,z.T,M*1E3):z.logger.S(350058965,"Null Representation at captions data received")},hX9=function(z,K){var f=[],M;
for(M in z.S.S)if(z.S.S.hasOwnProperty(M)){var p=z.S.S[M];if(g.Ew(p,K||null)){var t=p.info.id,B=t,v="."+t,I="",G="";if(p=p.info.captionTrack)t=p.languageCode,B=p.displayName,v=p.vssId,I=p.kind,G=p.id;f.push(new g.aB({id:M,languageCode:t,languageName:B,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:v,kind:I,captionId:G}))}}return f},aDS=function(z,K,f){var M=[],p;
for(p in z.S.S)if(z.S.S.hasOwnProperty(p)){var t=z.S.S[p];if(g.Ew(t,f||null)){var B=t.info.captionTrack;B&&B.languageCode===K&&M.push(t)}}return M.length?M[0]:null},RXZ=function(z,K){if(!g.Vbg(z)||z.S!=null&&g.M6q(K,z.S)&&z.S.S.rawcc!=null)return!1;
K=!!z.S&&z.S.isManifestless&&Object.values(z.S.S).some(function(f){return g.Ew(f,"386")});
z=!!z.S&&!z.S.isManifestless&&g.GxW(z.S);return K||z},SWT=function(){ut.call(this)},Lm7=function(z){var K=uOf.length;
if(z.byteLength<K)return!1;z=new Uint8Array(z,0,K);for(var f=0;f<K;f++)if(uOf[f]!==z[f])return!1;return!0},Ep7=function(z,K,f,M,p,t,B,v,I){switch(B.tagName){case "b":v.bold=!0;
break;case "i":v.italic=!0;break;case "u":v.underline=!0}for(var G=0;G<B.childNodes.length;G++){var b=B.childNodes[G];if(b.nodeType===3)b=new St(K,f,M,p.id,b.nodeValue,t||G>0,g.U9(v)?void 0:v),I.push(b),p.S.push(b);else{var e={};Object.assign(e,v);Ep7(z,K,f,M,p,!0,b,e,I)}}},P6p=function(z){var K=z.split(":");
z=0;K=g.a(K);for(var f=K.next();!f.done;f=K.next())z=z*60+Number(f.value);return z*1E3},HeS=function(z,K,f,M){M=Object.assign({Ke:0},M);
return new Lk(z,K,f,"_"+EC++,M)},A9=function(z,K){g.J.call(this);
this.U=z;this.SV=K;this.S=null;this.Y=this.U.iB();this.logger=new g.Np("caps")},qWS=function(z,K,f){if(typeof K==="string"||vpQ(K))return[{trackData:K,
i6:f}];if(typeof K==="string"&&K.substring(0,6)==="WEBVTT"||typeof K!=="string"&&Lm7(K))return[{trackData:K,i6:f}];var M=new DataView(K);if(M.byteLength<=8||M.getUint32(4)!==1718909296)return[];var p=g.TIg(M);if(z.Y&&p){var t=g.XfS(p),B=g.xTa(p);p=p.fJ;t&&p&&z.Y.LK(p,t,B)}z=g.Ia(M,1835295092);if(!z||!z.length||!z[0].size)return[];t=[];for(B=0;B<z.length;B++)p=z[B],p=new Uint8Array(K,p.dataOffset,p.size-(p.dataOffset-p.offset)),p=g.dz(p),t.push({trackData:p,i6:f+B*1E3});QW7(M,t,f);return t=t.filter(function(v){return!!v.trackData})},
QW7=function(z,K,f){var M=g.KN(z,0,1836476516),p=9E4;
M&&(p=g.$b(M)||9E4);M=0;for(var t=g.Ia(z,1836019558),B=0;B<t.length;B++){var v=t[B];B<K.length&&(v=g.KN(z,v.dataOffset,1953653094))&&(v=g.KN(z,v.dataOffset,1952867444))&&(v=g.N6(v)/p*1E3,B===0&&(M=v),K[B].i6=v-M+f||f*B*1E3)}},mrQ=function(z,K,f){z.S||(z.S=new SWT);
z=z.S.T(K,f);Math.random()<.01&&g.Al(Error("Deprecated subtitles format in web player: WebVTT"));return z},lD_=function(z){var K={};
if(z=g.u1(z))K.lang=z,g.aKS.test(z)&&(K.F2=1);return K},Wmp=function(z){g.R5.call(this,z);
var K=this;this.U=z;this.Bx=[];this.nH={};this.QE={};this.W=!1;this.J="NONE";this.Y=this.N=this.Y1=this.Xc=this.rE=null;this.nI={ij:function(){K.ij()},
jX:function(t,B,v,I){K.jX(t,B,v,I)}};
this.S=null;this.SV=this.U.Z();this.videoData=this.U.getVideoData();this.oa=this.U.wE();this.T={l3:{}};this.G={l3:{}};g.op(this.videoData)?this.J="OFFLINE":RXZ(this.videoData,this.U)?this.J="SABR_LIVE":g.pSS(this.videoData,this.U)?this.J="LIVE":this.videoData.captionTracks.length?this.J="INNERTUBE":this.videoData.C3&&(this.J="TTS");this.b_=this.SV.controlsType==="3";this.VE=new A9(this.U,this.SV);this.eV=new g.xI(this);this.D=new g.F({j:"div",K:"ytp-caption-window-container",V:{id:"ytp-caption-window-container"}});
this.l_={top:0,right:0,bottom:0,left:0,width:1,height:1};var f=null,M=g.Xi("yt-html5-player-modules::subtitlesModuleData");M&&(f=new g.JU(M));this.storage=f;var p;this.SE=!((p=z.qL())==null||!p.va());this.C=VUp(this);this.Hx=!this.C&&this.b_&&this.SE&&(this.J==="LIVE"||this.J==="SABR_LIVE");g.d(this,this.VE);this.C?this.Px=this.vx=null:(this.vx=new g.zJ(this.a4,void 0,this),g.d(this,this.vx),this.Px=new g.Kl(this.mTa,2E3,this),g.d(this,this.Px));g.d(this,this.eV);g.dq(this.player,this.D.element,4);
g.d(this,this.D);this.C||this.eV.X(z,"resize",this.Ze);(this.TP=g.si(this.SV)&&!g.L3()&&!this.U.isFullscreen()&&!this.C&&!this.Hx)&&this.eV.X(z,"resize",this.P8f);this.eV.X(z,"onPlaybackAudioChange",this.khe);this.eV.X(z,g.wE("captions"),function(t){K.onCueRangeEnter(t)});
this.eV.X(z,g.DU("captions"),function(t){K.onCueRangeExit(t)});
npf(this,kAZ()||{});this.player.rO("onCaptionsModuleAvailable")},ie5=function(z){if(z.SV.tU===1||z.videoData.EZ===1||g.Q_(z.videoData,"yt:cc")==="alwayson")return!0;
if(z.videoData.captionTracks.length)var K=z.getAudioTrack().Y;if(z.SV.tU===2){if(g.$t(z.SV))var f=Jo4(z);else if(z.storage)try{f=z.storage.get("module-enabled")}catch(p){z.storage.remove("module-enabled")}else f=null;if(f!=null)return!!f}f=N58(z.player.getAudioTrack(),g.$t(z.SV));var M=g.Q_(z.videoData,"yt:cc");if(gp9(z)===void 0){if(f==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return M?M==="on":!0;if(f==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return M==="on"}else return M==="on";return K==="ON"||
g.Q_(z.videoData,"yt:cc")==="on"},jt=function(z,K){if(z.S&&(K===void 0||!K)||!z.videoData.captionTracks.length)return!1;
z=z.getAudioTrack();return!!z.S||z.Y==="FORCED_ON"},gp9=function(z){var K=void 0,f=g.r0(g.OT(),65);
if(g.$t(z.SV)&&f!=null){if(Jo4(z)!=null)return!1;K=!f}return K},Xw=function(z,K){if(!z.Y)return null;
if(z.N&&z.N.J)return z.N.J;K=dr7(z,K);K=g.MN(z.Y.Y,K);var f=null;if(vD4(z.SV)){var M=z.U.isInline()?void 0:g.AV("yt-player-caption-sticky-language");for(var p=[M,z.videoData.captionsLanguagePreference,z.SV.captionsLanguagePreference,g.Q_(z.videoData,"yt:cc_default_lang")],t=!1,B=0;B<p.length;B++){var v=p[B];if(v){t=!0;for(var I=0;I<K.length;I++)if(g.u1(K[I])===v)return K[I];for(I=0;I<K.length;I++)if(g.u1(K[I]).split("-")[0]===v.split("-")[0])return K[I]}}if(t&&z.Y&&(p=z.Y.C,p.length))for(p=g.a(p),
t=p.next();!t.done;t=p.next())if(t=t.value,t.languageCode===M){f=t;break}}else for(M=[z.videoData.captionsLanguagePreference,z.SV.captionsLanguagePreference,g.Q_(z.videoData,"yt:cc_default_lang")],p=0;p<M.length;p++)for(t=0;t<K.length;t++)if(g.u1(K[t])===M[p])return K[t];M=null;z.N&&z.N.T&&(M=z.N.T);M||(M=K.find(function(G){return G.isDefault})||null);
M||(M=K[0]||Y1(z));M&&f&&g.u1(M).split("-")[0]!==f.languageCode.split("-")[0]&&(M=IiH(M,f));return M},Y1=function(z){return z.N&&z.N.S},x1=function(z){var K=Y1(z);
return!!K&&z.S===K},coo=function(z,K){var f=z.U.qL().H1().textTracks;
z=z.S.toString();for(var M=0;M<f.length;M++){var p=f[M];p.id===z&&(K?p.mode!=="showing"&&(p.mode="showing"):p.mode==="showing"&&(p.mode="disabled"))}},Zr=function(z,K,f){z.loaded&&z.unload();
f!=null&&(z.W=f,z.W&&(g.$t(z.SV)?Fw(z,!!K):OC(z,!!K)));z.SV.B("html5_sends_cfs_after_caption_loaded")||z.SV.B("html5_sends_cfs_after_caption_parsed")?(K!==null||jt(z,!0)||r$(z,null,K,z.W,!1),z.S=K,jt(z)&&(z.S=Y1(z))):(r$(z,z.S,K,z.W,!1),z.S=K,jt(z)&&(K=Y1(z),r$(z,z.S,K,z.W,!0),z.S=K));var M;sWH(z,(M=z.S)!=null?M:void 0);z.load()},jWp=function(z,K){if(K instanceof Lk){var f=z.nH[K.id];
f&&f.Y!==K&&(f.dispose(),delete z.nH[K.id],f=null);f||(f=Ao1(z,K))&&(z.nH[K.id]=f)}else f=K.windowId,z.QE[f]||(z.QE[f]=[]),z.QE[f].push(K)},Ao1=function(z,K){var f=YW8(z);
if(!f)return null;var M=z.S?g.u1(z.S):null;M&&g.aKS.test(M)&&(K.params.F2=1);var p=z.oa.getPlayerSize();M=p.height*z.l_.height;p=p.width*z.l_.width;z.SV.playerStyle!=="google-live"||z.T.isDefault||Object.assign(K.params,z.T);switch(K.params.Ke!=null?K.params.Ke:K.S.length>1?1:0){case 1:return new J9(K,z.T,z.G,f.width,f.height,p,M,z.SV.experiments,z.j2.bind(z),z.U);case 2:return new sC(K,z.T,z.G,f.width,f.height,p,M,z.SV.experiments,z.j2.bind(z),z.U);default:return new bt(K,z.T,z.G,f.width,f.height,
p,M,z.SV.experiments,z.j2.bind(z),z.U)}},npf=function(z,K,f){f=f===void 0?!1:f;
var M=oH.l3;z.T={};Object.assign(z.T,oH);z.T.l3={};Object.assign(z.T.l3,M);z.G={l3:{}};var p=K.backgroundOverride?z.G:z.T,t=K.background||M.background;mB.test(t);p.l3.background=t;p=K.colorOverride?z.G:z.T;t=K.color||M.color;mB.test(t);p.l3.color=t;p=K.windowColorOverride?z.G:z.T;t=K.windowColor||oH.windowColor;mB.test(t);p.windowColor=t;p=K.backgroundOpacityOverride?z.G:z.T;t=K.backgroundOpacity;t==null&&(t=M.backgroundOpacity);p.l3.backgroundOpacity=t;p=K.fontSizeIncrementOverride?z.G:z.T;t=K.fontSizeIncrement;
t==null&&(t=M.fontSizeIncrement);p.l3.fontSizeIncrement=t;t=K.fontStyleOverride?z.G:z.T;p=K.fontStyle;p==null&&(p=M.bold&&M.italic?3:M.bold?1:M.italic?2:0);t=t.l3;switch(p){case 1:t.bold=!0;delete t.italic;break;case 2:delete t.bold;t.italic=!0;break;case 3:t.bold=!0;t.italic=!0;break;default:delete t.bold,delete t.italic}p=K.textOpacityOverride?z.G:z.T;t=K.textOpacity;t==null&&(t=M.textOpacity);p.l3.textOpacity=t;p=K.windowOpacityOverride?z.G:z.T;t=K.windowOpacity;t==null&&(t=oH.windowOpacity);p.windowOpacity=
t;p=K.charEdgeStyleOverride?z.G:z.T;t=K.charEdgeStyle;t==null&&(t=M.charEdgeStyle);p.l3.charEdgeStyle=t;p=K.fontFamilyOverride?z.G:z.T;t=K.fontFamily;t==null&&(t=M.fontFamily);p.l3.fontFamily=t;z.loaded&&z.Ze();f&&g.sT("yt-player-caption-display-settings",K,2592E3)},Xv7=function(z,K){if(!z.Y)return{};
if(K){g.U9(K)||z.uI(K.vss_id,"m");if(z.C||!g.$f(K))return;if(g.U9(K)){Zr(z,null,!0);return}for(var f,M=g.MN(z.Y.Y,!0),p=0;p<M.length;p++){var t=M[p];t.languageCode!==K.languageCode||f&&(t.languageName!==K.languageName||(t.captionId||"")!==(K.captionId||"")||g.RB(t)!==K.displayName)||(f=K.translationLanguage?IiH(t,K.translationLanguage):t)}z.rd(K.position);!f||f===z.S&&z.loaded||(K=g.zF(),M=g.u1(f),K.length&&M===K[K.length-1]||(K.push(M),g.sT("yt-player-caption-language-preferences",K)),vD4(z.SV)&&
!z.U.isInline()&&g.sT("yt-player-caption-sticky-language",M,2592E3),Zr(z,f,!0))}else return z.loaded&&z.S&&!x1(z)?g.S1(z.S):{};return""},Fmp=function(z,K,f){K&&!z.Y1?(K=fD9({F2:0,
lang:"fr"}),z.Y1=[K,new St(K.start,K.end-K.start,0,K.id,f!=null?f:"Aper\u00e7u des sous-titres")],z.player.St(z.Y1)):!K&&z.Y1&&(xr1(z,z.Y1),z.Y1=null)},xr1=function(z,K){z.player.gL(K);
K=g.a(K);for(var f=K.next();!f.done;f=K.next())g.R8(z.Bx,f.value);vh(z.vx)},sWH=function(z,K){z.SV.B("html5_modify_caption_vss_logging")&&(z.videoData.Ax=K)},YW8=function(z){var K=z.oa.getVideoContentRect(!0).height,f=z.oa.getVideoContentRect(!0).width;
if(!K||!f)return null;K*=z.l_.height;f*=z.l_.width;return{width:f,height:K}},OC=function(z,K){if(z.storage)try{z.storage.set("module-enabled",K)}catch(f){}},Fw=function(z,K){z.U.isInline()||g.sT("yt-player-sticky-caption",K,2592E3)},Jo4=function(z){if(!z.U.isInline())return g.AV("yt-player-sticky-caption")},VUp=function(z){var K,f=!((K=z.U.qL())==null||!K.mj());
return z.b_&&f&&z.J!=="LIVE"&&z.J!=="SABR_LIVE"},dr7=function(z,K){g.Af(z.videoData)&&(K=!0);
K||(K=z.J==="TTS"?!1:z.J==="INNERTUBE"?!1:!0);return K||z.SV.B("web_deprecate_always_includes_asr_setting")&&g.$t(z.SV)?!0:!!g.r0(g.OT(),66)},r$=function(z,K,f,M,p){z.SV.B("html5_sends_cfs_after_caption_loaded")||z.SV.B("html5_sends_cfs_after_caption_parsed")?z.uW(f,!!f,p?"g":M?"m":"s"):p?z.uW(f,!0,"g"):M?K?z.uW(f,!!f,"m"):f&&z.uW(f,!0,"m"):!K&&f&&z.uW(f,!0,"s")};
g.u$.prototype.Nx=g.pW(77,function(){return!1});
g.u$.prototype.bY=g.pW(76,function(){});
g.LK.prototype.bY=g.pW(75,function(z,K,f){var M=this;this.CH();K=this.vD(z,K);var p=this.Fc.Z().B("html5_report_captions_ctmp_qoe"),t=(0,g.X)();this.cg();B5p(this,K,{format:"RAW",onSuccess:function(B){M.S=null;if(p){var v=(B.responseText.length/1024).toFixed(),I=(0,g.X)();M.videoData.Th("capresp",{ms:I-t,kb:v})}f.jX(B.responseText,z)},
onError:p?function(B){var v;B=(v=B==null?void 0:B.status)!=null?v:0;M.videoData.Th("capfail",{status:B})}:void 0,
withCredentials:!0})});
g.Pu.prototype.bY=g.pW(74,function(z,K,f){var M=this;this.CH();K=this.vD(z,K);this.cg();this.S=g.V4(K,{format:"RAW",onSuccess:function(p){M.S=null;f.jX(p.responseText,z)},
withCredentials:!0})});
g.r9.prototype.NJ=g.pW(73,function(){for(var z=g.Os(document,"track",void 0,this.S),K=0;K<z.length;K++)g.ps(z[K])});
g.io.prototype.NJ=g.pW(72,function(){this.mediaElement.NJ()});
g.r9.prototype.va=g.pW(71,function(){return!(!this.S.textTracks||!this.S.textTracks.addEventListener)});
g.io.prototype.va=g.pW(70,function(){return this.mediaElement.va()});
g.r9.prototype.mj=g.pW(69,function(){return!!this.S.textTracks});
g.io.prototype.mj=g.pW(68,function(){return this.mediaElement.mj()});
g.r9.prototype.GT=g.pW(67,function(z){for(var K=0;K<z.length;K++)this.S.appendChild(z[K])});
g.io.prototype.GT=g.pW(66,function(z){this.mediaElement.GT(z)});
g.oF.prototype.LK=g.pW(65,function(z,K,f){this.Z3.LK(z,K,f)});
g.oJ.prototype.LK=g.pW(64,function(z,K,f){this.Y.set(z,{N_:K,Zu:f})});
g.CY.prototype.LK=g.pW(63,function(z,K,f){this.Hx.LK(z,K,f)});
g.oF.prototype.PF=g.pW(62,function(z){return this.Z3.PF(z)});
g.CY.prototype.PF=g.pW(61,function(z){var K=2;this.G.has(z)?K=0:g.MMa(this,z)&&(K=1);return K});
g.m8.prototype.o3=g.pW(49,function(z){var K=this.app.FL({playerType:void 0});return K?K.o3(z):!1});
g.Xm.prototype.o3=g.pW(48,function(z){return this.AL.mR.o3(z)});
g.W3.prototype.o3=g.pW(47,function(z){return this.B7().some(function(K){return K.namespace===z})});
g.j0.prototype.o3=g.pW(46,function(){return!1});
g.m8.prototype.uI=g.pW(44,function(z,K){this.app.Of().uI(z,K)});
g.Xm.prototype.uI=g.pW(43,function(z,K){this.AL.uI(z,K)});
g.wv.prototype.uI=g.pW(42,function(z,K){z=[z,K];g.ef(this,g.ZL(this.provider),"cfi",z)});
g.mO.prototype.uI=g.pW(41,function(z,K){this.qoe&&this.qoe.uI(z,K)});
g.M9.prototype.uI=g.pW(40,function(z,K){this.Vh().uI(z,K)});
g.j0.prototype.uI=g.pW(39,function(){});
g.m8.prototype.uW=g.pW(38,function(z,K,f){this.app.Of().uW(z,K,f)});
g.Xm.prototype.uW=g.pW(37,function(z,K,f){this.AL.uW(z,K,f)});
g.wv.prototype.uW=g.pW(36,function(z,K,f){if(this.vx!==z||this.Z2!==K)K=K==="rawcc"?"":K,f=[z,K,this.vx,f],g.ef(this,g.ZL(this.provider),"cfs",f),this.vx=z,this.Z2=K});
g.mO.prototype.uW=g.pW(35,function(z,K,f){this.qoe&&this.qoe.uW(z,K,f)});
g.M9.prototype.uW=g.pW(34,function(z,K,f){this.Vh().uW(z,K,f)});
g.j0.prototype.uW=g.pW(33,function(){});
g.rX.prototype.Lr=g.pW(20,function(){return this.Y1});
g.hJ.prototype.Lr=g.pW(19,function(){return this.Of().iB()});
g.m8.prototype.iB=g.pW(18,function(){return this.app.Lr()});
g.Xm.prototype.iB=g.pW(17,function(){return this.AL.iB()});
g.M9.prototype.iB=g.pW(16,function(){var z;return((z=this.loader)==null?void 0:z.Lr())||null});
g.j0.prototype.iB=g.pW(15,function(){return null});
g.jA.prototype.jj=g.pW(1,function(z){return(z=this.It(z))?z.S:0});
g.ky.prototype.jj=g.pW(0,function(){return 0});
var wX7=/#(.)(.)(.)/,euf=/^#(?:[0-9a-f]{3}){1,2}$/i,uCp={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};IH.prototype.contains=function(z){z=g.l_(this.segments,z);return z>=0||z<0&&(-z-1)%2===1};
IH.prototype.length=function(){return this.segments.length/2};
g.h(ai7,g.J);g.k=ai7.prototype;g.k.JL=function(){g.J.prototype.JL.call(this);this.T&&this.T.cancel()};
g.k.Ki=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(z){z-=this.player.MB();var K=this.S;this.S=g.eS(this.Y1.WD(z).tL);K!==this.S&&this.N&&this.N()};
g.k.reset=function(){this.J=new IH;this.W=-1;this.T&&(this.T.cancel(),this.T=null)};
g.k.EB=function(){this.CH();var z;if(z=this.S!=null)z=this.S,z=z.S.VH(z);if(z&&!this.T&&!(this.S&&this.S.startTime-this.player.getCurrentTime()>30)){z=this.S;z=z.S.Ll(z);var K=z.tL[0],f;if((f=this.player.getVideoData())==null?0:f.enableServerStitchedDai)if(f=this.player.iB()){var M=K.S.info.id,p=K.Ia,t=z.tL[0].J;if(this.policy.Bx){if(f=f.xl(t,p,M,3))z.J=f}else if(M=f.mU(t,p,M,3))if(f=f.PF(p),f===0)M&&(z.S=new g.WN(M));else if(f===2){this.G.start();Ru1(this)&&this.seekTo(this.player.getCurrentTime());
return}}K.S.index.Zz(K.Ia)?(this.J.contains(z.tL[0].Ia)||SU8(this,z),this.S=g.eS(z.tL)):Ru1(this)&&this.seekTo(this.player.getCurrentTime())}this.G.start()};
g.h(GK,g.u$);g.k=GK.prototype;g.k.bY=function(z,K,f){var M=this;this.cg();K=EDQ(this,z.getId());K||(K=z.languageCode,K=this.S.isManifestless?PMQ(this,K,"386"):PMQ(this,K));if(K){var p=(K.index.jj(K.index.PV())-K.index.getStartTime(K.index.PV()))*1E3,t=this.U.Z(),B=new g.bOv(t),v=function(){M.T&&M.T.reset();M.W=!0};
t.B("html5_keep_caption_data_after_seek")&&(v=null);this.T=new ai7(B,this.U,K,function(I,G){f.jX(I,z,G,p)},this.G||g.tn(K.info),v)}};
g.k.Nx=function(){var z=this.W;this.W=!1;return z};
g.k.bT=function(z){var K=this.U.Z().B("html5_fallback_if_rawcc_missing");var f=this.S.S.rawcc!=null;if(!this.G||!f&&K)K=this.S.isManifestless?Lt9(this,"386"):Lt9(this);else{if(!f){this.logger.S(386248249,"rawcc used but unavailable");return}K=[new g.aB({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.aB({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}K=g.a(K);
for(f=K.next();!f.done;f=K.next())g.SE(this.Y,f.value);z.ij()};
g.k.cg=function(){this.T&&(this.T.dispose(),this.T=null)};
g.k.vD=function(){return""};
g.k.Q4=function(){this.T&&(this.T.reset(),this.U.GE("captions"))};
var mB=/^#(?:[0-9a-f]{3}){1,2}$/i;var qU_=["left","right","center","justify"];g.h(bt,g.F);g.k=bt.prototype;g.k.nt=function(z,K){this.b_=z;this.VE=K;var f=g.gW(this.element,this.element.parentElement);this.rE=z-f.x;this.oa=K-f.y};
g.k.zi=function(z,K){if(z!==this.b_||K!==this.VE){g.bx(this.element,"ytp-dragging")||g.ey(this.element,"ytp-dragging");var f=g.dW(this.element);z=z-this.rE-.02*this.E0;var M=K-this.oa-.02*this.ra,p=(z+f.width/2)/this.maxWidth*3;p=Math.floor(g.qt(p,0,2));var t=(M+f.height/2)/this.maxHeight*3;t=Math.floor(g.qt(t,0,2));K=p+t*3;z=(z+p/2*f.width)/this.maxWidth;z=g.qt(z,0,1)*100;f=(M+t/2*f.height)/this.maxHeight;f=g.qt(f,0,1)*100;this.Y.params.J0=K;this.Y.params.hd=f;this.Y.params.IL=z;this.Y.params.isDefault=
!1;this.S.J0=K;this.S.hd=f;this.S.IL=z;this.S.isDefault=!1;this.l_.J0=K;this.l_.hd=f;this.l_.IL=z;this.l_.isDefault=!1;this.UR()}};
g.k.EY=function(){g.Dz(this.element,"ytp-dragging")};
g.k.UR=function(){this.Zr(this.G)};
g.k.Zr=function(z){var K=this.SE?0:Math.min(this.xt(),this.maxWidth),f=this.eP(),M=this.SE;if(M){var p=getComputedStyle(this.J.parentNode);p=et(p.borderLeftWidth)+et(p.borderRightWidth)+et(p.paddingLeft)+et(p.paddingRight)}else p=0;var t=p;p="";this.Y.params.F2===3&&(p="rotate(180deg)");var B=M?"calc(96% - "+t+"px)":"96%";g.H6(this.element,{top:0,left:0,right:"",bottom:"",width:K?K+"px":"",height:f?f+"px":"","max-width":B,"max-height":B,margin:"",transform:""});this.pV(z);p={transform:p,top:"",left:"",
width:K?K+"px":"",height:f?f+"px":"","max-width":"","max-height":""};var v=this.S.IL*.96+2;B=this.S.J0;switch(B){case 0:case 3:case 6:(M=this.S.l3.fontSizeIncrement)&&M>0&&this.S.F2!==2&&this.S.F2!==3&&(v=Math.max(v/(1+M*2),2));p.left=v+"%";break;case 1:case 4:case 7:p.left=v+"%";v=this.J.offsetWidth;K||v?(K=K||v+1,p.width=K+"px",p["margin-left"]=M?K/-2-t/2+"px":K/-2+"px"):p.transform+=" translateX(-50%)";break;case 2:case 5:case 8:p.right=100-v+"%"}M=this.S.hd*.96+2;switch(B){case 0:case 1:case 2:p.top=
M+"%";break;case 3:case 4:case 5:p.top=M+"%";(f=f||this.element.clientHeight)?(p.height=f+"px",p["margin-top"]=f/-2+"px"):p.transform+=" translateY(-50%)";break;case 6:case 7:case 8:p.bottom=100-M+"%"}g.H6(this.element,p);if(this.W){f=this.J.offsetHeight;M=1;for(K=0;K<z.length;K++)p=z[K],typeof p.text==="string"&&(M+=p.text.split("\n").length-1,p.append||K===0||M++);f/=M;this.W.style.height=f+"px";this.W.style.width=f+"px";this.element.style.paddingLeft=f+5+"px";this.element.style.paddingRight=f+
5+"px";z=Number(this.element.style.marginLeft.replace("px",""))-f-5;f=Number(this.element.style.marginRight.replace("px",""))-f-5;this.element.style.marginLeft=z+"px";this.element.style.marginRight=f+"px"}};
g.k.pV=function(z){var K;for(K=0;K<z.length&&z[K]===this.G[K];K++);if(this.eV||this.G.length>K)K=0,this.eV=!1,this.G=[],this.D=this.vx=this.Bx=null,g.fs(this.J);for(;K<z.length;K++)WtZ(this,z[K])};
g.k.xt=function(){return 0};
g.k.eP=function(){return 0};
g.k.toString=function(){return g.F.prototype.toString.call(this)};gD_.prototype.clear=function(){this.T=this.time=this.mode=0;this.S=[];this.reset()};
gD_.prototype.reset=function(){this.mode=0;this.J.reset(0);this.C.reset(1)};
var iFS=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];w$.prototype.set=function(z){this.type=z};
w$.prototype.get=function(){return this.type};
Dr.prototype.clear=function(){this.state=0};
Dr.prototype.update=function(){this.state=this.state===2?1:0};
Dr.prototype.bl=function(){return this.state!==0};
Dr.prototype.matches=function(z,K){return this.bl()&&z===this.DW&&K===this.RD};
jnZ.prototype.reset=function(){this.timestamp=this.S=0};
yZ.prototype.updateTime=function(z){for(var K=1;K<=15;++K)for(var f=1;f<=32;++f)this.T[K][f].timestamp=z};
yZ.prototype.debugString=function(){for(var z="\n",K=1;K<=15;++K){for(var f=1;f<=32;++f){var M=this.T[K][f];z=M.S===0?z+"_":z+String.fromCharCode(M.S)}z+="\n"}return z};
yZ.prototype.reset=function(z){for(var K=0;K<=15;K++)for(var f=0;f<=32;f++)this.T[K][f].reset();this.J=z;this.S=0;this.Y=this.row=1};
var YUQ=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],XXT=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],xMS=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],FtT=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];oDH.prototype.reset=function(z,K){this.C=K;this.style.set(2);this.Y=this.W;this.J=this.G;this.S=this.Y;var f=(z<<2)+(K<<1);this.W.reset(f);this.G.reset(f);this.text.reset((z<<2)+(K<<1)+1)};
JCT.prototype.reset=function(z){this.C=z;this.Y.clear();this.J=this.T;this.T.reset(z,0);this.W.reset(z,1)};zXT.prototype.J=function(){};g.h(St,g.bS);St.prototype.toString=function(){return g.bS.prototype.toString.call(this)};g.h(ut,g.J);ut.prototype.reset=function(){};g.h(Lk,g.bS);Lk.prototype.toString=function(){return g.bS.prototype.toString.call(this)};
var EC=0;g.h(Ph,ut);Ph.prototype.reset=function(){this.G={};this.Y=this.S=null;this.W=!0};
Ph.prototype.T=function(z,K){z=z.firstChild;z.getAttribute("format");K=K||0;Number.isFinite(K);z=Array.from(z.childNodes);z=g.a(z);for(var f=z.next();!f.done;f=z.next())if(f=f.value,f.nodeType===1)switch(f.tagName){case "head":var M=f;break;case "body":var p=f}if(M)for(M=Array.from(M.childNodes),M=g.a(M),z=M.next();!z.done;z=M.next())if(z=z.value,z.nodeType===1)switch(z.tagName){case "pen":f=z.getAttribute("id");var t=this.pens,B={},v=z.getAttribute("p");v&&Object.assign(B,this.pens[v]);v=QZ(z,"b");
v!=null&&(B.bold=v);v=QZ(z,"i");v!=null&&(B.italic=v);v=QZ(z,"u");v!=null&&(B.underline=v);v=qO(z,"et");v!=null&&(B.charEdgeStyle=v);v=qO(z,"of");v!=null&&(B.offset=v);v=lt(z,"bc");v!=null&&(B.background=v);v=lt(z,"ec");v!=null&&(B.KV=v);v=lt(z,"fc");v!=null&&(B.color=v);v=qO(z,"fs");v!=null&&v!==0&&(B.fontFamily=v);v=Hh(z,"sz");v!==void 0&&(B.fontSizeIncrement=v/100-1);v=Hh(z,"bo");v!==void 0&&(B.backgroundOpacity=v/255);v=Hh(z,"fo");v!==void 0&&(B.textOpacity=v/255);v=qO(z,"rb");v!=null&&v!==10&&
v!==0&&(B.pz=v>10?v-1:v);z=qO(z,"hg");z!=null&&(B.hc=z);t[f]=B;break;case "ws":f=z.getAttribute("id");this.N[f]=MU5(this,z);break;case "wp":f=z.getAttribute("id"),this.D[f]=pv5(this,z)}if(p){M=[];p=Array.from(p.childNodes);p=g.a(p);for(z=p.next();!z.done;z=p.next())if(z=z.value,z.nodeType===1)switch(z.tagName){case "w":this.S=tUT(this,z,K,!1);(z=this.G[this.S.id])&&z.end>this.S.start&&(z.end=this.S.start);this.G[this.S.id]=this.S;M.push(this.S);break;case "p":var I=z;v=K;f=[];t=I.getAttribute("w")||
this.C;B=!!QZ(I,"a");v=(Hh(I,"t")||0)+v;var G=Hh(I,"d")||5E3;B||(!this.W&&this.Y&&this.Y.windowId===t&&this.Y.end>v&&(this.Y.end=v),this.Y&&this.Y.text==="\n"&&(this.Y.text=""));var b=B?6:5,e=I.getAttribute("p");e=e?this.pens[e]:null;var w=Array.from(I.childNodes);w.length&&(this.W=I.getAttribute("d")!=null);for(I=0;I<w.length;I++){var D=w[I],y=void 0;I>0&&(B=!0);var R=void 0;D.nodeType===1&&(R=D);if(R&&R.tagName==="s"){if((D=(D=R.getAttribute("p"))?this.pens[D]:null)&&D.pz&&(D.pz===1?(D=w.slice(I,
I+4),D.length===4&&(y=$r7(v,G,t,B,b,D,this.pens),I+=3)):y=$r7(v,G,t,B,b,[R],this.pens)),!y){var S=R;y=v;R=G;D=t;var E=B,L=b,q=S.textContent?S.textContent:"",V=S.getAttribute("p");V=V?this.pens[V]:null;S=Hh(S,"t")||0;y=new St(y+S,R-S,L,D,q,E,V)}}else y=new St(v,G,b,t,D.textContent||"",B,e);f.push(y);this.Y=y}if(f.length>0)for(f[0].windowId===this.C&&(this.S=tUT(this,z,K,!0),M.push(this.S)),z=g.a(f),f=z.next();!f.done;f=z.next())f=f.value,f.windowId=this.S.id,this.S.S.push(f),M.push(f)}K=M}else K=[];
return K};var Oe5=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.h(VZ,ut);VZ.prototype.reset=function(){this.Y.clear()};
VZ.prototype.T=function(z,K){var f=JSON.parse(z);if(!f)return[];if(f.pens){z=0;for(var M=g.a(f.pens),p=M.next();!p.done;p=M.next()){p=p.value;var t={},B=p.pParentId;B&&Object.assign(t,this.S.get(B));p.bAttr&&(t.bold=!0);p.iAttr&&(t.italic=!0);p.uAttr&&(t.underline=!0);B=p.ofOffset;B!=null&&(t.offset=B);p.szPenSize!==void 0&&(t.fontSizeIncrement=p.szPenSize/100-1);B=p.etEdgeType;B!=null&&(t.charEdgeStyle=B);p.ecEdgeColor!==void 0&&(t.KV=nk(p.ecEdgeColor));B=p.fsFontStyle;B!=null&&B!==0&&(t.fontFamily=
B);p.fcForeColor!==void 0&&(t.color=nk(p.fcForeColor));p.foForeAlpha!==void 0&&(t.textOpacity=p.foForeAlpha/255);p.bcBackColor!==void 0&&(t.background=nk(p.bcBackColor));p.boBackAlpha!==void 0&&(t.backgroundOpacity=p.boBackAlpha/255);(B=p.rbRuby)&&B!==10&&(t.pz=B>10?B-1:B,t.textEmphasis=Oe5.get(t.pz));p.hgHorizGroup&&(t.hc=p.hgHorizGroup);this.S.set(z++,t)}}if(f.wsWinStyles)for(z=0,M=g.a(f.wsWinStyles),p=M.next();!p.done;p=M.next())p=p.value,t={},(B=p.wsParentId)?Object.assign(t,this.C.get(B)):Object.assign(t,
this.W),p.mhModeHint!==void 0&&(t.Ke=p.mhModeHint),p.juJustifCode!==void 0&&(t.textAlign=p.juJustifCode),p.pdPrintDir!==void 0&&(t.F2=p.pdPrintDir),p.sdScrollDir!==void 0&&(t.mH=p.sdScrollDir),p.wfcWinFillColor!==void 0&&(t.windowColor=nk(p.wfcWinFillColor)),p.wfoWinFillAlpha!==void 0&&(t.windowOpacity=p.wfoWinFillAlpha/255),this.C.set(z++,t);if(f.wpWinPositions)for(z=0,M=g.a(f.wpWinPositions),p=M.next();!p.done;p=M.next())p=p.value,t={},(B=p.wpParentId)&&Object.assign(t,this.J.get(B)),p.ahHorPos!==
void 0&&(t.IL=p.ahHorPos),p.apPoint!==void 0&&(t.J0=p.apPoint),p.avVerPos!==void 0&&(t.hd=p.avVerPos),p.ccCols!==void 0&&(t.aD=p.ccCols),p.rcRows!==void 0&&(t.xQ=p.rcRows),this.J.set(z++,t);if(f.events){z=[];f=g.a(f.events);for(M=f.next();!M.done;M=f.next()){var v=M.value;p=(v.tStartMs||0)+K;t=v.dDurationMs||0;if(v.id)B=String(v.id),M=B4S(this,v,p,t,B),z.push(M),this.Y.set(B,M);else{v.wWinId?B=v.wWinId.toString():(B="_"+EC++,M=B4S(this,v,p,t,B),z.push(M),this.Y.set(B,M));M=z;var I=v;t===0&&(t=5E3);
v=this.Y.get(B);var G=!!I.aAppend,b=G?6:5,e=I.segs,w=null;I.pPenId&&(w=this.S.get(I.pPenId));for(I=0;I<e.length;I++){var D=e[I],y=D.utf8;if(y){var R=D.tOffsetMs||0,S=null;D.pPenId&&(S=this.S.get(D.pPenId));if((v.params.Ke!=null?v.params.Ke:v.S.length>1?1:0)===2&&G&&y==="\n")continue;D=null;var E=[],L;if(L=S&&S.pz===1){L=e;var q=I;if(q+3>=L.length||!L[q+1].pPenId||!L[q+2].pPenId||!L[q+3].pPenId)L=!1;else{var V=L[q+1].pPenId;(V=this.S.get(V))&&V.pz&&V.pz===2?(V=L[q+2].pPenId,V=this.S.get(V),!V||!V.pz||
V.pz<3?L=!1:(V=L[q+3].pPenId,L=(V=this.S.get(V))&&V.pz&&V.pz===2?!0:!1)):L=!1}}if(L)R=e[I+1].utf8,D=e[I+3].utf8,L=e[I+2].utf8,q=this.S.get(e[I+2].pPenId),y=Km4(y,R,L,D,q),D=new St(p,t,b,B,y,G,S),I+=3;else{if(y.indexOf("<")>-1){var c=void 0;E=S;L=w;q=p;V=t;var O=R,x=b,T=G,M8=[],$S=g.C7("<html>"+y+"</html>");if(!$S.getElementsByTagName("parsererror").length&&((c=$S.firstChild)==null?0:c.childNodes.length))for(c=g.a($S.firstChild.childNodes),$S=c.next();!$S.done;$S=c.next()){$S=$S.value;var td=void 0,
r=void 0,yI=(r=(td=$S.textContent)==null?void 0:td.replace(/\n/g,""))!=null?r:"";if($S.nodeType!==3||yI&&yI.match(/^ *$/)==null){td={};Object.assign(td,E||L);r=void 0;switch((r=$S)==null?void 0:r.tagName){case "b":td.bold=!0;break;case "i":td.italic=!0;break;case "u":td.underline=!0}M8.push(new St(q+O,V-O,x,v.id,yI,T,td))}}E=M8}E.length||(E=[new St(p+R,t-R,b,v.id,y,G,S||w)])}if(E.length)for(G=g.a(E),S=G.next();!S.done;S=G.next())S=S.value,M.push(S),v.S.push(S);else D&&(M.push(D),v.S.push(D))}G=!0}}}K=
z}else K=[];return K};g.h(Wh,g.u$);Wh.prototype.bY=function(z,K,f){bFQ(this.videoData.videoId,z.vssId,f.jX)};
Wh.prototype.bT=function(z){if(this.audioTrack)for(var K=g.a(this.audioTrack.captionTracks),f=K.next();!f.done;f=K.next())g.SE(this.Y,f.value);z.ij()};g.h(J9,bt);J9.prototype.pV=function(z){var K=this.Y.S;bt.prototype.pV.call(this,z);for(z=z.length;z<K.length;z++){var f=K[z];if(t&&f.S===p)var M=t;else{M={};Object.assign(M,f.S);Object.assign(M,roZ);var p=f.S;var t=M}WtZ(this,f,M)}};
var roZ={nP:!0};g.h(g$,zXT);g$.prototype.J=function(z,K,f,M,p){if(f<M){var t="_"+EC++;f=f/1E3-this.W;M=M/1E3-this.W;z=new Lk(f,M-f,5,t,{textAlign:0,J0:0,IL:K*2.5,hd:z*5.33});p=new St(f,M-f,5,t,p);this.Y.push(z);this.Y.push(p)}};
g.h(ch,ut);ch.prototype.T=function(z){z=new g$(z,z.byteLength,this.Y);if(N4T(z)){for(;z.byteOffset<z.S.byteLength;)for(z.version===0?z.T=d$(z)*(1E3/45):z.version===1&&(z.T=d$(z)*4294967296+d$(z)),z.C=it(z);z.C>0;z.C--){var K=it(z),f=it(z),M=it(z);K&4&&(K&3)===this.track&&(this.track===0||this.track===1)&&(K=this.S,K.S.push({time:z.T,type:this.track,Y_:f,lw:M,order:K.S.length}))}ACS(this.S,z);return z.Y}return[]};
ch.prototype.reset=function(){this.S.clear()};g.h(sC,bt);g.k=sC.prototype;g.k.UR=function(){g.pl(this.nI)};
g.k.mS=function(){this.element.removeEventListener("transitionend",this.mS,!1);g.Dz(this.element,"ytp-rollup-mode");this.Zr(this.Ft,!0)};
g.k.eP=function(){return this.T?this.Y1:this.N};
g.k.xt=function(){return this.T?this.N:this.Y1};
g.k.Zr=function(z,K){this.Ft=z;if(this.Y.params.xQ){for(var f=0,M=0;M<this.G.length&&f<z.length;M++)this.G[M]===z[f]&&f++;f>0&&f<z.length&&(z=this.G.concat(z.slice(f)));this.TP=this.Y1;this.N=this.Y1=0;bt.prototype.Zr.call(this,z);beZ(this,K)}bt.prototype.Zr.call(this,z)};eXo.prototype.unload=function(){this.S!=null&&(this.U.removeEventListener("sabrCaptionsDataLoaded",this.S),this.S=null);this.z5=[];this.U.publish("sabrCaptionsBufferedRangesUpdated",this.z5)};
eXo.prototype.gr=function(z){return{formatId:g.Nh(z.info.S.info,this.CI),Ia:z.info.Ia+(this.CI?0:1),startTimeMs:z.info.J*1E3,durationMs:z.info.G*1E3}};g.h(kz2,g.u$);g.k=kz2.prototype;g.k.bY=function(z,K,f){this.cg();K=z.getId();K=K!=null&&K in this.S.S?this.S.S[K]:null;K||(K=z.languageCode,K=this.S.isManifestless?aDS(this,K,"386"):aDS(this,K));K&&(this.T=z,this.W=K,yo1(this.G,f),this.U.publish("sabrCaptionsTrackChanged",g.Nh(K.info,this.S.CI)))};
g.k.bT=function(z){var K=this.S.isManifestless?hX9(this,"386"):hX9(this);K=g.a(K);for(var f=K.next();!f.done;f=K.next())g.SE(this.Y,f.value);z.ij()};
g.k.cg=function(){this.T&&(this.T=this.W=null,this.G.unload(),this.U.publish("sabrCaptionsTrackChanged",null))};
g.k.vD=function(){return""};
g.k.Q4=function(){this.U.GE("captions")};var uOf="WEBVTT".split("").map(function(z){return z.charCodeAt(0)});
g.h(SWT,ut);
SWT.prototype.T=function(z,K){z instanceof ArrayBuffer&&(z=g.dz(new Uint8Array(z)));var f=[];z=z.split(Ze9);for(var M=1;M<z.length;M++){var p=z[M],t=K;if(p!==""&&!opS.test(p)){var B=C6S.exec(p);if(B&&B.length>=4){var v=P6p(B[1]),I=P6p(B[2])-v;v+=t;var G=(B=B[3])?B.split(" "):[];B={};var b=null;var e="";var w=null,D="";G=g.a(G);for(var y=G.next();!y.done;y=G.next())if(y=y.value.split(":"),y.length===2){var R=y[1];switch(y[0]){case "line":y=R.split(",");y[0].endsWith("%")&&(b=y[0],B.hd=Number.parseInt(b,
10),y.length===2&&(e=y[1].trim()));break;case "position":y=R.split(",");w=y[0];B.IL=Number.parseInt(w,10);y.length===2&&(D=y[1].trim());break;case "align":switch(R){case "start":B.textAlign=0;break;case "middle":B.textAlign=2;break;case "end":B.textAlign=1}}}b||e||(e="end");if(!w)switch(B.textAlign){case 0:B.IL=0;break;case 1:B.IL=100;break;case 2:B.IL=50}if(B.textAlign!=null){b=0;switch(e){case "center":b+=3;break;case "end":b+=6;break;default:b+=0}switch(D){case "line-left":b+=0;break;case "center":b+=
1;break;case "line-right":b+=2;break;default:switch(B.textAlign){case 0:b+=0;break;case 2:b+=1;break;case 1:b+=2}}e=b<0||b>8?7:b;B.J0=e}p=p.substring(C6S.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");D=B;B=p;p={};if(B.indexOf("<")<0&&B.indexOf("&")<0)t=HeS(v,I,5,D),I=new St(v,I,5,t.id,B,!1,g.U9(p)?void 0:p),f.push(t),f.push(I),t.S.push(I);else for(e=B.split(T4f),e.length===1?(B=5,D=HeS(v,I,B,D)):(b=B=6,D=Object.assign({aD:32},D),D=new Lk(v,I,b,"_"+EC++,D)),f.push(D),b=v,w=0;w<e.length;w++)G=e[w],
w%2===0?(y=g.C7("<html>"+G+"</html>"),y.getElementsByTagName("parsererror").length?(R=y.createElement("span"),R.appendChild(y.createTextNode(G))):R=y.firstChild,Ep7(this,b,I-(b-v),B,D,w>0,R,p,f)):b=P6p(G)+t}C6S.lastIndex=0}}return f};
var opS=/^NOTE/,Ze9=/(?:\r\n|\r|\n){2,}/,C6S=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),T4f=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.h(A9,g.J);A9.prototype.clear=function(){this.S&&this.S.dispose();this.S=null};
A9.prototype.reset=function(){this.S&&this.S.reset()};
A9.prototype.JL=function(){g.J.prototype.JL.call(this);this.clear()};var oH={windowColor:"#080808",windowOpacity:0,textAlign:2,J0:7,IL:50,hd:100,isDefault:!0,l3:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.h(Wmp,g.R5);g.k=Wmp.prototype;g.k.JL=function(){if(this.C||this.Hx){var z=this.U.qL();z&&!z.CH()&&z.NJ()}else Fmp(this,!1);g.R5.prototype.JL.call(this)};
g.k.As=function(){return this.SV.B("html5_honor_caption_availabilities_in_audio_track")&&this.J!=="LIVE"&&this.J!=="SABR_LIVE"};
g.k.F7=function(){if(this.b_)return this.C||this.Hx;var z=this.getAudioTrack();if(this.As()){if(!z.captionTracks.length)return!1;if(!this.Y)return!0}z=N58(z,g.$t(this.SV));return z==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:z==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?jt(this):gp9(this)||jt(this)?!0:ie5(this)};
g.k.load=function(){g.R5.prototype.load.call(this);this.N=this.getAudioTrack();if(this.Y)this.S&&(this.VE.clear(),this.C?coo(this,!0):this.player.getPresentingPlayerType()!==3&&this.Y.bY(this.S,"json3",this.nI),this.C||this.Hx||x1(this)||this.player.rO("captionschanged",g.S1(this.S)));else{var z;this.J==="OFFLINE"?z=new Wh(this.player,this.videoData,this.getAudioTrack()):this.J==="SABR_LIVE"?z=new kz2(this.videoData.S,this.player):this.J==="LIVE"?z=new GK(this.videoData.S,this.player):this.J==="INNERTUBE"?
z=new g.LK(this.player,this.videoData,this.getAudioTrack()):z=new g.Pu(this.player,this.videoData.C3,this.videoData.videoId,g.gcW(this.videoData),this.videoData.r_,this.videoData.eventId);this.Y=z;g.d(this,this.Y);this.Y.bT(this.nI)}};
g.k.unload=function(){this.C&&this.S?coo(this,!1):(this.Px&&g.tU(this.Px),this.player.GE("captions"),this.Bx=[],this.Y&&this.Y.cg(),this.VE.clear(),this.Y1&&this.player.St(this.Y1),this.Ze());g.R5.prototype.unload.call(this);this.player.uO();this.player.rO("captionschanged",{})};
g.k.create=function(){this.F7()&&this.load();var z;a:{var K,f,M;if(this.SV.B("web_player_nitrate_promo_tooltip")&&((K=this.videoData.getPlayerResponse())==null?0:(f=K.captions)==null?0:(M=f.playerCaptionsTracklistRenderer)==null?0:M.enableTouchCaptionsNitrate)){var p,t;if(K=(z=this.videoData.getPlayerResponse())==null?void 0:(p=z.captions)==null?void 0:(t=p.playerCaptionsTracklistRenderer)==null?void 0:t.captionTracks)for(z=g.a(K),p=z.next();!p.done;p=z.next())if(p=p.value,p.kind==="asr"&&p.languageCode===
"en"){z=!0;break a}}z=!1}z&&this.U.publish("showpromotooltip",this.D.element)};
g.k.ij=function(){var z=N58(this.player.getAudioTrack(),g.$t(this.SV));var K=z==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Xw(this,this.W):z==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&jt(this)?Y1(this):gp9(this)||this.W||ie5(this)?Xw(this,this.W):jt(this)?Y1(this):null;if(this.C||this.Hx){var f=g.MN(this.Y.Y,!0);z=[];for(var M=0;M<f.length;M++){var p=f[M],t=g.zi("TRACK");t.setAttribute("kind","subtitles");t.setAttribute("label",g.RB(p));t.setAttribute("srclang",g.u1(p));t.setAttribute("id",p.toString());
this.Hx||t.setAttribute("src",this.Y.vD(p,"vtt"));p===K&&t.setAttribute("default","1");z.push(t)}K=this.U.qL();K.GT(z);z=K.H1();this.SE&&this.eV.X(z.textTracks,"change",this.Ivc)}else!this.S&&K&&Zr(this,K),this.player.rO("onCaptionsTrackListChanged"),this.player.IX("onApiChange")};
g.k.Ivc=function(){for(var z=this.U.qL().H1().textTracks,K=null,f=0;f<z.length;f++)if(z[f].mode==="showing")a:{K=g.MN(this.Y.Y,!0);for(var M=0;M<K.length;M++)if(K[M].toString()===z[f].id){K=K[M];break a}K=null}(this.loaded?this.S:null)!==K&&Zr(this,K,!0)};
g.k.wmE=function(){!this.S&&this.C||this.unload()};
g.k.jX=function(z,K,f,M){if(z){var p;sWH(this,(p=this.S)!=null?p:void 0);this.SV.B("html5_sends_cfs_after_caption_loaded")&&r$(this,null,this.S,this.W,x1(this));this.Y.Nx()&&(this.Bx=[],this.U.GE("captions"),vh(this.vx),this.VE.reset());a:{p=this.VE;M=M||0;f=qWS(p,z,f||0);z=[];try{for(var t=g.a(f),B=t.next();!B.done;B=t.next()){var v=B.value,I=v.trackData,G=v.i6,b=p.SV.B("safari_live_drm_captions_fix");if(typeof I!=="string"){f=z;var e=f.concat;if(b&&Lm7(I))var w=mrQ(p,I,G);else{var D=p,y=K,R=I,S=
G,E=M;if(!vpQ(R))throw Error("Invalid binary caption track data");D.S||(D.S=new ch(E,y));w=D.S.T(R,S)}var L=e.call(f,w)}else{if(I.substring(0,6)==="WEBVTT")var q=z.concat(mrQ(p,I,G));else{f=z;var V=f.concat;b:{y=D=void 0;R=p;S=K;if(I[0]==="{")try{R.S||(R.S=new VZ(lD_(S)));var c=y=R.S.T(I,G);break b}catch(r){g.sm(r);c=[];break b}var O=g.C7(I);if(!O||!O.firstChild){var x=Error("Invalid caption track data");x.params=I;throw x;}if(O.firstChild.tagName==="timedtext"){if(Number(O.firstChild.getAttribute("format"))===
3){R.S||(R.S=new Ph(lD_(S),R.SV));c=D=R.S.T(O,G);break b}var T=Error("Unsupported subtitles format in web player (Format2)");T.params=I;throw T;}if(O.firstChild.tagName==="transcript"){var M8=Error("Unsupported subtitles format in web player (Format1)");M8.params=I;throw M8;}var $S=Error("Invalid caption track data");$S.params=I;throw $S;}q=V.call(f,c)}L=q}z=L}var td=z;break a}catch(r){p.logger.S(187101178,"Captions parsing failed: "+r.message+". ");p.clear();td=[];break a}td=void 0}K=td;this.SV.B("html5_sends_cfs_after_caption_parsed")&&
!this.SV.B("html5_sends_cfs_after_caption_loaded")&&K.length>0&&r$(this,null,this.S,this.W,x1(this));td=!this.SV.B("html5_keep_caption_data_after_seek")&&(this.J==="LIVE"||this.J==="SABR_LIVE");this.player.St(K,void 0,td);!this.W||this.Hx||x1(this)||g.iY(this.SV)||g.jo(this.SV)||g.O$(this.SV)||this.SV.eV==="shortspage"||this.player.isInline()||(g.tU(this.Px),K=fD9({J0:0,IL:5,hd:5,xQ:2,textAlign:0,F2:0,lang:"fr"}),this.Xc=[K],td=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."],this.rE||(t=
new g.kl(g.dM()),g.d(this,t),this.rE=t.element),t=K.end-K.start,(B=g.RB(this.S))&&this.Xc.push(new St(K.start,t,0,K.id,B)),this.Xc.push(new St(K.start,t,0,K.id,td[0]),new St(K.start,t,0,K.id,this.rE,!0),new St(K.start,t,0,K.id,td[1],!0)),this.player.St(this.Xc),g.$4(this.Px));!this.W||this.Hx||x1(this)||(g.$t(this.SV)?Fw(this,!0):OC(this,!0),this.N&&(this.N.J=this.S),this.player.uO());this.W=!1}};
g.k.onCueRangeEnter=function(z){this.Bx.push(z);vh(this.vx)};
g.k.onCueRangeExit=function(z){g.R8(this.Bx,z);this.Y instanceof GK&&this.Y.G&&this.player.gL([z]);vh(this.vx)};
g.k.getCaptionWindowContainerId=function(){return this.D.element.id};
g.k.mTa=function(){xr1(this,this.Xc);this.Xc=null};
g.k.a4=function(){var z=this;if(!this.TP||!this.C){this.vx.stop();g.Jdo(this.QE);this.Bx.sort(g.eN);var K=this.Bx;if(this.Y1){var f=g.ds(K,function(t){return this.Y1.indexOf(t)===-1},this);
f.length&&(K=f)}K=g.a(K);for(f=K.next();!f.done;f=K.next())jWp(this,f.value);K=g.a(Object.entries(this.nH));var M=K.next();for(f={};!M.done;f={sA:void 0,fG:void 0},M=K.next()){var p=g.a(M.value);M=p.next().value;p=p.next().value;f.sA=M;f.fG=p;this.QE[f.sA]?(f.fG.element.parentNode||(f.fG instanceof sC||f.fG instanceof J9||g.xf(this.nH,function(t){return function(B,v){v!==t.sA&&B.Y.params.J0===t.fG.Y.params.J0&&B.Y.params.IL===t.fG.Y.params.IL&&B.Y.params.hd===t.fG.Y.params.hd&&(B.dispose(),delete z.nH[v]);
return v===t.sA}}(f),this),this.D.element.appendChild(f.fG.element)),f.fG.Zr(this.QE[f.sA])):(f.fG.dispose(),delete this.nH[f.sA])}}};
g.k.GwV=function(){npf(this,{},!0);this.player.rO("captionssettingschanged")};
g.k.hN=function(){var z=oH.l3;z={background:z.background,backgroundOpacity:z.backgroundOpacity,charEdgeStyle:z.charEdgeStyle,color:z.color,fontFamily:z.fontFamily,fontSizeIncrement:z.fontSizeIncrement,fontStyle:z.bold&&z.italic?3:z.bold?1:z.italic?2:0,textOpacity:z.textOpacity,windowColor:oH.windowColor,windowOpacity:oH.windowOpacity};var K=kAZ()||{};K.background!=null&&(z.background=K.background);K.backgroundOverride!=null&&(z.backgroundOverride=K.backgroundOverride);K.backgroundOpacity!=null&&(z.backgroundOpacity=
K.backgroundOpacity);K.backgroundOpacityOverride!=null&&(z.backgroundOpacityOverride=K.backgroundOpacityOverride);K.charEdgeStyle!=null&&(z.charEdgeStyle=K.charEdgeStyle);K.charEdgeStyleOverride!=null&&(z.charEdgeStyleOverride=K.charEdgeStyleOverride);K.color!=null&&(z.color=K.color);K.colorOverride!=null&&(z.colorOverride=K.colorOverride);K.fontFamily!=null&&(z.fontFamily=K.fontFamily);K.fontFamilyOverride!=null&&(z.fontFamilyOverride=K.fontFamilyOverride);K.fontSizeIncrement!=null&&(z.fontSizeIncrement=
K.fontSizeIncrement);K.fontSizeIncrementOverride!=null&&(z.fontSizeIncrementOverride=K.fontSizeIncrementOverride);K.fontStyle!=null&&(z.fontStyle=K.fontStyle);K.fontStyleOverride!=null&&(z.fontStyleOverride=K.fontStyleOverride);K.textOpacity!=null&&(z.textOpacity=K.textOpacity);K.textOpacityOverride!=null&&(z.textOpacityOverride=K.textOpacityOverride);K.windowColor!=null&&(z.windowColor=K.windowColor);K.windowColorOverride!=null&&(z.windowColorOverride=K.windowColorOverride);K.windowOpacity!=null&&
(z.windowOpacity=K.windowOpacity);K.windowOpacityOverride!=null&&(z.windowOpacityOverride=K.windowOpacityOverride);return z};
g.k.T1=function(z,K){var f={};Object.assign(f,kAZ());Object.assign(f,z);npf(this,f,K);this.player.rO("captionssettingschanged")};
g.k.Ze=function(){!this.C&&this.loaded&&(g.jS(this.nH,function(z,K){z.dispose();delete this.nH[K]},this),this.a4())};
g.k.Lo=function(z,K){switch(z){case "fontSize":if(isNaN(K))break;z=g.qt(K,-2,4);this.T1({fontSizeIncrement:z});return z;case "reload":K&&!this.C&&Zr(this,this.S,!0);break;case "stickyLoading":K!==void 0&&this.SV.D&&(g.$t(this.SV)?Fw(this,!!K):OC(this,!!K));break;case "track":return Xv7(this,K);case "tracklist":return this.Y?g.UZ(g.MN(this.Y.Y,!(!K||!K.includeAsr)),function(f){return g.S1(f)}):[];
case "translationLanguages":return this.Y?this.Y.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||K===void 0||Fmp(this,!!K);break;case "sampleSubtitlesCustomized":this.C||Fmp(this,!!K,K);break;case "recommendedTranslationLanguages":return g.zF();case "defaultTranslationSourceTrackIndices":return this.Y?this.Y.D:[]}};
g.k.getOptions=function(){var z="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.SV.D&&z.push("stickyLoading");return z};
g.k.PX=function(){var z=this.S;if(this.U.o3("captions")){if(this.SV.B("html5_modify_caption_vss_logging")){var K;return(z=(K=this.videoData.Ax)!=null?K:null)?{cc:g.ziv(z)}:{}}if(z)return K=z.vssId,z.translationLanguage&&K&&(K="t"+K+"."+g.u1(z)),{cc:K}}return{}};
g.k.g9L=function(){this.isSubtitlesOn()?(g.$t(this.SV)?Fw(this,!1):OC(this,!1),sWH(this),Zr(this,null,!0)):this.Fn()};
g.k.Fn=function(){var z=x1(this)||!this.S?Xw(this,!0):this.S;z&&this.uI(z.vssId,"m");this.isSubtitlesOn()||Zr(this,x1(this)||!this.S?Xw(this,!0):this.S,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.S&&!x1(this)};
g.k.khe=function(){var z=x1(this);jt(this,z)?Zr(this,this.getAudioTrack().S,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.As()&&(this.W=!1,this.S=null,this.Y&&(this.Y.dispose(),this.Y=null)),this.F7()&&(z?Zr(this,Xw(this,!1),!1):this.load()))};
g.k.rd=function(z){z&&(this.l_={top:z.top,right:z.right,bottom:z.bottom,left:z.left,width:1-z.left-z.right,height:1-z.top-z.bottom},this.D.element.style.top=this.l_.top*100+"%",this.D.element.style.left=this.l_.left*100+"%",this.D.element.style.width=this.l_.width*100+"%",this.D.element.style.height=this.l_.height*100+"%",this.D.element.style.position="absolute",z=YW8(this))&&(this.D.element.style.width=z.width+"px",this.D.element.style.height=z.height+"px")};
g.k.onVideoDataChange=function(z,K){z==="newdata"&&(this.videoData=K,this.loaded&&this.unload(),this.W=!1,this.S=null,this.Y&&(this.Y.dispose(),this.Y=null,this.player.rO("captionschanged",{})),this.F7()&&this.load())};
g.k.getAudioTrack=function(){return this.player.getAudioTrack()};
g.k.P8f=function(){var z=this.U.qL();z&&!z.CH()&&z.NJ();this.U.isFullscreen()?(this.C=this.b_=!0,this.loaded&&this.ij()):(this.b_=this.SV.controlsType==="3",this.C=VUp(this));Zr(this,this.S)};
g.k.j2=function(){var z,K,f,M=(z=this.videoData.getPlayerResponse())==null?void 0:(K=z.captions)==null?void 0:(f=K.playerCaptionsTracklistRenderer)==null?void 0:f.openTranscriptCommand;M&&this.player.LH("innertubeCommand",M)};
g.k.uW=function(z,K,f){var M=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,p="";z&&(p=z.vssId,p=p.replace(M,""));var t="";z&&z.getId()&&(t=z.getId()||"");z&&z.getXtags()&&(z=z.getXtags(),z=z.replace(M,""),t=t.concat(";"+z));this.U.uW(K?p:"",K?t:"",f)};
g.k.uI=function(z,K){z=(z||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");z.length>0&&this.U.uI(z,K)};
g.k.Q4=function(){this.Y&&this.Y.Q4()};g.a5("captions",Wmp);})(_yt_player);
