(function(g){var window=this;'use strict';var LHZ=function(z){z.publish("autonavvisibility")},EEo=function(z,K){z.LH("onAutonavCoundownStarted",K)},Pdo=function(z){var K,f,M;
return z==null?void 0:(K=z.playerOverlays)==null?void 0:(f=K.playerOverlayRenderer)==null?void 0:(M=f.autoplay)==null?void 0:M.playerOverlayAutoplayRenderer},MV=function(z,K,f){g.k4(z.element,"ytp-suggestion-set",!!K.videoId);
var M=K.playlistId;f=K.JJ(f?f:"mqdefault.jpg");var p=null,t=null;K instanceof g.l1&&(K.lengthText?(p=K.lengthText||null,t=K.Ox||null):K.lengthSeconds&&(p=g.nd(K.lengthSeconds),t=g.nd(K.lengthSeconds,!0)));var B=!!M;M=B&&g.qR(M).type==="RD";var v=K instanceof g.l1?K.isLivePlayback:null,I=K instanceof g.l1?K.isUpcoming:null,G=K.author,b=K.shortViewCount,e=K.publishedTimeText,w=[],D=[];G&&w.push(G);b&&(w.push(b),D.push(b));e&&D.push(e);f={title:K.title,author:G,author_and_views:w.join(" \u2022 "),aria_label:K.ariaLabel||
g.Pt("Regarder $TITLE",{TITLE:K.title}),duration:p,timestamp:t,url:K.xv(),is_live:v,is_upcoming:I,is_list:B,is_mix:M,background:f?"background-image: url("+f+")":"",views_and_publish_time:D.join(" \u2022 "),autoplayAlternativeHeader:K.wx};K instanceof g.mr&&(f.playlist_length=K.playlistLength);z.update(f)},p4=function(z){var K=z.Z(),f=K.J;
g.F.call(this,{j:"a",K:"ytp-autonav-suggestion-card",V:{href:"{{url}}",target:f?K.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},L:[{j:"div",Wx:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],V:{style:"{{background}}"},L:[{j:"div",V:{"aria-label":"{{timestamp}}"},Wx:["ytp-autonav-timestamp"],qc:"{{duration}}"},{j:"div",Wx:["ytp-autonav-live-stamp"],qc:"En direct"},
{j:"div",Wx:["ytp-autonav-upcoming-stamp"],qc:"\u00c0 venir"},{j:"div",K:"ytp-autonav-list-overlay",L:[{j:"div",K:"ytp-autonav-mix-text",qc:"Mix"},{j:"div",K:"ytp-autonav-mix-icon"}]}]},{j:"div",Wx:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],qc:"{{title}}"},{j:"div",Wx:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],qc:"{{author}}"},{j:"div",Wx:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],qc:"{{views_and_publish_time}}"}]});this.U=
z;this.suggestion=null;this.S=f;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},tF=function(z,K){K=K===void 0?!1:K;
g.F.call(this,{j:"div",K:"ytp-autonav-endscreen-countdown-overlay"});var f=this;this.G=K;this.cancelCommand=this.W=void 0;this.T=0;this.container=new g.F({j:"div",K:"ytp-autonav-endscreen-countdown-container"});g.d(this,this.container);this.container.hL(this.element);K=z.Z();var M=K.J;this.U=z;this.suggestion=null;this.onVideoDataChange("newdata",this.U.getVideoData());this.X(z,"videodatachange",this.onVideoDataChange);this.S=new g.F({j:"div",K:"ytp-autonav-endscreen-upnext-container",V:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},L:[{j:"div",K:"ytp-autonav-endscreen-upnext-header"},{j:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",qc:"{{autoplayAlternativeHeader}}"},{j:"a",K:"ytp-autonav-endscreen-link-container",V:{href:"{{url}}",target:M?K.N:""},L:[{j:"div",K:"ytp-autonav-endscreen-upnext-thumbnail",V:{style:"{{background}}"},L:[{j:"div",V:{"aria-label":"{{timestamp}}"},Wx:["ytp-autonav-timestamp"],
qc:"{{duration}}"},{j:"div",Wx:["ytp-autonav-live-stamp"],qc:"En direct"},{j:"div",Wx:["ytp-autonav-upcoming-stamp"],qc:"\u00c0 venir"}]},{j:"div",K:"ytp-autonav-endscreen-video-info",L:[{j:"div",K:"ytp-autonav-endscreen-premium-badge"},{j:"div",K:"ytp-autonav-endscreen-upnext-title",qc:"{{title}}"},{j:"div",K:"ytp-autonav-endscreen-upnext-author",qc:"{{author}}"},{j:"div",K:"ytp-autonav-view-and-date",qc:"{{views_and_publish_time}}"},{j:"div",K:"ytp-autonav-author-and-view",qc:"{{author_and_views}}"}]}]}]});
g.d(this,this.S);this.S.hL(this.container.element);M||this.X(this.S.dE("ytp-autonav-endscreen-link-container"),"click",this.vG);this.U.createClientVe(this.container.element,this,115127);this.U.createClientVe(this.S.dE("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.F({j:"div",K:"ytp-autonav-overlay"});g.d(this,this.overlay);this.overlay.hL(this.container.element);this.Y=new g.F({j:"div",K:"ytp-autonav-endscreen-button-container"});g.d(this,this.Y);this.Y.hL(this.container.element);
this.cancelButton=new g.F({j:"button",Wx:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",K.B("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],V:{"aria-label":"Annuler la lecture automatique"},qc:"Annuler"});g.d(this,this.cancelButton);this.cancelButton.hL(this.Y.element);this.cancelButton.listen("click",this.xE,this);this.U.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.F({j:"a",Wx:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",K.B("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],V:{href:"{{url}}",role:"button","aria-label":"Lire la vid\u00e9o suivante"},qc:"Regarder"});g.d(this,this.playButton);this.playButton.hL(this.Y.element);this.playButton.listen("click",this.vG,this);this.U.createServerVe(this.playButton.element,this.playButton,!0);(K=this.U.getVideoData())&&Hj2(this,K);this.J=new g.Kl(function(){QtH(f)},500);
g.d(this,this.J);this.WG();this.X(z,"autonavvisibility",this.WG);this.U.B("web_autonav_color_transition")&&(this.X(z,"autonavchange",this.HO),this.X(z,"onAutonavCoundownStarted",this.bHL))},BH=function(z){var K=z.U.hD(!0,z.U.isFullscreen());
g.k4(z.container.element,"ytp-autonav-endscreen-small-mode",z.wI(K));g.k4(z.container.element,"ytp-autonav-endscreen-is-premium",!!z.suggestion&&!!z.suggestion.q1V);g.k4(z.U.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!z.U.US());g.k4(z.U.getRootNode(),"countdown-running",z.Wc());g.k4(z.container.element,"ytp-player-content",z.U.US());g.H6(z.overlay.element,{width:K.width+"px"});if(!z.Wc()){z.U.US()?qfp(z,Math.round(mDT(z)/1E3)):qfp(z);K=!!z.suggestion&&!!z.suggestion.wx;var f=z.U.US()||
!K;g.k4(z.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!f&&K);g.k4(z.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",f&&!K);z.Y.s3(z.U.US());g.k4(z.element,"ytp-enable-w2w-color-transitions",lO7(z))}},QtH=function(z){var K=mDT(z),f=Math,M=f.min;
var p=z.T?Date.now()-z.T:0;f=M.call(f,p,K);qfp(z,Math.ceil((K-f)/1E3));K-f<=500&&z.Wc()?z.select(!0):z.Wc()&&z.J.start()},mDT=function(z){if(z.U.isFullscreen()){var K;
z=(K=z.U.getVideoData())==null?void 0:K.GV;return z===-1||z===void 0?8E3:z}return z.U.dZ()>=0?z.U.dZ():g.uY(z.U.Z().experiments,"autoplay_time")||1E4},Hj2=function(z,K){K=K.getWatchNextResponse();
var f,M;K=(f=Pdo(K))==null?void 0:(M=f.nextButton)==null?void 0:M.buttonRenderer;z.W=K==null?void 0:K.navigationEndpoint;f=K==null?void 0:K.trackingParams;z.playButton&&f&&z.U.setTrackingParams(z.playButton.element,f)},lO7=function(z){var K;
return!((K=z.U.getVideoData())==null||!K.watchToWatchTransitionRenderer)},qfp=function(z,K){K=K===void 0?-1:K;
z=z.S.dE("ytp-autonav-endscreen-upnext-header");g.fs(z);if(K>=0){K=String(K);var f="Prochaine vid\u00e9o dans $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],M="Prochaine vid\u00e9o dans $SECONDS".indexOf(f);if(M>=0){z.appendChild(g.Ks("Prochaine vid\u00e9o dans $SECONDS".slice(0,M)));var p=g.zi("span");g.GJ(p,"ytp-autonav-endscreen-upnext-header-countdown-number");g.B6(p,K);z.appendChild(p);z.appendChild(g.Ks("Prochaine vid\u00e9o dans $SECONDS".slice(M+f.length)));return}}g.B6(z,"\u00c0 suivre")},
NV=function(z,K){g.F.call(this,{j:"div",
Wx:["html5-endscreen","ytp-player-content",K||"base-endscreen"]});this.created=!1;this.player=z},vH=function(z){g.F.call(this,{j:"div",
Wx:["ytp-upnext","ytp-player-content"],V:{"aria-label":"{{aria_label}}"},L:[{j:"div",K:"ytp-cued-thumbnail-overlay-image",V:{style:"{{background}}"}},{j:"span",K:"ytp-upnext-top",L:[{j:"span",K:"ytp-upnext-header",qc:"\u00c0 suivre"},{j:"span",K:"ytp-upnext-title",qc:"{{title}}"},{j:"span",K:"ytp-upnext-author",qc:"{{author}}"}]},{j:"a",K:"ytp-upnext-autoplay-icon",V:{role:"button",href:"{{url}}","aria-label":"Lire la vid\u00e9o suivante"},L:[{j:"svg",V:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},L:[{j:"circle",K:"ytp-svg-autoplay-circle",V:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{j:"circle",K:"ytp-svg-autoplay-ring",V:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{j:"path",K:"ytp-svg-fill",V:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{j:"span",K:"ytp-upnext-bottom",L:[{j:"span",K:"ytp-upnext-cancel"},{j:"span",K:"ytp-upnext-paused",
qc:"La lecture automatique est d\u00e9sactiv\u00e9e"}]}]});this.api=z;this.cancelButton=null;this.W=this.dE("ytp-svg-autoplay-ring");this.T=this.notification=this.S=this.suggestion=null;this.J=new g.Kl(this.n0,5E3,this);this.Y=0;var K=this.dE("ytp-upnext-cancel");this.cancelButton=new g.F({j:"button",Wx:["ytp-upnext-cancel-button","ytp-button"],V:{tabindex:"0","aria-label":"Annuler la lecture automatique"},qc:"Annuler"});g.d(this,this.cancelButton);this.cancelButton.listen("click",this.hX,this);this.cancelButton.hL(K);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.d(this,this.J);this.api.createClientVe(this.element,this,18788);K=this.dE("ytp-upnext-autoplay-icon");this.X(K,"click",this.cO);this.api.createClientVe(K,this,115130);this.IY();this.X(z,"autonavvisibility",this.IY);this.X(z,"mdxnowautoplaying",this.iIH);this.X(z,"mdxautoplaycanceled",this.F9V);g.k4(this.element,"ytp-upnext-mobile",this.api.Z().Y)},VJ5=function(z,K){if(K)return K;
if(z.api.isFullscreen()){var f;z=(f=z.api.getVideoData())==null?void 0:f.GV;return z===-1||z===void 0?8E3:z}return z.api.dZ()>=0?z.api.dZ():g.uY(z.api.Z().experiments,"autoplay_time")||1E4},nE9=function(z,K){K=VJ5(z,K);
var f=Math,M=f.min;var p=(0,g.X)()-z.Y;f=M.call(f,p,K);K=K===0?1:Math.min(f/K,1);z.W.setAttribute("stroke-dashoffset",""+-211*(K+1));K>=1&&z.Wc()&&z.api.getPresentingPlayerType()!==3?z.select(!0):z.Wc()&&z.S.start()},Im=function(z){NV.call(this,z,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.F({j:"div",K:"ytp-suggestion-panel",L:[{j:"div",Wx:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],qc:"Plus de vid\u00e9os"}]});this.D=new g.F({j:"div",K:"ytp-suggestions-container"});this.videos=[];this.T=null;this.W=this.G=!1;this.Y=new tF(this.player);g.d(this,this.Y);this.Y.hL(this.element);z.getVideoData().Ph?this.S=this.Y:(this.S=new vH(z),g.dq(this.player,this.S.element,4),g.d(this,this.S));this.overlay=new g.F({j:"div",
K:"ytp-autonav-overlay-cancelled-state"});g.d(this,this.overlay);this.overlay.hL(this.element);this.J=new g.xI(this);g.d(this,this.J);g.d(this,this.table);this.table.hL(this.element);this.table.show();g.d(this,this.D);this.D.hL(this.table.element);this.hide()},GY=function(z){var K=z.US();
K!==z.W&&(z.W=K,LHZ(z.player),z.W?(z.Y!==z.S&&z.Y.hide(),z.table.hide()):(z.Y!==z.S&&z.Y.show(),z.table.show()))},bX=function(z,K){g.F.call(this,{j:"button",
Wx:["ytp-watch-on-youtube-button","ytp-button"],qc:"{{content}}"});this.U=z;this.buttonType=this.buttonType=K;this.Vi();this.buttonType===2&&g.ey(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Vi);this.s3(!0)},eB=function(z,K){NV.call(this,z,"embeds-lite-endscreen");
this.U=z;this.S=K;this.U.createClientVe(this.element,this,156943);this.watchButton=new bX(z,2);g.d(this,this.watchButton);this.watchButton.hL(this.element);this.hide()},wu=function(z){var K=z.Z(),f=g.sq||g.nO?{style:"will-change: opacity"}:void 0,M=K.J,p=["ytp-modern-videowall-still"];
K.Y&&p.push("ytp-videowall-show-text");g.F.call(this,{j:"a",Wx:p,V:{href:"{{url}}",target:M?K.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{j:"div",K:"ytp-modern-videowall-still-image",V:{style:"{{background}}"},L:[{j:"span",K:"ytp-modern-videowall-still-info-duration",qc:"{{duration}}"}]},{j:"span",K:"ytp-modern-videowall-still-info",V:{"aria-hidden":"true"},L:[{j:"span",K:"ytp-modern-videowall-still-info-bg",L:[{j:"span",
K:"ytp-modern-videowall-still-info-content",V:f,L:[{j:"span",K:"ytp-modern-videowall-still-info-title",qc:"{{title}}"},{j:"span",K:"ytp-modern-videowall-still-info-author",qc:"{{author_and_views}}"},{j:"span",K:"ytp-modern-videowall-still-info-live",qc:"En direct"}]}]}]},{j:"span",Wx:["ytp-modern-videowall-still-listlabel-regular","ytp-modern-videowall-still-listlabel"],V:{"aria-hidden":"true"},L:[{j:"span",K:"ytp-modern-videowall-still-listlabel-icon"},"Playlist",{j:"span",K:"ytp-modern-videowall-still-listlabel-length",
L:[" (",{j:"span",qc:"{{playlist_length}}"},")"]}]},{j:"span",Wx:["ytp-modern-videowall-still-listlabel-mix","ytp-modern-videowall-still-listlabel"],V:{"aria-hidden":"true"},L:[{j:"span",K:"ytp-modern-videowall-still-listlabel-mix-icon"},"Mix",{j:"span",K:"ytp-modern-videowall-still-listlabel-length",qc:" (50+)"}]}]});this.suggestion=null;this.Y=M;this.api=z;this.S=new g.xI(this);g.d(this,this.S);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.S.X(z,"videodatachange",
this.onVideoDataChange);z.createServerVe(this.element,this);this.onVideoDataChange()},WHp=function(z){NV.call(this,z,"videowall-endscreen");
var K=this;this.U=z;this.stills=[];this.T=this.videoData=null;this.J=this.G=!1;this.D=null;g.ey(this.element,"modern-videowall-endscreen");this.Y=new g.xI(this);g.d(this,this.Y);this.W=new g.Kl(function(){g.ey(K.element,"ytp-show-tiles")},0);
g.d(this,this.W);this.table=new g.kl({j:"div",K:"ytp-modern-endscreen-content"});g.d(this,this.table);this.table.hL(this.element);z.getVideoData().Ph?this.S=new tF(z,!0):this.S=new vH(z);g.d(this,this.S);g.dq(this.player,this.S.element,4);z.createClientVe(this.element,this,158789);this.hide()},D7=function(z){return g.cD(z.player)&&z.F8()&&!z.T},y1=function(z){var K=z.US();
K!==z.G&&(z.G=K,LHZ(z.player))},Ju_=function(z){NV.call(this,z,"subscribecard-endscreen");
this.S=new g.F({j:"div",K:"ytp-subscribe-card",L:[{j:"img",K:"ytp-author-image",V:{src:"{{profilePicture}}"}},{j:"div",K:"ytp-subscribe-card-right",L:[{j:"div",K:"ytp-author-name",qc:"{{author}}"},{j:"div",K:"html5-subscribe-button-container"}]}]});g.d(this,this.S);this.S.hL(this.element);var K=z.getVideoData();this.subscribeButton=new g.Ky("S'abonner",null,"Se d\u00e9sabonner",null,!0,!1,K.rL,K.subscribed,"trailer-endscreen",null,z,!1);g.d(this,this.subscribeButton);this.subscribeButton.hL(this.S.dE("html5-subscribe-button-container"));
this.X(z,"videodatachange",this.Dq);this.Dq();this.hide()},ku=function(z){var K=z.Z(),f=g.sq||g.nO?{style:"will-change: opacity"}:void 0,M=K.J,p=["ytp-videowall-still"];
K.Y&&p.push("ytp-videowall-show-text");g.F.call(this,{j:"a",Wx:p,V:{href:"{{url}}",target:M?K.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{j:"div",K:"ytp-videowall-still-image",V:{style:"{{background}}"}},{j:"span",K:"ytp-videowall-still-info",V:{"aria-hidden":"true"},L:[{j:"span",K:"ytp-videowall-still-info-bg",L:[{j:"span",K:"ytp-videowall-still-info-content",V:f,L:[{j:"span",K:"ytp-videowall-still-info-title",qc:"{{title}}"},
{j:"span",K:"ytp-videowall-still-info-author",qc:"{{author_and_views}}"},{j:"span",K:"ytp-videowall-still-info-live",qc:"En direct"},{j:"span",K:"ytp-videowall-still-info-duration",qc:"{{duration}}"}]}]}]},{j:"span",Wx:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],V:{"aria-hidden":"true"},L:[{j:"span",K:"ytp-videowall-still-listlabel-icon"},"Playlist",{j:"span",K:"ytp-videowall-still-listlabel-length",L:[" (",{j:"span",qc:"{{playlist_length}}"},")"]}]},{j:"span",Wx:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],V:{"aria-hidden":"true"},L:[{j:"span",K:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{j:"span",K:"ytp-videowall-still-listlabel-length",qc:" (50+)"}]}]});this.suggestion=null;this.Y=M;this.api=z;this.S=new g.xI(this);g.d(this,this.S);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.S.X(z,"videodatachange",this.onVideoDataChange);z.createServerVe(this.element,this);this.onVideoDataChange()},hF=function(z){NV.call(this,z,"videowall-endscreen");
var K=this;this.U=z;this.T=0;this.stills=[];this.J=this.videoData=null;this.W=this.D=!1;this.N=null;this.Y=new g.xI(this);g.d(this,this.Y);this.G=new g.Kl(function(){g.ey(K.element,"ytp-show-tiles")},0);
g.d(this,this.G);var f=new g.F({j:"button",Wx:["ytp-button","ytp-endscreen-previous"],V:{"aria-label":"Pr\u00e9c\u00e9dente"},L:[g.HW()]});g.d(this,f);f.hL(this.element);f.listen("click",this.Ct,this);this.table=new g.kl({j:"div",K:"ytp-endscreen-content"});g.d(this,this.table);this.table.hL(this.element);f=new g.F({j:"button",Wx:["ytp-button","ytp-endscreen-next"],V:{"aria-label":"Suivante"},L:[g.Qb()]});g.d(this,f);f.hL(this.element);f.listen("click",this.IB,this);z.getVideoData().Ph?this.S=new tF(z,
!0):this.S=new vH(z);g.d(this,this.S);g.dq(this.player,this.S.element,4);z.createClientVe(this.element,this,158789);this.hide()},am=function(z){return g.cD(z.player)&&z.F8()&&!z.J},Rm=function(z){var K=z.US();
K!==z.D&&(z.D=K,LHZ(z.player))},SB=function(z){NV.call(this,z,"watch-again-on-youtube-endscreen");
this.watchButton=new bX(z,1);g.d(this,this.watchButton);this.watchButton.hL(this.element);g.HW1(z)&&(this.S=new g.Ub(z),g.d(this,this.S),this.Y=new g.F({j:"div",Wx:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],V:{tabIndex:"-1"},L:[this.S]}),g.d(this,this.Y),this.S.hL(this.Y.element),this.Y.hL(this.element));z.createClientVe(this.element,this,156914);this.hide()},cu_=function(z){g.R5.call(this,z);
var K=this;this.endScreen=null;this.Y=this.S=this.T=this.J=!1;this.listeners=new g.xI(this);g.d(this,this.listeners);var f=z.Z(),M=z.getVideoData();M=M&&M.limitedPlaybackDurationInSeconds!==0;g.yS(g.Xf(f))&&M&&!g.WD(z)?(this.Y=!0,this.endScreen=new eB(z,g.aN(z))):z.isEmbedsShortsMode()?this.endScreen=new SB(z):gE9(z)?(this.J=!0,ij8(this),this.S?this.endScreen=new Im(z):f.B("delhi_modern_endscreen")?this.endScreen=new WHp(z):this.endScreen=new hF(z)):f.Hm?this.endScreen=new Ju_(z):this.endScreen=new NV(z);
g.d(this,this.endScreen);g.dq(z,this.endScreen.element,4);dDH(this);this.listeners.X(z,"videodatachange",this.onVideoDataChange,this);this.listeners.X(z,g.wE("endscreen"),function(p){K.onCueRangeEnter(p)});
this.listeners.X(z,g.DU("endscreen"),function(p){K.onCueRangeExit(p)})},ij8=function(z){var K=z.player.getVideoData();
if(!K||z.S===K.yL&&z.T===K.Ph)return!1;z.S=K.yL;z.T=K.Ph;return!0},gE9=function(z){z=z.Z();
return z.QW&&!z.Hm&&!z.disableOrganicUi},dDH=function(z){z.player.GE("endscreen");
var K=z.player.getVideoData();K=new g.bS(Math.max((K.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var f=new g.bS(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});z.player.St([K,f])};
g.m8.prototype.dZ=g.pW(14,function(){return this.app.dZ()});
g.hJ.prototype.dZ=g.pW(13,function(){return this.getVideoData().G4});
g.PD.prototype.Wn=g.pW(12,function(z){this.Cb().Wn(z)});
g.Dn.prototype.Wn=g.pW(11,function(z){this.S!==z&&(this.S=z,this.Dq())});
g.nY.prototype.Wn=g.pW(10,function(z){this.overflowButton&&this.overflowButton.Wn(z)});
g.PD.prototype.mD=g.pW(9,function(z){this.Cb().mD(z)});
g.SY.prototype.mD=g.pW(8,function(z){this.Y!==z&&(this.Y=z,this.Dq())});
g.nY.prototype.mD=g.pW(7,function(z){this.shareButton&&this.shareButton.mD(z)});
g.PD.prototype.Xj=g.pW(6,function(z){this.Cb().Xj(z)});
g.r1.prototype.Xj=g.pW(5,function(z){this.fm!==z&&(this.fm=z,this.LN())});
g.PD.prototype.Fj=g.pW(4,function(z){this.Cb().Fj(z)});
g.nY.prototype.Fj=g.pW(3,function(z){this.gg!==z&&(this.gg=z,this.DK())});g.h(p4,g.F);p4.prototype.select=function(){this.U.by(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.p4||void 0)&&this.U.logClick(this.element)};
p4.prototype.onClick=function(z){g.v1(z,this.U,this.S,this.suggestion.sessionData||void 0)&&this.select()};
p4.prototype.onKeyPress=function(z){switch(z.keyCode){case 13:case 32:z.defaultPrevented||(this.select(),z.preventDefault())}};g.h(tF,g.F);g.k=tF.prototype;g.k.uC=function(z){this.suggestion!==z&&(this.suggestion=z,MV(this.S,z),this.playButton.updateValue("url",this.suggestion.xv()),BH(this))};
g.k.Wc=function(){return this.T>0};
g.k.fK=function(){this.Wc()||(this.T=Date.now(),QtH(this),EEo(this.U,mDT(this)),g.k4(this.U.getRootNode(),"countdown-running",this.Wc()))};
g.k.mA=function(){this.dU();QtH(this);var z=this.S.dE("ytp-autonav-endscreen-upnext-header");z&&g.B6(z,"\u00c0 suivre")};
g.k.dU=function(){this.Wc()&&(this.J.stop(),this.T=0)};
g.k.select=function(z){this.U.nextVideo(!1,z===void 0?!1:z);this.dU()};
g.k.vG=function(z){g.v1(z,this.U)&&(z.currentTarget===this.playButton.element?this.U.logClick(this.playButton.element):z.currentTarget===this.S.dE("ytp-autonav-endscreen-link-container")&&(z=this.S.dE("ytp-autonav-endscreen-link-container"),this.U.logVisibility(z,!0),this.U.logClick(z)),this.W?(this.U.LH("innertubeCommand",this.W),this.dU()):this.select())};
g.k.xE=function(){this.U.logClick(this.cancelButton.element);g.Vp(this.U,!0);this.cancelCommand&&this.U.LH("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(z,K){Hj2(this,K);z=K.getWatchNextResponse();var f,M;z=(f=Pdo(z))==null?void 0:(M=f.cancelButton)==null?void 0:M.buttonRenderer;this.cancelCommand=z==null?void 0:z.command};
g.k.bHL=function(z){if(lO7(this)){var K=this.U.getVideoData().watchToWatchTransitionRenderer,f=K==null?void 0:K.fromColorPaletteDark;K=K==null?void 0:K.toColorPaletteDark;if(f&&K){var M=this.element;M.style.setProperty("--w2w-start-background-color",g.rc(f.surgeColor));M.style.setProperty("--w2w-start-primary-text-color",g.rc(f.primaryTitleColor));M.style.setProperty("--w2w-start-secondary-text-color",g.rc(f.secondaryTitleColor));M.style.setProperty("--w2w-end-background-color",g.rc(K.surgeColor));
M.style.setProperty("--w2w-end-primary-text-color",g.rc(K.primaryTitleColor));M.style.setProperty("--w2w-end-secondary-text-color",g.rc(K.secondaryTitleColor));M.style.setProperty("--w2w-animation-duration",z+"ms")}g.k4(this.element,"ytp-w2w-animate",!0)}};
g.k.HO=function(z){this.U.B("web_autonav_color_transition")&&z!==2&&g.k4(this.element,"ytp-w2w-animate",!1)};
g.k.WG=function(){var z=this.U.US();this.G&&this.l8!==z&&this.s3(z);BH(this);this.U.logVisibility(this.container.element,z);this.U.logVisibility(this.cancelButton.element,z);this.U.logVisibility(this.S.dE("ytp-autonav-endscreen-link-container"),z);this.U.logVisibility(this.playButton.element,z)};
g.k.wI=function(z){return z.width<400||z.height<459};g.h(NV,g.F);g.k=NV.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.F8=function(){return!1};
g.k.US=function(){return!1};
g.k.JC=function(){return!1};g.h(vH,g.F);g.k=vH.prototype;g.k.n0=function(){this.notification&&(this.J.stop(),this.W8(this.T),this.T=null,this.notification.close(),this.notification=null)};
g.k.uC=function(z){this.suggestion=z;MV(this,z,"hqdefault.jpg")};
g.k.IY=function(){this.s3(this.api.US());this.api.logVisibility(this.element,this.api.US());this.api.logVisibility(this.dE("ytp-upnext-autoplay-icon"),this.api.US());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.US())};
g.k.ZIx=function(){window.focus();this.n0()};
g.k.fK=function(z){var K=this;this.Wc()||(g.bi("a11y-announce","\u00c0 suivre "+this.suggestion.title),this.Y=(0,g.X)(),this.S=new g.Kl(function(){nE9(K,z)},25),nE9(this,z),EEo(this.api,VJ5(this,z)));
g.Dz(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.F.prototype.hide.call(this)};
g.k.Wc=function(){return!!this.S};
g.k.mA=function(){this.dU();this.Y=(0,g.X)();nE9(this);g.ey(this.element,"ytp-upnext-autoplay-paused")};
g.k.dU=function(){this.Wc()&&(this.S.dispose(),this.S=null)};
g.k.select=function(z){z=z===void 0?!1:z;if(this.api.Z().B("autonav_notifications")&&z&&window.Notification&&typeof document.hasFocus==="function"){var K=Notification.permission;K==="default"?Notification.requestPermission():K!=="granted"||document.hasFocus()||(this.n0(),this.notification=new Notification("\u00c0 suivre",{body:this.suggestion.title,icon:this.suggestion.JJ()}),this.T=this.X(this.notification,"click",this.ZIx),this.J.start())}this.dU();this.api.nextVideo(!1,z)};
g.k.cO=function(z){!g.t$(this.cancelButton.element,z.target)&&g.v1(z,this.api)&&(this.api.US()&&this.api.logClick(this.dE("ytp-upnext-autoplay-icon")),this.select())};
g.k.hX=function(){this.api.US()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.Vp(this.api,!0)};
g.k.iIH=function(z){this.api.getPresentingPlayerType();this.show();this.fK(z)};
g.k.F9V=function(){this.api.getPresentingPlayerType();this.dU();this.hide()};
g.k.JL=function(){this.dU();this.n0();g.F.prototype.JL.call(this)};g.h(Im,NV);g.k=Im.prototype;g.k.create=function(){NV.prototype.create.call(this);this.J.X(this.player,"appresize",this.Dc);this.J.X(this.player,"onVideoAreaChange",this.Dc);this.J.X(this.player,"videodatachange",this.onVideoDataChange);this.J.X(this.player,"autonavchange",this.CA);this.J.X(this.player,"onAutonavCancelled",this.UY);this.onVideoDataChange()};
g.k.show=function(){NV.prototype.show.call(this);(this.G||this.T&&this.T!==this.videoData.clientPlaybackNonce)&&g.Vp(this.player,!1);g.cD(this.player)&&this.F8()&&!this.T?(GY(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.S.select(!0):this.S.fK():this.videoData.autonavState===3&&this.S.mA()):(g.Vp(this.player,!0),GY(this));this.Dc()};
g.k.hide=function(){NV.prototype.hide.call(this);this.S.mA();GY(this)};
g.k.Dc=function(){var z=this.player.hD(!0,this.player.isFullscreen());GY(this);BH(this.Y);g.k4(this.element,"ytp-autonav-cancelled-small-mode",this.wI(z));g.k4(this.element,"ytp-autonav-cancelled-tiny-mode",this.s6(z));g.k4(this.element,"ytp-autonav-cancelled-mini-mode",z.width<=400||z.height<=360);this.overlay&&g.H6(this.overlay.element,{width:z.width+"px"});if(!this.W)for(z=0;z<this.videos.length;z++)g.k4(this.videos[z].element,"ytp-suggestion-card-with-margin",z%2===1)};
g.k.onVideoDataChange=function(){var z=this.player.getVideoData();if(this.videoData!==z&&z){this.videoData=z;if((z=this.videoData.suggestions)&&z.length||this.player.B("web_player_autonav_empty_suggestions_fix")){var K=g.ME(this.videoData);K&&(this.S.uC(K),this.S!==this.Y&&this.Y.uC(K))}if(z&&z.length)for(K=0;K<st_.length;++K){var f=st_[K];if(z&&z[f]){this.videos[K]=new p4(this.player);var M=this.videos[K];f=z[f];M.suggestion!==f&&(M.suggestion=f,MV(M,f));g.d(this,this.videos[K]);this.videos[K].hL(this.D.element)}}this.Dc()}};
g.k.CA=function(z){z===1?(this.G=!1,this.T=this.videoData.clientPlaybackNonce,this.S.dU(),this.l8&&this.Dc()):(this.G=!0,this.US()&&(z===2?this.S.fK():z===3&&this.S.mA()))};
g.k.UY=function(z){z?this.CA(1):(this.T=null,this.G=!1)};
g.k.F8=function(){return this.videoData.autonavState!==1};
g.k.wI=function(z){return(z.width<910||z.height<459)&&!this.s6(z)&&!(z.width<=400||z.height<=360)};
g.k.s6=function(z){return z.width<800&&!(z.width<=400||z.height<=360)};
g.k.US=function(){return this.l8&&g.cD(this.player)&&this.F8()&&!this.T};
var st_=[1,3,2,4];g.h(bX,g.F);g.k=bX.prototype;g.k.Vi=function(){switch(this.buttonType){case 1:var z="Regarder \u00e0 nouveau sur YouTube";var K=156915;break;case 2:z="Continuer \u00e0 regarder sur YouTube";K=156942;break;default:z="Continuer \u00e0 regarder sur YouTube",K=156942}this.update({content:z});this.U.hasVe(this.element)&&this.U.destroyVe(this.element);this.U.createClientVe(this.element,this,K)};
g.k.onClick=function(z){this.U.B("web_player_log_click_before_generating_ve_conversion_params")&&this.U.logClick(this.element);g.I0(this.getVideoUrl(),this.U,z);this.U.B("web_player_log_click_before_generating_ve_conversion_params")||this.U.logClick(this.element)};
g.k.getVideoUrl=function(){var z=!0;switch(this.buttonType){case 1:z=!0;break;case 2:z=!1}z=this.U.getVideoUrl(z,!1,!1,!0);var K=this.U.Z();if(g.Jw(K)){var f={};g.Jw(K)&&g.wq(this.U,"addEmbedsConversionTrackingParams",[f]);z=g.V8(z,f)}return z};
g.k.logVisibility=function(){this.U.logVisibility(this.element,this.l8&&this.C)};
g.k.show=function(){g.F.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.F.prototype.hide.call(this);this.logVisibility()};
g.k.Xt=function(z){g.F.prototype.Xt.call(this,z);this.logVisibility()};g.h(eB,NV);eB.prototype.show=function(){this.player.getPlayerState()!==3&&(NV.prototype.show.call(this),this.S.Fj(!0),this.S.mD(!0),this.U.Z().b3||this.S.Wn(!0),this.U.logVisibility(this.element,!0),this.watchButton.Xt(!0))};
eB.prototype.hide=function(){NV.prototype.hide.call(this);this.S.Fj(!1);this.S.mD(!1);this.S.Wn(!1);this.U.logVisibility(this.element,!1);this.watchButton.Xt(!1)};g.h(wu,g.F);wu.prototype.select=function(){this.api.by(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.p4||void 0)&&this.api.logClick(this.element)};
wu.prototype.onClick=function(z){if(g.Jw(this.api.Z())&&this.api.B("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var K=this.suggestion.xv(),f={};g.JT(this.api,f);K=g.V8(K,f);g.I0(K,this.api,z)}else g.v1(z,this.api,this.Y,this.suggestion.sessionData||void 0)&&this.select()};
wu.prototype.onKeyPress=function(z){switch(z.keyCode){case 13:case 32:z.defaultPrevented||(this.select(),z.preventDefault())}};
wu.prototype.onVideoDataChange=function(){var z=this.api.getVideoData(),K=this.api.Z();this.Y=z.f3?!1:K.J};g.h(WHp,NV);g.k=WHp.prototype;g.k.create=function(){NV.prototype.create.call(this);var z=this.player.getVideoData();z&&(this.videoData=z);this.yz();this.Y.X(this.player,"appresize",this.yz);this.Y.X(this.player,"onVideoAreaChange",this.yz);this.Y.X(this.player,"videodatachange",this.onVideoDataChange);this.Y.X(this.player,"autonavchange",this.e2);this.Y.X(this.player,"onAutonavCancelled",this.WO);z=this.videoData.autonavState;z!==this.D&&this.e2(z);this.Y.X(this.element,"transitionend",this.m8)};
g.k.destroy=function(){g.g0(this.Y);g.yj(this.stills);this.stills=[];NV.prototype.destroy.call(this);g.Dz(this.element,"ytp-show-tiles");this.W.stop();this.D=this.videoData.autonavState};
g.k.F8=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var z=this.l8;NV.prototype.show.call(this);g.Dz(this.element,"ytp-show-tiles");this.player.Z().Y?g.pl(this.W):this.W.start();(this.J||this.T&&this.T!==this.videoData.clientPlaybackNonce)&&g.Vp(this.player,!1);D7(this)?(y1(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.S.select(!0):this.S.fK():this.videoData.autonavState===3&&this.S.mA()):(g.Vp(this.player,!0),y1(this));z!==this.l8&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var z=this.l8;NV.prototype.hide.call(this);this.S.mA();y1(this);z!==this.l8&&this.player.logVisibility(this.element,!1)};
g.k.m8=function(z){z.target===this.element&&this.yz()};
g.k.yz=function(){var z,K,f,M;var p=((z=this.videoData)==null?0:(K=z.suggestions)==null?0:K.length)?(f=this.videoData)==null?void 0:f.suggestions:[(M=this.videoData)==null?void 0:g.ME(M)];if(p.length){K=this.U.hD(!0,this.U.isFullscreen());z=Math.floor((K.width-64+16)/(g.qt(K.width*.27,250,450)+16));K=Math.min(3,Math.floor((K.height-64)/((K.width-64-(z-1)*16)/z*.5625+70)));g.yf(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.ey(this.element,"ytp-modern-endscreen-limit-rows-"+K);g.k4(this.element,"ytp-modern-endscreen-single-item",z===1);g.k4(this.element,"ytp-modern-endscreen-row-0",K===0);z=this.table.element;z.ariaLive="polite";this.S.uC(g.ME(this.videoData));this.S instanceof tF&&BH(this.S);g.k4(this.element,"ytp-endscreen-takeover",D7(this));y1(this);K=0;z.ariaBusy="true";f=p.length;for(M=0;M<f;M++){var t=M%f,B=this.stills[M];B||(B=new wu(this.player),this.stills[M]=B,z.appendChild(B.element));t=p[t];if(B.suggestion!==
t){B.suggestion=t;var v=B.api.Z();MV(B,t,"hqdefault.jpg");if(g.Jw(v)&&!B.api.B("web_player_log_click_before_generating_ve_conversion_params")){v=t.xv();var I={};g.wq(B.api,"addEmbedsConversionTrackingParams",[I]);v=g.V8(v,I);B.updateValue("url",v)}(t=(t=t.sessionData)&&t.itct)&&B.api.setTrackingParams(B.element,t)}K++}this.stills.length=K}};
g.k.onVideoDataChange=function(){var z=this.player.getVideoData(1);this.videoData!==z&&(z!=null&&g.ME(z)?(this.videoData=z,this.yz()):this.player.Th("missg",{vid:(z==null?void 0:z.videoId)||"",cpn:(z==null?void 0:z.clientPlaybackNonce)||""}))};
g.k.JC=function(){return this.S.Wc()};
g.k.e2=function(z){z===1?(this.J=!1,this.T=this.videoData.clientPlaybackNonce,this.S.dU(),this.l8&&this.yz()):(this.J=!0,this.l8&&D7(this)&&(z===2?this.S.fK():z===3&&this.S.mA()))};
g.k.WO=function(z){if(z){for(z=0;z<this.stills.length;z++)this.U.logVisibility(this.stills[z].element,!0);this.e2(1)}else this.T=null,this.J=!1;this.yz()};
g.k.US=function(){return this.l8&&D7(this)};g.h(Ju_,NV);Ju_.prototype.Dq=function(){var z=this.player.getVideoData();this.S.update({profilePicture:z.profilePicture,author:z.author});this.subscribeButton.channelId=z.rL;var K=this.subscribeButton;z.subscribed?K.S():K.Y()};g.h(ku,g.F);ku.prototype.select=function(){this.api.by(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.p4||void 0)&&this.api.logClick(this.element)};
ku.prototype.onClick=function(z){if(g.Jw(this.api.Z())&&this.api.B("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var K=this.suggestion.xv(),f={};g.JT(this.api,f);K=g.V8(K,f);g.I0(K,this.api,z)}else g.v1(z,this.api,this.Y,this.suggestion.sessionData||void 0)&&this.select()};
ku.prototype.onKeyPress=function(z){switch(z.keyCode){case 13:case 32:z.defaultPrevented||(this.select(),z.preventDefault())}};
ku.prototype.onVideoDataChange=function(){var z=this.api.getVideoData(),K=this.api.Z();this.Y=z.f3?!1:K.J};g.h(hF,NV);g.k=hF.prototype;g.k.create=function(){NV.prototype.create.call(this);var z=this.player.getVideoData();z&&(this.videoData=z);this.Jn();this.Y.X(this.player,"appresize",this.Jn);this.Y.X(this.player,"onVideoAreaChange",this.Jn);this.Y.X(this.player,"videodatachange",this.onVideoDataChange);this.Y.X(this.player,"autonavchange",this.xC);this.Y.X(this.player,"onAutonavCancelled",this.vO);z=this.videoData.autonavState;z!==this.N&&this.xC(z);this.Y.X(this.element,"transitionend",this.BO)};
g.k.destroy=function(){g.g0(this.Y);g.yj(this.stills);this.stills=[];NV.prototype.destroy.call(this);g.Dz(this.element,"ytp-show-tiles");this.G.stop();this.N=this.videoData.autonavState};
g.k.F8=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var z=this.l8;NV.prototype.show.call(this);g.Dz(this.element,"ytp-show-tiles");this.player.Z().Y?g.pl(this.G):this.G.start();(this.W||this.J&&this.J!==this.videoData.clientPlaybackNonce)&&g.Vp(this.player,!1);am(this)?(Rm(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.S.select(!0):this.S.fK():this.videoData.autonavState===3&&this.S.mA()):(g.Vp(this.player,!0),Rm(this));z!==this.l8&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var z=this.l8;NV.prototype.hide.call(this);this.S.mA();Rm(this);z!==this.l8&&this.player.logVisibility(this.element,!1)};
g.k.BO=function(z){z.target===this.element&&this.Jn()};
g.k.Jn=function(){var z,K,f,M;var p=((z=this.videoData)==null?0:(K=z.suggestions)==null?0:K.length)?(f=this.videoData)==null?void 0:f.suggestions:[(M=this.videoData)==null?void 0:g.ME(M)];if(p.length){g.ey(this.element,"ytp-endscreen-paginate");var t=this.U.hD(!0,this.U.isFullscreen());if(z=g.aN(this.U))z=z.po()?48:32,t.width-=z*2;var B=t.width/t.height;M=96/54;K=z=2;var v=Math.max(t.width/96,2),I=Math.max(t.height/54,2);f=p.length;var G=f*4;for(G-=4;G>0&&(z<v||K<I);){var b=z/2,e=K/2,w=z<=v-2&&G>=
e*4,D=K<=I-2&&G>=b*4;if((b+1)/e*M/B>B/(b/(e+1)*M)&&D)G-=b*4,K+=2;else if(w)G-=e*4,z+=2;else if(D)G-=b*4,K+=2;else break}M=!1;G>=12&&f*4-G<=6&&(K>=4||z>=4)&&(M=!0);G=z*96;v=K*54;B=G/v<B?t.height/v:t.width/G;B=Math.min(B,2);G=Math.floor(Math.min(t.width,G*B));v=Math.floor(Math.min(t.height,v*B));t=this.table.element;t.ariaLive="polite";g.ip(t,G,v);g.H6(t,{marginLeft:G/-2+"px",marginTop:v/-2+"px"});this.S.uC(g.ME(this.videoData));this.S instanceof tF&&BH(this.S);g.k4(this.element,"ytp-endscreen-takeover",
am(this));Rm(this);G+=4;v+=4;B=0;t.ariaBusy="true";for(I=0;I<z;I++)for(b=0;b<K;b++)if(e=B,D=0,M&&I>=z-2&&b>=K-2?D=1:b%2===0&&I%2===0&&(b<2&&I<2?b===0&&I===0&&(D=2):D=2),e=g.mM(e+this.T,f),D!==0){w=this.stills[B];w||(w=new ku(this.player),this.stills[B]=w,t.appendChild(w.element));var y=Math.floor(v*b/K),R=Math.floor(G*I/z),S=Math.floor(v*(b+D)/K)-y-4,E=Math.floor(G*(I+D)/z)-R-4;g.ns(w.element,R,y);g.ip(w.element,E,S);g.H6(w.element,"transitionDelay",(b+I)/20+"s");g.k4(w.element,"ytp-videowall-still-mini",
D===1);g.k4(w.element,"ytp-videowall-still-large",D>2);D=Math.max(E,S);g.k4(w.element,"ytp-videowall-still-round-large",D>=256);g.k4(w.element,"ytp-videowall-still-round-medium",D>96&&D<256);g.k4(w.element,"ytp-videowall-still-round-small",D<=96);e=p[e];w.suggestion!==e&&(w.suggestion=e,D=w.api.Z(),y=g.bx(w.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",MV(w,e,y),g.Jw(D)&&!w.api.B("web_player_log_click_before_generating_ve_conversion_params")&&(D=e.xv(),y={},g.wq(w.api,"addEmbedsConversionTrackingParams",
[y]),D=g.V8(D,y),w.updateValue("url",D)),(e=(e=e.sessionData)&&e.itct)&&w.api.setTrackingParams(w.element,e));B++}t.ariaBusy="false";g.k4(this.element,"ytp-endscreen-paginate",B<f);for(p=this.stills.length-1;p>=B;p--)z=this.stills[p],g.ps(z.element),g.DO(z);this.stills.length=B}};
g.k.onVideoDataChange=function(){var z=this.player.getVideoData(1);this.videoData!==z&&(z!=null&&g.ME(z)?(this.T=0,this.videoData=z,this.Jn()):this.player.Th("missg",{vid:(z==null?void 0:z.videoId)||"",cpn:(z==null?void 0:z.clientPlaybackNonce)||""}))};
g.k.IB=function(){this.T+=this.stills.length;this.Jn()};
g.k.Ct=function(){this.T-=this.stills.length;this.Jn()};
g.k.JC=function(){return this.S.Wc()};
g.k.xC=function(z){z===1?(this.W=!1,this.J=this.videoData.clientPlaybackNonce,this.S.dU(),this.l8&&this.Jn()):(this.W=!0,this.l8&&am(this)&&(z===2?this.S.fK():z===3&&this.S.mA()))};
g.k.vO=function(z){if(z){for(z=0;z<this.stills.length;z++)this.U.logVisibility(this.stills[z].element,!0);this.xC(1)}else this.J=null,this.W=!1;this.Jn()};
g.k.US=function(){return this.l8&&am(this)};g.h(SB,NV);SB.prototype.hasSuggestions=function(){var z;return(z=this.S)==null?void 0:z.hasSuggestions()};
SB.prototype.show=function(){if(this.player.getPlayerState()!==3){NV.prototype.show.call(this);var z=this.Y;if(z){var K=this.S.hasSuggestions();g.k4(this.element,"ytp-shorts-branded-ui",K);K?z.show():z.hide()}var f;(f=g.aN(this.player))==null||f.Xj(!0);this.player.logVisibility(this.element,!0);this.watchButton.Xt(!0)}};
SB.prototype.hide=function(){NV.prototype.hide.call(this);var z;(z=g.aN(this.player))==null||z.Xj(!1);this.player.logVisibility(this.element,!1);this.watchButton.Xt(!1)};g.h(cu_,g.R5);g.k=cu_.prototype;g.k.F7=function(){var z=this.player.getVideoData(),K=z.mutedAutoplay&&(z.limitedPlaybackDurationInSeconds>0||z.endSeconds>0||z.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.Y)&&!K)return!0;var f;var M=!!((z==null?0:g.ME(z))||(z==null?0:(f=z.suggestions)==null?0:f.length));M=!gE9(this.player)||M;z=z.Zh;f=this.player.BF();return M&&!z&&!f&&!K};
g.k.US=function(){return this.endScreen.US()};
g.k.Pl=function(){return this.US()?this.endScreen.JC():!1};
g.k.JL=function(){this.player.GE("endscreen");g.R5.prototype.JL.call(this)};
g.k.load=function(){var z=this.player.getVideoData();var K=z.transitionEndpointAtEndOfStream;if(K&&K.videoId){var f=this.player.pI().yR.get("heartbeat"),M=g.ME(z);!M||K.videoId!==M.videoId||z.dP?(this.player.by(K.videoId,void 0,void 0,!0,!0,K),f&&f.Yr("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),z=!0):z=!1}else z=!1;z||(g.R5.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.R5.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(z){this.F7()&&(this.endScreen.created||this.endScreen.create(),z.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(z){z.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){dDH(this);this.J&&ij8(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.S?this.endScreen=new Im(this.player):this.endScreen=new hF(this.player),g.d(this,this.endScreen),g.dq(this.player,this.endScreen.element,4))};g.a5("endscreen",cu_);})(_yt_player);
